/* Čeština. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — domů',
  'fejlec.menuNyit': 'Otevřít nabídku',
  'fejlec.menuZar': 'Zavřít nabídku',
  'fejlec.foMenu': 'Hlavní nabídka',
  'fejlec.sotetMod': 'Přepnout tmavý režim',
  'fejlec.fok': 'Teď {fok} stupňů — {ido}',
  'fejlec.jelenleg': 'Právě teď',

  'menu.fooldal': 'Domů',
  'menu.fooldalLeiras': 'Turistické značky, příklady a názory',
  'menu.tervezo': 'Plánovač',
  'menu.tervezoLeiras': 'Zadej dvě místa nebo kresli do mapy',
  'menu.peldak': 'Příklady',
  'menu.peldakLeiras': 'Hotové trasy, ze kterých můžeš vyjít',

  'lab.terkep': 'Mapu tvoří přispěvatelé {osm}, kteří dodávají i dlaždice.',
  'lab.becsles': 'Vzdálenost a čas chůze jsou odhady — v terénu platí značené turistické cesty.',
  'lab.impresszum': 'O stránce a ochrana údajů',

  'fooldal.cim': 'Túrabakancs — mapa pro plánování turistických tras',
  'fooldal.lead': 'Mapa, do které se dá kreslit. Hotové túry na začátek. Čas chůze, který počítá i se stoupáním.',
  'fooldal.tervezek': 'Naplánuju túru',
  'fooldal.peldak': 'Podívám se na příklady',
  'fooldal.ma': 'Dnes',
  'fooldal.napkelte': 'východ slunce',
  'fooldal.napnyugta': 'západ slunce',
  'fooldal.vilagosMeg': 'ještě světla',
  'fooldal.lement': 'zapadlo',
  'fooldal.vanMeg': 'ještě je světlo',
  'fooldal.marLement': 'slunce už zapadlo',
  'fooldal.napAlap': 'Pro Budapešť. Plánovač počítá se začátkem tvé vlastní trasy.',
  'fooldal.jelzesCim': 'Co znamená barva na stromě?',
  'fooldal.jelzesLead': 'Maďarská turistická značka říká dvě věci najednou. Barva to, jak velká trasa je, tvar to, k čemu slouží.',
  'fooldal.jelzesSzin': 'barva',
  'fooldal.jelzesAlak': 'tvar',
  'fooldal.jelzesApro': 'Nepsali jsme to zpaměti: ověřili jsme si na značených cestách v OpenStreetMap, co kam vede. Trasy s trojúhelníkem končí na vrcholu nebo u rozhledny, trasy s kruhem se vracejí tam, odkud vyšly.',
  'fooldal.keszVonal': 'Začni hotovou trasou',
  'fooldal.keszVonalLead': 'Otevři ji, popotáhni body, udělej si ji vlastní.',
  'fooldal.szerintunk': 'podle nás',
  'fooldal.osszesPelda': 'Všechny příklady →',

  'peldak.kicsi': 'Příklady',
  'peldak.cim': 'Hotové trasy, ze kterých můžeš vyjít.',
  'peldak.bevezeto': 'Otevři kteroukoli, popotáhni body, přidej vlastní značky — a je tvoje.',
  'peldak.tajegyseg': 'Oblast',
  'peldak.mindegyik': 'Všechny',
  'peldak.hossz': 'Délka',
  'peldak.nehezseg': 'Náročnost',
  'peldak.torold': 'smazat vše',
  'peldak.szurokTorol': 'zrušit filtry',
  'peldak.utvonal': 'tras',
  'peldak.megnezem': 'Zobrazit',
  'peldak.gyalogut': 'Trasy vedou po skutečných pěších cestách',
  'peldak.gyalogutUtan': ', ne po přímce mezi dvěma body — proto vzdálenost a stoupání sedí. V terénu stejně platí značené cesty a oficiální mapy.',
  'peldak.darab': '{db} tras',

  'utvonal.nincs': 'Tato trasa neexistuje.',
  'utvonal.tobbi': 'Tady jsou ostatní příklady.',
  'utvonal.hossz': 'Délka',
  'utvonal.sik': 'Počítáno pro rovinu; do kopce víc.',
  'utvonal.jelolesek': 'Značky',
  'utvonal.kozelito': 'Přibližný průběh, ne zaměřená turistická cesta.',
  'utvonal.megnyitas': 'Otevřít v plánovači',
  'utvonal.gpx': 'Stáhnout GPX',

  'tervezo.honnanHova': 'Odkud kam?',
  'tervezo.adatok': 'Údaje o trase',
  'tervezo.adatokCimke': 'Údaje o trase — {km}, {ido}',
  'tervezo.eszkozok': 'Uložení, hotové trasy, GPX',
  'tervezo.vissza': 'O krok zpět',
  'tervezo.retegek': 'Co má mapa ukazovat',
  'tervezo.ujraKeres': 'Hledat v této oblasti',

  'hh.honnan': 'Odkud',
  'hh.hova': 'Kam — když necháš prázdné, jen tam skočíme',
  'hh.honnanHely': 'Název místa nebo souřadnice',
  'hh.hovaHely': 'Například: Sněžka',
  'hh.innen': 'Vyrazím odsud',
  'hh.odaugras': 'Skočit tam',
  'hh.szamolom': 'Počítám…',
  'hh.utvonalat': 'Chci trasu',
  'hh.keres': 'Hledám…',
  'hh.nincsHelyzet': 'Nepodařilo se zjistit tvou polohu. Zadej výchozí bod ručně.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'délka',
  'adat.emelkedo': 'stoupání',
  'adat.lejto': 'klesání',
  'adat.nehezseg': 'náročnost',
  'adat.tempo': 'Tempo',
  'adat.tengerszint': '{also}–{felso} m n. m.',
  'adat.nev': 'Například: nedělní okruh',

  'terkep.igazit': 'Přikládám linii na skutečné pěší cesty…',
  'terkep.masodik': 'Označ druhý bod — linie si sama sedne na cestu.',
  'terkep.keszUt': 'Trasa hotová. Klepni do mapy, pokud chceš novou.',
  'terkep.sug': 'Klepni do mapy a přidej body. Body se dají táhnout; klepnutím se smažou.',
  'terkep.keszVonal': 'Hotovo — linie vede po skutečných pěších cestách.',
  'terkep.jelolesTorol': 'Smazat značku',
  'terkep.tobbVan': 'je toho tu víc — přibliž si to',
  'terkep.keresem': 'hledám…',
  'terkep.nagyits': 'přibliž si to',
  'terkep.hiba': 'nepodařilo se',
  'terkep.nincsAdat': 'bez údajů',

  'reteg.viz': 'Pitná voda, pramen',
  'reteg.menedek': 'Přístřešek',
  'reteg.kozlekedes': 'Zastávka, nádraží',
  'reteg.parkolo': 'Parkoviště',
  'reteg.kilato': 'Rozhledna',
  'reteg.vendeglatas': 'Jídlo a pití',
  'reteg.latvany': 'Pamětihodnost',

  'nincs.cim': 'Taková stránka neexistuje',
  'nincs.magyarazat': 'Buď ses překlepl v adrese, nebo vede na stránku, která už neexistuje.',
  'nincs.lead': 'Odsud můžeš pokračovat:',
  'nincs.kezdolap': 'Domů',
  'nincs.tervezo': 'Plánovač tras',
  'nincs.tervezoLeiras': 'nakresli túru do mapy',
  'nincs.peldak': 'Hotové trasy',
  'nincs.peldakLeiras': 'příklady, které můžeš otevřít',

  'meta.fooldalCim': 'Túrabakancs — turistické trasy, značky, názory',
  'meta.fooldalLeiras': 'Mapa pro plánování tras, vysvětlení maďarských turistických značek a názory bez jmen.',
  'meta.tervezoCim': 'Plánovač — Túrabakancs',
  'meta.tervezoLeiras': 'Nakresli trasu do mapy, přidej značky, sdílej ji odkazem.',
  'meta.peldakCim': 'Vzorové trasy — Túrabakancs',
  'meta.peldakLeiras': 'Hotové turistické trasy v mapě, které můžeš otevřít a dál kreslit.',
  'meta.impresszumCim': 'O stránce a ochrana údajů — Túrabakancs',
  'meta.impresszumLeiras': 'K čemu stránka je a k čemu ne. Žádný účet, žádné cookies, žádné měření; co nakreslíš, zůstává v tvém prohlížeči.',
  'meta.nincsCim': 'Taková stránka neexistuje — Túrabakancs',
  'meta.nincsLeiras': 'Tato adresa neexistuje.',
};
