/* Čeština. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — domů',
  'fejlec.menuNyit': 'Otevřít nabídku',
  'fejlec.menuZar': 'Zavřít nabídku',
  'fejlec.foMenu': 'Hlavní nabídka',
  'fejlec.sotetMod': 'Přepnout tmavý režim',
  'fejlec.fok': 'Teď {fok} stupňů — {ido}',
  'fejlec.jelenleg': 'Právě teď',

  'menu.fooldal': 'Domů',
  'menu.fooldalLeiras': 'Turistické značky, příklady a názory',
  'menu.tervezo': 'Plánovač',
  'menu.tervezoLeiras': 'Zadej dvě místa nebo kresli do mapy',
  'menu.peldak': 'Příklady',
  'menu.peldakLeiras': 'Hotové trasy, ze kterých můžeš vyjít',

  'lab.terkep': 'Mapu tvoří přispěvatelé {osm}, kteří dodávají i dlaždice.',
  'lab.becsles': 'Vzdálenost a čas chůze jsou odhady — v terénu platí značené turistické cesty.',
  'lab.impresszum': 'O stránce a ochrana údajů',

  'fooldal.cim': 'Túrabakancs — mapa pro plánování turistických tras',
  'fooldal.lead': 'Mapa, do které se dá kreslit. Hotové túry na začátek. Čas chůze, který počítá i se stoupáním.',
  'fooldal.tervezek': 'Naplánuju túru',
  'fooldal.peldak': 'Podívám se na příklady',
  'fooldal.ma': 'Dnes',
  'fooldal.napkelte': 'východ slunce',
  'fooldal.napnyugta': 'západ slunce',
  'fooldal.vilagosMeg': 'ještě světla',
  'fooldal.lement': 'zapadlo',
  'fooldal.vanMeg': 'ještě je světlo',
  'fooldal.marLement': 'slunce už zapadlo',
  'fooldal.napAlap': 'Pro Budapešť. Plánovač počítá se začátkem tvé vlastní trasy.',
  'fooldal.jelzesCim': 'Co znamená barva na stromě?',
  'fooldal.jelzesLead': 'Maďarská turistická značka říká dvě věci najednou. Barva to, jak velká trasa je, tvar to, k čemu slouží.',
  'fooldal.jelzesSzin': 'barva',
  'fooldal.jelzesAlak': 'tvar',
  'fooldal.jelzesApro': 'Nepsali jsme to zpaměti: ověřili jsme si na značených cestách v OpenStreetMap, co kam vede. Trasy s trojúhelníkem končí na vrcholu nebo u rozhledny, trasy s kruhem se vracejí tam, odkud vyšly.',
  'fooldal.keszVonal': 'Začni hotovou trasou',
  'fooldal.keszVonalLead': 'Otevři ji, popotáhni body, udělej si ji vlastní.',
  'fooldal.szerintunk': 'podle nás',
  'fooldal.osszesPelda': 'Všechny příklady →',

  'peldak.kicsi': 'Příklady',
  'peldak.cim': 'Hotové trasy, ze kterých můžeš vyjít.',
  'peldak.bevezeto': 'Otevři kteroukoli, popotáhni body, přidej vlastní značky — a je tvoje.',
  'peldak.tajegyseg': 'Oblast',
  'peldak.mindegyik': 'Všechny',
  'peldak.hossz': 'Délka',
  'peldak.nehezseg': 'Náročnost',
  'peldak.torold': 'smazat vše',
  'peldak.szurokTorol': 'zrušit filtry',
  'peldak.utvonal': 'tras',
  'peldak.megnezem': 'Zobrazit',
  'peldak.gyalogut': 'Trasy vedou po skutečných pěších cestách',
  'peldak.gyalogutUtan': ', ne po přímce mezi dvěma body — proto vzdálenost a stoupání sedí. V terénu stejně platí značené cesty a oficiální mapy.',
  'peldak.darab': '{db} tras',

  'utvonal.nincs': 'Tato trasa neexistuje.',
  'utvonal.tobbi': 'Tady jsou ostatní příklady.',
  'tempo.gyalog': 'Pěšky',
  'tempo.futas': 'Běh',
  'tempo.bringa': 'Kolo',
  'utvonal.elgepelt': 'Možná ses překlepl v adrese.',
  'utvonal.kozelitoUtan': ' V terénu platí značené turistické cesty a oficiální mapy.',
  'utvonal.hossz': 'Délka',
  'utvonal.sik': 'Počítáno pro rovinu; do kopce víc.',
  'utvonal.jelolesek': 'Značky',
  'utvonal.kozelito': 'Přibližný průběh, ne zaměřená turistická cesta.',
  'utvonal.megnyitas': 'Otevřít v plánovači',
  'utvonal.gpx': 'Stáhnout GPX',

  'tervezo.honnanHova': 'Odkud kam?',
  'tervezo.adatok': 'Údaje o trase',
  'tervezo.adatokCimke': 'Údaje o trase — {km}, {ido}',
  'tervezo.eszkozok': 'Uložení, hotové trasy, GPX',
  'tervezo.vissza': 'O krok zpět',
  'tervezo.retegek': 'Co má mapa ukazovat',
  'tervezo.ujraKeres': 'Hledat v této oblasti',

  'hh.honnan': 'Odkud',
  'hh.hova': 'Kam — když necháš prázdné, jen tam skočíme',
  'hh.honnanHely': 'Název místa nebo souřadnice',
  'hh.hovaHely': 'Například: Sněžka',
  'hh.innen': 'Vyrazím odsud',
  'hh.odaugras': 'Skočit tam',
  'hh.szamolom': 'Počítám…',
  'hh.utvonalat': 'Chci trasu',
  'hh.keres': 'Hledám…',
  'hh.nincsHelyzet': 'Nepodařilo se zjistit tvou polohu. Zadej výchozí bod ručně.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'délka',
  'adat.emelkedo': 'stoupání',
  'adat.lejto': 'klesání',
  'adat.nehezseg': 'náročnost',
  'adat.tempo': 'Tempo',
  'adat.tengerszint': '{also}–{felso} m n. m.',
  'adat.nev': 'Například: nedělní okruh',

  'terkep.igazit': 'Přikládám linii na skutečné pěší cesty…',
  'terkep.masodik': 'Označ druhý bod — linie si sama sedne na cestu.',
  'terkep.keszUt': 'Trasa hotová. Klepni do mapy, pokud chceš novou.',
  'terkep.sug': 'Klepni do mapy a přidej body. Body se dají táhnout; klepnutím se smažou.',
  'terkep.keszVonal': 'Hotovo — linie vede po skutečných pěších cestách.',
  'jeloles.ugras': 'Skočit sem: {nev}',
  'jeloles.neve': 'Název: {tipus}',
  'terkep.jelolesTorol': 'Smazat značku',
  'terkep.tobbVan': 'je toho tu víc — přibliž si to',
  'terkep.keresem': 'hledám…',
  'terkep.nagyits': 'přibliž si to',
  'terkep.hiba': 'nepodařilo se',
  'terkep.nincsAdat': 'bez údajů',

  'reteg.viz': 'Pitná voda, pramen',
  'reteg.menedek': 'Přístřešek',
  'reteg.kozlekedes': 'Zastávka, nádraží',
  'reteg.parkolo': 'Parkoviště',
  'reteg.kilato': 'Rozhledna',
  'reteg.vendeglatas': 'Jídlo a pití',
  'reteg.latvany': 'Pamětihodnost',

  'nincs.cim': 'Taková stránka neexistuje',
  'nincs.magyarazat': 'Buď ses překlepl v adrese, nebo vede na stránku, která už neexistuje.',
  'nincs.lead': 'Odsud můžeš pokračovat:',
  'nincs.kezdolap': 'Domů',
  'nincs.tervezo': 'Plánovač tras',
  'nincs.tervezoLeiras': 'nakresli túru do mapy',
  'nincs.peldak': 'Hotové trasy',
  'nincs.peldakLeiras': 'příklady, které můžeš otevřít',

  'meta.fooldalCim': 'Túrabakancs — turistické trasy, značky, názory',
  'meta.fooldalLeiras': 'Mapa pro plánování tras, vysvětlení maďarských turistických značek a názory bez jmen.',
  'meta.tervezoCim': 'Plánovač — Túrabakancs',
  'meta.tervezoLeiras': 'Nakresli trasu do mapy, přidej značky, sdílej ji odkazem.',
  'meta.peldakCim': 'Vzorové trasy — Túrabakancs',
  'meta.peldakLeiras': 'Hotové turistické trasy v mapě, které můžeš otevřít a dál kreslit.',
  'meta.impresszumCim': 'O stránce a ochrana údajů — Túrabakancs',
  'meta.impresszumLeiras': 'K čemu stránka je a k čemu ne. Žádný účet, žádné cookies, žádné měření; co nakreslíš, zůstává v tvém prohlížeči.',
  'meta.nincsCim': 'Taková stránka neexistuje — Túrabakancs',
  'meta.nincsLeiras': 'Tato adresa neexistuje.',

  /* ---- Nehézség, szűrők, ajánló ---- */
  'nehez.konnyu': 'Lehká',
  'nehez.kozepes': 'Střední',
  'nehez.eros': 'Náročná',
  'nehez.nehez': 'Těžká',
  'nehez.konnyuLeiras': 'Krátká procházka, zvládne ji každý.',
  'nehez.kozepesLeiras': 'Půl dne, není třeba kondice.',
  'nehez.erosLeiras': 'Celodenní túra, připrav se.',
  'nehez.nehezLeiras': 'Dlouhý den. Jen se zkušenostmi a vybavením.',
  'szuro.rovid': 'Krátká',
  'szuro.kozepes': 'Střední',
  'szuro.hosszu': 'Dlouhá',
  'szuro.rovidLeiras': 'pod 3 km',
  'szuro.kozepesLeiras': '3–8 km',
  'szuro.hosszuLeiras': 'nad 8 km',
  'tanacs.osszkepCimke': '{nehez} — {ido} chůze',
  'tanacs.osszkepMagassag': '{km} km, {fel} m stoupání. {leiras} Čas chůze je bez přestávek; připočti aspoň půl hodiny.',
  'tanacs.osszkepNincs': '{km} km. {leiras} Stoupání se ještě načítá; zatím čas chůze počítá jen se vzdáleností.',
  'tanacs.sotetCimke': 'Slunce už zapadlo',
  'tanacs.sotetSzoveg': 'Západ slunce byl dnes v {ido}. Pokud vyrážíš teď, nechoď bez čelovky.',
  'tanacs.sotetedesCimke': 'Nestihneš to před setměním',
  'tanacs.sotetedesSzoveg': 'Západ slunce v {nyugta}, zbývá {maradek}. Trasa trvá {ut}, bez přestávek. Vezmi si čelovku, nebo vyraz dřív.',
  'tanacs.vilagosCimke': '{maradek} do západu slunce',
  'tanacs.vilagosSzoveg': 'Dnes se stmívá v {ido}. Pokud vyrážíš teď, času máš dost.',
  'tanacs.visszautCimke': 'Cíl není tam, kde start',
  'tanacs.visszautSzoveg': 'Dělí je {tav} km. Pokud jedeš autem, promysli, jak se k němu vrátíš — nebo naplánuj okruh.',
  'tanacs.vizCimke': 'Není označené místo s vodou',
  'tanacs.vizSzoveg': 'Na {km} km je to málo. Zapni vrstvu s pitnou vodou: ukážu, co je v okolí.',
  'tanacs.megkozelitesCimke': 'Není označeno, jak se dostaneš na start',
  'tanacs.megkozelitesSzoveg': 'Před vyražením to bude první otázka. Vrstvou se zastávkami zjistíš, co je v okolí.',
  'tanacs.durvaCimke': 'Linie je velmi rovná',
  'tanacs.durvaSzoveg': 'Průměrně {atlag} km na úsek. Skutečná pěšina se klikatí, takže reálná vzdálenost je delší — naklikej víc bodů pro přesnější obraz.',
  'tanacs.emelkedoCimke': '{fel} metrů stoupání',
  'tanacs.emelkedoSzoveg': 'Nejnižší bod je {min} m, nejvyšší {max} m. Samotné toto stoupání prodlouží čas chůze o {plusz}.',
  'tanacs.veszelyCimke': 'Označil jsi těžký úsek',
  'tanacs.veszelySzoveg': 'Po dešti a v mrazu jsou strmé, skalnaté úseky mnohem pomalejší a rizikovější. Před vyražením si zkontroluj počasí.',

  /* ---- Időjárás és jelöléstípusok ---- */
  'ido.derult': 'Jasno',
  'ido.jobbaraDerult': 'Převážně jasno',
  'ido.szakadozott': 'Polojasno',
  'ido.borult': 'Zataženo',
  'ido.kod': 'Mlha',
  'ido.zuzmarasKod': 'Mrznoucí mlha',
  'ido.gyengeSzitalas': 'Slabé mrholení',
  'ido.szitalas': 'Mrholení',
  'ido.erosSzitalas': 'Silné mrholení',
  'ido.gyengeEso': 'Slabý déšť',
  'ido.eso': 'Déšť',
  'ido.erosEso': 'Silný déšť',
  'ido.gyengeHavazas': 'Slabé sněžení',
  'ido.havazas': 'Sněžení',
  'ido.erosHavazas': 'Silné sněžení',
  'ido.hoszemcsek': 'Sněhová zrna',
  'ido.zapor': 'Přeháňky',
  'ido.hevesZapor': 'Silné přeháňky',
  'ido.hozapor': 'Sněhové přeháňky',
  'ido.erosHozapor': 'Silné sněhové přeháňky',
  'ido.zivatar': 'Bouřka',
  'ido.jegesoZivatar': 'Bouřka s krupobitím',
  'ido.hevesJegeso': 'Silná bouřka s krupobitím',
  'ido.ismeretlen': 'Neznámé',
  'idoFigy.zivatar': 'Očekávají se bouřky. Na hřebeni ani na rozhledně tehdy nemáš co dělat.',
  'idoFigy.sokCsapadek': '{mm} mm srážek: skalnaté úseky a žebříky budou kluzké.',
  'idoFigy.eso': 'Očekává se déšť — na blátivých svazích půjdeš pomaleji.',
  'idoFigy.meleg': '{fok} stupňů: na úsecích bez stínu si vezmi dvojnásobek vody.',
  'idoFigy.fagy': 'Nad ránem {fok} stupňů: trasa může být zledovatělá.',
  'idoFigy.szel': 'Vítr {szel} km/h: na hřebeni nepříjemný, na rozhledně studený.',
  'tipus.kilato': 'Rozhledna',
  'tipus.forras': 'Pramen, pitná voda',
  'tipus.pihen': 'Odpočívadlo, lavička',
  'tipus.parkolo': 'Parkoviště',
  'tipus.vendeglatas': 'Jídlo a pití',
  'tipus.latnivalo': 'Pamětihodnost',
  'tipus.veszely': 'Nebezpečí, těžký úsek',
  'tipus.kozlekedes': 'Zastávka, nádraží',

  /* ---- Tanácsok, túralista, napnevek ---- */
  'tanacs.lekerem': 'Načítám…',
  'tanacs.milyenIdo': 'Jaké bude počasí?',
  'nap.ma': 'dnes',
  'nap.holnap': 'zítra',
  'turak.lead': 'Ukážu ti, jaké {jelzett} vedou tam, kde je právě mapa. Kteroukoli můžeš načíst a kreslit dál.',
  'turak.jelzett': 'značené cesty',
  'turak.keresem': 'Hledám…',
  'turak.keres': 'Hledat cesty v této oblasti',
  'turak.tolt': 'načítám…',
  'turak.festett': 'V terénu platí namalovaná značka.',

  /* ---- Impresszum és adatkezelés ---- */
  'imp.cim': 'O stránce a ochrana údajů',
  'imp.felelossegCim': 'Odpovědnost — přečti si to, než vyrazíš',
  'imp.felelossegLead': 'Stránka ukazuje trasy, vzdálenosti, stoupání, časy chůze a západ slunce. Jsou to {eros}, ne záruky:',
  'imp.felelossegEros': 'výpočty a odhady',
  'imp.felelosseg1': 'Linie sledují pěšiny z mapových dat. Jestli je daná pěšina právě schůdná, mapa neví — může na ni spadnout strom, může ji vymýt déšť, může být uzavřená.',
  'imp.felelosseg2': 'Čas chůze počítá s rovinou a průměrným tempem. Zátěž, sníh, bláto, setmění a tvoje kondice to všechno přebijí.',
  'imp.felelosseg3': 'Stoupání pochází z výškového modelu, který se může o pár metrů lišit od skutečnosti.',
  'imp.felelossegZaro': '{eros} K orientaci slouží značené turistické cesty a oficiální mapy; před vyražením si zkontroluj počasí a řekni někomu, kam jdeš. Tahle stránka pomáhá plánovat — nenahrazuje zdravý rozum.',
  'imp.felelossegZaroEros': 'V terénu platí tvé vlastní rozhodnutí a odpovědnost.',
  'imp.tartalomCim': 'Obsah',
  'imp.tartalom': 'Hvězdičková hodnocení jsou náš názor, ne průměr cizích bodů. Mapová data pocházejí z OpenStreetMap, který udržují dobrovolníci. Fotografie pamětihodností jsou pod volnými licencemi, se jmény autorů — celý seznam níže, pod {link}.',
  'imp.adatCim': 'Ochrana údajů',
  'imp.adat1': 'Stránka nežádá účet, nesbírá osobní údaje a nepoužívá cookies. Co nakreslíš, vzniká v tvém prohlížeči a tam i zůstává: uložené plány jdou do úložiště tvého zařízení a sdílený odkaz vkládá trasu přímo do adresy, ne do databáze.',
  'imp.adat2': 'To, co přece jen jde na internet, nejde k nám. Mapové dlaždice a odpovědi vyhledávání míst dávají veřejné služby OpenStreetMap, výšková data Open-Meteo a přikládání tras na pěšiny pěší router FOSSGIS. Když ukážeš na pamětihodnost, její obrázek dodá Wikimedia Commons — teprve tehdy, když na ni ukážeš. Tehdy — jako u každého obrázku na každé stránce — je jim vidět tvoje IP adresa a u přikládání a výšky i souřadnice tvé linie. Tomu se nedá vyhnout, pokud chceme ukázat mapu; aspoň o tom ale víš.',
  'imp.kepekCim': 'Obrázky',
  'imp.kepek': 'Fotografie pamětihodností pocházejí z Wikimedia Commons a jsou pod volnými licencemi — volné ale neznamená bez majitele: každá má autora, kterého je třeba uvést. Obrázek se načte teprve tehdy, když ukážeš na pamětihodnost, a jméno autora je vždy u něj. Seznam níže uvádí patnáct maďarských míst, jejichž obrázky hostujeme sami.',

  /* ---- Alfajták és ivhatóság ---- */
  'fajta.ivoviz': 'Pitná voda',
  'fajta.forras': 'Pramen',
  'fajta.esobeallo': 'Přístřešek',
  'fajta.menedekhaz': 'Útulna',
  'fajta.turistahaz': 'Chata',
  'fajta.vasutallomas': 'Železniční stanice',
  'fajta.megallohely': 'Zastávka',
  'fajta.buszmegallo': 'Autobusová zastávka',
  'fajta.parkolo': 'Parkoviště',
  'fajta.kilatopont': 'Vyhlídka',
  'fajta.kilatotorony': 'Rozhledna',
  'fajta.etterem': 'Restaurace',
  'fajta.kavezo': 'Kavárna',
  'fajta.kocsma': 'Hospoda',
  'fajta.bufe': 'Bufet',
  'fajta.var': 'Hrad, zámek',
  'fajta.rom': 'Zřícenina',
  'fajta.regeszeti': 'Archeologická lokalita',
  'fajta.emlekmu': 'Památník',
  'fajta.muzeum': 'Muzeum',
  'fajta.vizeses': 'Vodopád',
  'fajta.barlang': 'Vchod do jeskyně',
  'fajta.sziklakapu': 'Skalní brána',
  'fajta.vilagitotorony': 'Maják',
  'fajta.latnivalo': 'Zajímavost',
  'viz.ihato': 'pitná',
  'viz.nemIhato': 'NENÍ pitná',
  'viz.nincsAdat': 'bez údaje, zda je pitná',

  /* ---- Hibaüzenetek és apróságok ---- */
  'hiba.utvonalkereso': 'Vyhledávač tras je teď nedostupný.',
  'hiba.helykereso': 'Vyhledávání míst je teď nedostupné.',
  'hiba.helykeresoNema': 'Vyhledávání míst neodpovídá.',
  'hiba.haromBetu': 'Napiš aspoň tři písmena.',
  'hiba.nincsHely': 'Pro tohle jsem nenašel místo: „{mit}“',
  'hiba.elorejelzes': 'Předpověď je teď nedostupná.',
  'hiba.homerseklet': 'Teplota je teď nedostupná.',
  'hiba.magassag': 'Výšková data jsou teď nedostupná.',
  'hiba.osmNema': 'Vyhledávání OpenStreetMap neodpovídá.',
  'hiba.tulterhelt': 'Vyhledávání je přetížené. Zkus to za pár sekund.',
  'hiba.terheles': 'Vyhledávání nestíhá. Zkus to za pár sekund.',
  'hiba.keresesNemSikerult': 'Vyhledávání selhalo.',
  'hiba.ismeretlenReteg': 'Neznámá vrstva.',
  'hiba.nincsHelyzet': 'Tenhle prohlížeč neumí zjistit tvoji polohu.',
  'gpx.nemTud': 'Tenhle prohlížeč neumí číst GPX.',
  'gpx.serult': 'Tenhle soubor není čitelné GPX — poškozený nebo jiný formát.',
  'gpx.ures': 'V tomhle souboru není ani trasa, ani značky.',
  'gpx.nagy': 'Tenhle soubor má přes 5 MB. Takhle velkou trasu neumím rozumně zobrazit.',
  'gpx.nemSikerult': 'Tenhle soubor se nepodařilo načíst.',
  'terv.ujKezdtel': 'Začal jsi novou trasu — šipkou získáš zpět předchozí.',
  'terv.betoltve': 'Načteno. Popotáhni body nebo přidej značky.',
  'terv.vagolapon': 'Odkaz je ve schránce — trasa je přímo v adrese.',
  'terv.cimsorban': 'Sdílený odkaz je v adresním řádku prohlížeče.',
  'terv.elmentve': 'Uloženo. Na jiném zařízení se k tomu dostaneš přes sdílený odkaz.',
  'terv.nevtelen': 'Nepojmenovaný plán',
  'terv.mentesFrissit': 'Aktualizovat uložení',
  'terv.mentesBongeszobe': 'Uložit do prohlížeče',
  'terkep.cel': 'Cíl',
  'terkep.rajt': 'Start',
  'terkep.hanyadikPont': '{n}. bod',
  'hh.koordinata': 'zadané souřadnice',
  'nap.ketNapMulva': 'Za dva dny',
  'turak.jelzettUt': 'značená cesta',
  'kep.lasdForras': 'viz zdroj',
  'ut.ketPont': 'Jsou potřeba aspoň dva body.',
  'ut.nemErheto': 'Vyhledávač tras je teď nedostupný. Zkus to později.',
  'ut.tulSok': 'Příliš mnoho dotazů v krátkém čase. Chvíli počkej.',
  'ut.hibat': 'Vyhledávač tras vrátil chybu.',
  'ut.nincsGyalogut': 'Mezi těmito body jsem nenašel pěší cestu. Možná je mezi nimi voda nebo plot.',
  'ut.nemSikerult': 'Nepodařilo se najít trasu.',
  'ut.tulSokPont': 'Najednou umím přiložit na cesty nejvýš {max} bodů. Smaž jich pár nebo to rozděl na úseky.',
  'ut.nincsGyalogut2': 'Mezi těmito body jsem nenašel pěší cestu. Možná vede přes vodu nebo bezcestný terén.',
  'terv.egyenesMarad': '{ok} Linie zatím zůstává rovná, proto jsou vzdálenost a stoupání menší než ve skutečnosti.',
  'adat.tengerszintUtan': 'n. m.',

  /* ---- Főoldal: mit tud, kiemelt példa ---- */
  'fooldal.peldaKalap': 'Takhle vypadá, co dostaneš',
  'fooldal.peldaNyisd': 'Otevřít v plánovači',
  'fooldal.mitTud': 'Co tahle mapa umí',
  'fooldal.mitTudLead': 'Čtyři důvody plánovat tady, a ne na obecné mapě.',
  'fooldal.tud1Cim': 'Linie vede po skutečných pěšinách',
  'fooldal.tud1': 'Ne přímka mezi dvěma body. Označ dvě místa a trasa si sama sedne na skutečné pěšiny — proto vzdálenost a stoupání sedí.',
  'fooldal.tud2Cim': 'Čas chůze počítá se stoupáním',
  'fooldal.tud2': 'Deset kilometrů po rovině a deset v horách není stejný čas. Odhad připočítá za každých sto metrů stoupání a ukáže i výškový profil.',
  'fooldal.tud3Cim': 'Ukáže, co je v okolí',
  'fooldal.tud3': 'Sedm vrstev z OpenStreetMap: pitná voda, přístřešky, zastávky, parkoviště, rozhledny, jídlo a pití, pamětihodnosti. V kterékoli zemi světa.',
  'fooldal.tud4Cim': 'Zůstává to tvoje',
  'fooldal.tud4': 'Co nakreslíš, vzniká v tvém prohlížeči. Sdílený odkaz nese samotnou trasu, ne identifikátor z databáze — a stáhneš si ji i v GPX, do jakýchkoli hodinek či aplikace.',
  'adat.menetido': 'čas chůze',
};
