/* English. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — home',
  'fejlec.menuNyit': 'Open menu',
  'fejlec.menuZar': 'Close menu',
  'fejlec.foMenu': 'Main menu',
  'fejlec.sotetMod': 'Toggle dark mode',
  'fejlec.fok': '{fok} degrees now — {ido}',
  'fejlec.jelenleg': 'Currently',

  'menu.fooldal': 'Home',
  'menu.fooldalLeiras': 'Trail marks, examples and opinions',
  'menu.tervezo': 'Planner',
  'menu.tervezoLeiras': 'Type in two places, or draw on the map',
  'menu.peldak': 'Examples',
  'menu.peldakLeiras': 'Ready-made routes to start from',

  'lab.terkep': 'The map is made by {osm} contributors, who also provide the tiles.',
  'lab.becsles': 'Distance and walking time are estimates — on the ground, the marked trails are what count.',
  'lab.impresszum': 'About and privacy',

  'fooldal.cim': 'Túrabakancs — hiking route planner map',
  'fooldal.lead': 'A map you can draw on. Ready-made hikes to start from. Walking time that accounts for the climb.',
  'fooldal.tervezek': 'Plan a hike',
  'fooldal.peldak': 'See examples',
  'fooldal.ma': 'Today',
  'fooldal.napkelte': 'sunrise',
  'fooldal.napnyugta': 'sunset',
  'fooldal.vilagosMeg': 'of daylight left',
  'fooldal.lement': 'sunset passed',
  'fooldal.vanMeg': 'still light',
  'fooldal.marLement': 'the sun has set',
  'fooldal.napAlap': 'For Budapest. The planner calculates for the start of your own route.',
  'fooldal.jelzesCim': 'What does the paint on the tree mean?',
  'fooldal.jelzesLead': 'A Hungarian trail mark tells you two things at once. The colour says how big the route is, the shape says what it is for.',
  'fooldal.jelzesSzin': 'colour',
  'fooldal.jelzesAlak': 'shape',
  'fooldal.jelzesApro': 'We did not write this from memory: we checked against the marked paths in OpenStreetMap to see what leads where. Routes marked with a triangle end at a peak or a lookout; those marked with a circle return to where they started.',
  'fooldal.keszVonal': 'Start from a ready-made route',
  'fooldal.keszVonalLead': 'Open it, drag its points, make it your own.',
  'fooldal.szerintunk': 'we think',
  'fooldal.osszesPelda': 'All examples →',

  'peldak.kicsi': 'Examples',
  'peldak.cim': 'Ready-made routes to start from.',
  'peldak.bevezeto': 'Open any of them, drag the points, add your own markers — and it is yours.',
  'peldak.tajegyseg': 'Region',
  'peldak.mindegyik': 'All',
  'peldak.hossz': 'Length',
  'peldak.nehezseg': 'Difficulty',
  'peldak.torold': 'clear all',
  'peldak.szurokTorol': 'clear filters',
  'peldak.utvonal': 'routes',
  'peldak.megnezem': 'View',
  'peldak.gyalogut': 'The routes follow actual footpaths',
  'peldak.gyalogutUtan': ', not a straight line between two points — which is why the distance and the ascent are true. On the ground, the marked trails and the official maps still take precedence.',
  'peldak.darab': '{db} routes',

  'utvonal.nincs': 'This route does not exist.',
  'utvonal.tobbi': 'Here are the other examples.',
  'utvonal.hossz': 'Length',
  'utvonal.sik': 'Calculated for flat ground; more on a climb.',
  'utvonal.jelolesek': 'Markers',
  'utvonal.kozelito': 'Approximate line, not a surveyed trail.',
  'utvonal.megnyitas': 'Open in the planner',
  'utvonal.gpx': 'Download GPX',

  'tervezo.honnanHova': 'From where to where?',
  'tervezo.adatok': 'Route details',
  'tervezo.adatokCimke': 'Route details — {km}, {ido}',
  'tervezo.eszkozok': 'Save, ready-made routes, GPX',
  'tervezo.vissza': 'One step back',
  'tervezo.retegek': 'What the map should show',
  'tervezo.ujraKeres': 'Search this area',

  'hh.honnan': 'From',
  'hh.hova': 'To — leave it empty and we just jump there',
  'hh.honnanHely': 'Place name or coordinates',
  'hh.hovaHely': 'For example: Ben Nevis',
  'hh.innen': 'Start from here',
  'hh.odaugras': 'Jump there',
  'hh.szamolom': 'Calculating…',
  'hh.utvonalat': 'Get a route',
  'hh.keres': 'Searching…',
  'hh.nincsHelyzet': 'I could not get your location. Type the starting point by hand.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'length',
  'adat.emelkedo': 'ascent',
  'adat.lejto': 'descent',
  'adat.nehezseg': 'difficulty',
  'adat.tempo': 'Pace',
  'adat.tengerszint': '{also}–{felso} m above sea level',
  'adat.nev': 'For example: Sunday loop',

  'terkep.igazit': 'Snapping the line to real footpaths…',
  'terkep.masodik': 'Mark the second point — the line snaps to the path on its own.',
  'terkep.keszUt': 'Route ready. Tap the map to start a new one.',
  'terkep.sug': 'Tap the map to add points. Points can be dragged; tap one to delete it.',
  'terkep.keszVonal': 'Done — the line follows actual footpaths.',
  'terkep.jelolesTorol': 'Delete marker',
  'terkep.tobbVan': 'there are more here — zoom in',
  'terkep.keresem': 'searching…',
  'terkep.nagyits': 'zoom in',
  'terkep.hiba': 'failed',
  'terkep.nincsAdat': 'no data',

  'reteg.viz': 'Drinking water, spring',
  'reteg.menedek': 'Shelter',
  'reteg.kozlekedes': 'Stop, station',
  'reteg.parkolo': 'Parking',
  'reteg.kilato': 'Lookout',
  'reteg.vendeglatas': 'Food and drink',
  'reteg.latvany': 'Sight',

  'nincs.cim': 'No such page',
  'nincs.magyarazat': 'Either you mistyped the address, or it points to a page that no longer exists.',
  'nincs.lead': 'You can carry on from here:',
  'nincs.kezdolap': 'Home',
  'nincs.tervezo': 'Route planner',
  'nincs.tervezoLeiras': 'draw a hike on the map',
  'nincs.peldak': 'Ready-made routes',
  'nincs.peldakLeiras': 'examples you can open',

  'meta.fooldalCim': 'Túrabakancs — hiking routes, trail marks, opinions',
  'meta.fooldalLeiras': 'A route planner map, an explanation of Hungarian trail marks, and opinions without names.',
  'meta.tervezoCim': 'Planner — Túrabakancs',
  'meta.tervezoLeiras': 'Draw a route on the map, add markers, share it with a link.',
  'meta.peldakCim': 'Example routes — Túrabakancs',
  'meta.peldakLeiras': 'Ready-made hiking routes on the map that you can open and redraw.',
  'meta.impresszumCim': 'About and privacy — Túrabakancs',
  'meta.impresszumLeiras': 'What the site is for and what it is not. No account, no cookies, no tracking; what you draw stays in your browser.',
  'meta.nincsCim': 'No such page — Túrabakancs',
  'meta.nincsLeiras': 'This address does not exist.',
};
