/* English. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — home',
  'fejlec.menuNyit': 'Open menu',
  'fejlec.menuZar': 'Close menu',
  'fejlec.foMenu': 'Main menu',
  'fejlec.sotetMod': 'Toggle dark mode',
  'fejlec.fok': '{fok} degrees now — {ido}',
  'fejlec.jelenleg': 'Currently',

  'menu.fooldal': 'Home',
  'menu.fooldalLeiras': 'Trail marks, examples and opinions',
  'menu.tervezo': 'Planner',
  'menu.tervezoLeiras': 'Type in two places, or draw on the map',
  'menu.peldak': 'Examples',
  'menu.peldakLeiras': 'Ready-made routes to start from',

  'lab.terkep': 'The map is made by {osm} contributors, who also provide the tiles.',
  'lab.becsles': 'Distance and walking time are estimates — on the ground, the marked trails are what count.',
  'lab.impresszum': 'About and privacy',

  'fooldal.cim': 'Túrabakancs — hiking route planner map',
  'fooldal.lead': 'A map you can draw on. Ready-made hikes to start from. Walking time that accounts for the climb.',
  'fooldal.tervezek': 'Plan a hike',
  'fooldal.peldak': 'See examples',
  'fooldal.ma': 'Today',
  'fooldal.napkelte': 'sunrise',
  'fooldal.napnyugta': 'sunset',
  'fooldal.vilagosMeg': 'of daylight left',
  'fooldal.lement': 'sunset passed',
  'fooldal.vanMeg': 'still light',
  'fooldal.marLement': 'the sun has set',
  'fooldal.napAlap': 'For Budapest. The planner calculates for the start of your own route.',
  'fooldal.jelzesCim': 'What does the paint on the tree mean?',
  'fooldal.jelzesLead': 'A Hungarian trail mark tells you two things at once. The colour says how big the route is, the shape says what it is for.',
  'fooldal.jelzesSzin': 'colour',
  'fooldal.jelzesAlak': 'shape',
  'fooldal.jelzesApro': 'We did not write this from memory: we checked against the marked paths in OpenStreetMap to see what leads where. Routes marked with a triangle end at a peak or a lookout; those marked with a circle return to where they started.',
  'fooldal.keszVonal': 'Start from a ready-made route',
  'fooldal.keszVonalLead': 'Open it, drag its points, make it your own.',
  'fooldal.szerintunk': 'we think',
  'fooldal.osszesPelda': 'All examples →',

  'peldak.kicsi': 'Examples',
  'peldak.cim': 'Ready-made routes to start from.',
  'peldak.bevezeto': 'Open any of them, drag the points, add your own markers — and it is yours.',
  'peldak.tajegyseg': 'Region',
  'peldak.mindegyik': 'All',
  'peldak.hossz': 'Length',
  'peldak.nehezseg': 'Difficulty',
  'peldak.torold': 'clear all',
  'peldak.szurokTorol': 'clear filters',
  'peldak.utvonal': 'routes',
  'peldak.megnezem': 'View',
  'peldak.gyalogut': 'The routes follow actual footpaths',
  'peldak.gyalogutUtan': ', not a straight line between two points — which is why the distance and the ascent are true. On the ground, the marked trails and the official maps still take precedence.',
  'peldak.darab': '{db} routes',

  'utvonal.nincs': 'This route does not exist.',
  'utvonal.tobbi': 'Here are the other examples.',
  'tempo.gyalog': 'Walking',
  'tempo.futas': 'Running',
  'tempo.bringa': 'Cycling',
  'utvonal.elgepelt': 'You may have mistyped the address.',
  'utvonal.kozelitoUtan': ' On the ground, the marked trails and the official maps take precedence.',
  'utvonal.hossz': 'Length',
  'utvonal.sik': 'Calculated for flat ground; more on a climb.',
  'utvonal.jelolesek': 'Markers',
  'utvonal.kozelito': 'Approximate line, not a surveyed trail.',
  'utvonal.megnyitas': 'Open in the planner',
  'utvonal.gpx': 'Download GPX',

  'tervezo.honnanHova': 'From where to where?',
  'tervezo.adatok': 'Route details',
  'tervezo.adatokCimke': 'Route details — {km}, {ido}',
  'tervezo.eszkozok': 'Save, ready-made routes, GPX',
  'tervezo.vissza': 'One step back',
  'tervezo.retegek': 'What the map should show',
  'tervezo.ujraKeres': 'Search this area',

  'hh.honnan': 'From',
  'hh.hova': 'To — leave it empty and we just jump there',
  'hh.honnanHely': 'Place name or coordinates',
  'hh.hovaHely': 'For example: Ben Nevis',
  'hh.innen': 'Start from here',
  'hh.odaugras': 'Jump there',
  'hh.szamolom': 'Calculating…',
  'hh.utvonalat': 'Get a route',
  'hh.keres': 'Searching…',
  'hh.nincsHelyzet': 'I could not get your location. Type the starting point by hand.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'length',
  'adat.emelkedo': 'ascent',
  'adat.lejto': 'descent',
  'adat.nehezseg': 'difficulty',
  'adat.tempo': 'Pace',
  'adat.tengerszint': '{also}–{felso} m above sea level',
  'adat.nev': 'For example: Sunday loop',

  'terkep.igazit': 'Snapping the line to real footpaths…',
  'terkep.masodik': 'Mark the second point — the line snaps to the path on its own.',
  'terkep.keszUt': 'Route ready. Tap the map to start a new one.',
  'terkep.sug': 'Tap the map to add points. Points can be dragged; tap one to delete it.',
  'terkep.keszVonal': 'Done — the line follows actual footpaths.',
  'jeloles.ugras': 'Jump to: {nev}',
  'jeloles.neve': 'Name of the {tipus}',
  'terkep.jelolesTorol': 'Delete marker',
  'terkep.tobbVan': 'there are more here — zoom in',
  'terkep.keresem': 'searching…',
  'terkep.nagyits': 'zoom in',
  'terkep.hiba': 'failed',
  'terkep.nincsAdat': 'no data',

  'reteg.viz': 'Drinking water, spring',
  'reteg.menedek': 'Shelter',
  'reteg.kozlekedes': 'Stop, station',
  'reteg.parkolo': 'Parking',
  'reteg.kilato': 'Lookout',
  'reteg.vendeglatas': 'Food and drink',
  'reteg.latvany': 'Sight',

  'nincs.cim': 'No such page',
  'nincs.magyarazat': 'Either you mistyped the address, or it points to a page that no longer exists.',
  'nincs.lead': 'You can carry on from here:',
  'nincs.kezdolap': 'Home',
  'nincs.tervezo': 'Route planner',
  'nincs.tervezoLeiras': 'draw a hike on the map',
  'nincs.peldak': 'Ready-made routes',
  'nincs.peldakLeiras': 'examples you can open',

  'meta.fooldalCim': 'Túrabakancs — hiking routes, trail marks, opinions',
  'meta.fooldalLeiras': 'A route planner map, an explanation of Hungarian trail marks, and opinions without names.',
  'meta.tervezoCim': 'Planner — Túrabakancs',
  'meta.tervezoLeiras': 'Draw a route on the map, add markers, share it with a link.',
  'meta.peldakCim': 'Example routes — Túrabakancs',
  'meta.peldakLeiras': 'Ready-made hiking routes on the map that you can open and redraw.',
  'meta.impresszumCim': 'About and privacy — Túrabakancs',
  'meta.impresszumLeiras': 'What the site is for and what it is not. No account, no cookies, no tracking; what you draw stays in your browser.',
  'meta.nincsCim': 'No such page — Túrabakancs',
  'meta.nincsLeiras': 'This address does not exist.',

  /* ---- Nehézség, szűrők, ajánló ---- */
  'nehez.konnyu': 'Easy',
  'nehez.kozepes': 'Moderate',
  'nehez.eros': 'Demanding',
  'nehez.nehez': 'Hard',
  'nehez.konnyuLeiras': 'A short walk, anyone can do it.',
  'nehez.kozepesLeiras': 'Half a day, no fitness required.',
  'nehez.erosLeiras': 'A full-day hike, come prepared.',
  'nehez.nehezLeiras': 'A long day. Only with experience and proper gear.',
  'szuro.rovid': 'Short',
  'szuro.kozepes': 'Medium',
  'szuro.hosszu': 'Long',
  'szuro.rovidLeiras': 'under 3 km',
  'szuro.kozepesLeiras': '3–8 km',
  'szuro.hosszuLeiras': 'over 8 km',
  'tanacs.osszkepCimke': '{nehez} — {ido} walking time',
  'tanacs.osszkepMagassag': '{km} km, {fel} m of ascent. {leiras} The walking time excludes breaks; add at least half an hour.',
  'tanacs.osszkepNincs': '{km} km. {leiras} I am still loading the ascent; until then the walking time is based on distance alone.',
  'tanacs.sotetCimke': 'The sun has already set',
  'tanacs.sotetSzoveg': 'Sunset was at {ido} today. If you set off now, do not go without a headlamp.',
  'tanacs.sotetedesCimke': 'You will not finish before dark',
  'tanacs.sotetedesSzoveg': 'Sunset at {nyugta}, which is {maradek} away. The route takes {ut}, without breaks. Take a headlamp, or start earlier.',
  'tanacs.vilagosCimke': '{maradek} until sunset',
  'tanacs.vilagosSzoveg': 'It gets dark at {ido} today. If you set off now, you have plenty of time.',
  'tanacs.visszautCimke': 'The finish is not where the start is',
  'tanacs.visszautSzoveg': 'They are {tav} km apart. If you drive, think through how you get back to the car — or plan a loop.',
  'tanacs.vizCimke': 'No water source marked',
  'tanacs.vizSzoveg': 'That is not enough for {km} km. Turn on the drinking-water layer: I will show what is nearby.',
  'tanacs.megkozelitesCimke': 'No way to the start is marked',
  'tanacs.megkozelitesSzoveg': 'This will be the first question before you set off. Use the stops layer to see what is nearby.',
  'tanacs.durvaCimke': 'The line is very straight',
  'tanacs.durvaSzoveg': '{atlag} km per segment on average. A real path winds, so the actual distance is longer — click in more points for a better picture.',
  'tanacs.emelkedoCimke': '{fel} metres of ascent',
  'tanacs.emelkedoSzoveg': 'The lowest point is {min} m, the highest {max} m. This ascent alone adds {plusz} to the walking time.',
  'tanacs.veszelyCimke': 'You marked a difficult section',
  'tanacs.veszelySzoveg': 'After rain and in frost, steep rocky sections are much slower and riskier. Check the weather before you set off.',

  /* ---- Időjárás és jelöléstípusok ---- */
  'ido.derult': 'Clear',
  'ido.jobbaraDerult': 'Mostly clear',
  'ido.szakadozott': 'Scattered cloud',
  'ido.borult': 'Overcast',
  'ido.kod': 'Fog',
  'ido.zuzmarasKod': 'Freezing fog',
  'ido.gyengeSzitalas': 'Light drizzle',
  'ido.szitalas': 'Drizzle',
  'ido.erosSzitalas': 'Heavy drizzle',
  'ido.gyengeEso': 'Light rain',
  'ido.eso': 'Rain',
  'ido.erosEso': 'Heavy rain',
  'ido.gyengeHavazas': 'Light snow',
  'ido.havazas': 'Snow',
  'ido.erosHavazas': 'Heavy snow',
  'ido.hoszemcsek': 'Snow grains',
  'ido.zapor': 'Showers',
  'ido.hevesZapor': 'Heavy showers',
  'ido.hozapor': 'Snow showers',
  'ido.erosHozapor': 'Heavy snow showers',
  'ido.zivatar': 'Thunderstorm',
  'ido.jegesoZivatar': 'Thunderstorm with hail',
  'ido.hevesJegeso': 'Severe thunderstorm with hail',
  'ido.ismeretlen': 'Unknown',
  'idoFigy.zivatar': 'Thunderstorms expected. A ridge or a lookout tower is no place to be.',
  'idoFigy.sokCsapadek': '{mm} mm of rain: rocky sections and ladders will be slippery.',
  'idoFigy.eso': 'Rain expected — muddy slopes will slow you down.',
  'idoFigy.meleg': '{fok} degrees: on unshaded sections, carry twice the water.',
  'idoFigy.fagy': '{fok} degrees at dawn: the trail may be icy.',
  'idoFigy.szel': '{szel} km/h wind: unpleasant on a ridge, cold in a lookout tower.',
  'tipus.kilato': 'Lookout',
  'tipus.forras': 'Spring, drinking water',
  'tipus.pihen': 'Rest spot, bench',
  'tipus.parkolo': 'Parking',
  'tipus.vendeglatas': 'Food and drink',
  'tipus.latnivalo': 'Sight',
  'tipus.veszely': 'Danger, hard section',
  'tipus.kozlekedes': 'Stop, station',

  /* ---- Tanácsok, túralista, napnevek ---- */
  'tanacs.lekerem': 'Fetching…',
  'tanacs.milyenIdo': 'What will the weather be?',
  'nap.ma': 'today',
  'nap.holnap': 'tomorrow',
  'turak.lead': 'I will show you which {jelzett} run where the map is right now. You can load any of them and keep drawing.',
  'turak.jelzett': 'marked trails',
  'turak.keresem': 'Searching…',
  'turak.keres': 'Search for trails in this area',
  'turak.tolt': 'loading…',
  'turak.festett': 'On the ground, the painted mark is what counts.',

  /* ---- Impresszum és adatkezelés ---- */
  'imp.cim': 'About and privacy',
  'imp.felelossegCim': 'Responsibility — read this before you set off',
  'imp.felelossegLead': 'The site shows routes, distances, ascents, walking times and sunset. These are {eros}, not guarantees:',
  'imp.felelossegEros': 'calculations and estimates',
  'imp.felelosseg1': 'The lines follow footpaths from the map data. Whether a given path is passable right now, the map cannot know — a tree may have fallen on it, rain may have washed it out, it may be closed.',
  'imp.felelosseg2': 'The walking time assumes flat ground and an average pace. Load, snow, mud, nightfall and your own fitness all override it.',
  'imp.felelosseg3': 'The ascent comes from a terrain model, which may differ from reality by a few metres.',
  'imp.felelossegZaro': '{eros} For navigation, use the marked trails and official maps; check the weather before you set off, and tell someone where you are going. This site helps you plan — it does not replace common sense.',
  'imp.felelossegZaroEros': 'On the ground, your own decision and responsibility are what count.',
  'imp.tartalomCim': 'The content',
  'imp.tartalom': 'The star ratings are our own opinion, not an average of other people’s scores. The map data comes from OpenStreetMap, maintained by volunteers. Photos of sights are under free licences, with their authors named — the full list is below, under {link}.',
  'imp.adatCim': 'Privacy',
  'imp.adat1': 'The site asks for no account, collects no personal data and uses no cookies. What you draw is created in your browser and stays there: your saved plans go into your own device’s storage, and the shareable link puts the route into the address itself, not into a database.',
  'imp.adat2': 'What does leave for the internet does not come to us. The map tiles and the place-search answers come from OpenStreetMap’s public services, the elevation data from Open-Meteo, and the snapping of routes to paths from the FOSSGIS walking router. If you point at a sight, its photo comes from Wikimedia Commons — only when you point at it. In those moments — as with every image on every website — your IP address is visible to them, and for snapping and elevation, the coordinates of your line as well. We cannot avoid this if we want to show a map; but at least you know.',
  'imp.kepekCim': 'The images',
  'imp.kepek': 'Photos of sights come from Wikimedia Commons and are under free licences — but free does not mean ownerless: each has an author who must be credited. An image is only downloaded when you point at a sight, and the author’s name is always shown with it. The list below covers the fifteen Hungarian places whose images we host ourselves.',

  /* ---- Alfajták és ivhatóság ---- */
  'fajta.ivoviz': 'Drinking water',
  'fajta.forras': 'Spring',
  'fajta.esobeallo': 'Rain shelter',
  'fajta.menedekhaz': 'Wilderness hut',
  'fajta.turistahaz': 'Mountain hut',
  'fajta.vasutallomas': 'Railway station',
  'fajta.megallohely': 'Halt',
  'fajta.buszmegallo': 'Bus stop',
  'fajta.parkolo': 'Parking',
  'fajta.kilatopont': 'Viewpoint',
  'fajta.kilatotorony': 'Observation tower',
  'fajta.etterem': 'Restaurant',
  'fajta.kavezo': 'Café',
  'fajta.kocsma': 'Pub',
  'fajta.bufe': 'Fast food',
  'fajta.var': 'Castle',
  'fajta.rom': 'Ruins',
  'fajta.regeszeti': 'Archaeological site',
  'fajta.emlekmu': 'Monument',
  'fajta.muzeum': 'Museum',
  'fajta.vizeses': 'Waterfall',
  'fajta.barlang': 'Cave entrance',
  'fajta.sziklakapu': 'Natural arch',
  'fajta.vilagitotorony': 'Lighthouse',
  'fajta.latnivalo': 'Attraction',
  'viz.ihato': 'drinkable',
  'viz.nemIhato': 'NOT drinkable',
  'viz.nincsAdat': 'no data on whether it is drinkable',

  /* ---- Hibaüzenetek és apróságok ---- */
  'hiba.utvonalkereso': 'The route finder is unavailable right now.',
  'hiba.helykereso': 'The place search is unavailable right now.',
  'hiba.helykeresoNema': 'The place search is not responding.',
  'hiba.haromBetu': 'Type at least three letters.',
  'hiba.nincsHely': 'I found no place for: “{mit}”',
  'hiba.elorejelzes': 'The forecast is unavailable right now.',
  'hiba.homerseklet': 'The temperature is unavailable right now.',
  'hiba.magassag': 'The elevation data is unavailable right now.',
  'hiba.osmNema': 'The OpenStreetMap search is not responding.',
  'hiba.tulterhelt': 'The search is overloaded. Try again in a few seconds.',
  'hiba.terheles': 'The search cannot cope with the load. Try again in a few seconds.',
  'hiba.keresesNemSikerult': 'The search failed.',
  'hiba.ismeretlenReteg': 'Unknown layer.',
  'hiba.nincsHelyzet': 'This browser cannot tell your location.',
  'gpx.nemTud': 'This browser cannot read GPX files.',
  'gpx.serult': 'This file is not readable GPX — corrupted or a different format.',
  'gpx.ures': 'This file contains neither a track nor any markers.',
  'gpx.nagy': 'This file is larger than 5 MB. A track that big cannot be shown sensibly.',
  'gpx.nemSikerult': 'This file could not be read.',
  'terv.ujKezdtel': 'You started a new route — the arrow brings the previous one back.',
  'terv.betoltve': 'Loaded. Drag its points, or add markers.',
  'terv.vagolapon': 'The link is on the clipboard — the route is in the address itself.',
  'terv.cimsorban': 'The shareable link is in the browser’s address bar.',
  'terv.elmentve': 'Saved. On another device, reach it with the shareable link.',
  'terv.nevtelen': 'Unnamed plan',
  'terv.mentesFrissit': 'Update the save',
  'terv.mentesBongeszobe': 'Save to the browser',
  'terkep.cel': 'Finish',
  'terkep.kozremukodoi': 'contributors',
  'hh.koordinata': 'coordinates entered',
  'nap.ketNapMulva': 'In two days',
  'turak.jelzettUt': 'marked trail',
  'kep.lasdForras': 'see the source',
  'ut.ketPont': 'At least two points are needed.',
  'ut.nemErheto': 'The route finder is unavailable right now. Try again later.',
  'ut.tulSok': 'Too many requests in a short time. Wait a moment.',
  'ut.hibat': 'The route finder returned an error.',
  'ut.nincsGyalogut': 'I found no footpath between these points. There may be water or a fence in between.',
  'ut.nemSikerult': 'No route could be found.',
  'ut.tulSokPont': 'I can snap at most {max} points to paths at once. Delete a few, or split it into sections.',
  'ut.nincsGyalogut2': 'I found no footpath between these points. It may cross water or trackless terrain.',
  'terv.egyenesMarad': '{ok} The line stays straight for now, so the distance and ascent are lower than in reality.',
  'adat.tengerszintUtan': 'above sea level',

  /* ---- Főoldal: mit tud, kiemelt példa ---- */
  'fooldal.peldaKalap': 'This is what you get',
  'fooldal.peldaNyisd': 'Open it in the planner',
  'fooldal.mitTud': 'What this map does',
  'fooldal.mitTudLead': 'Four reasons to plan here rather than on a general-purpose map.',
  'fooldal.tud1Cim': 'The line follows real footpaths',
  'fooldal.tud1': 'Not a straight line between two points. Mark two places and the track snaps to the actual paths — which is why the distance and the ascent are true.',
  'fooldal.tud2Cim': 'Walking time counts the climb',
  'fooldal.tud2': 'Ten kilometres on the flat and ten in the hills are not the same time. The estimate adds for every hundred metres of climb, and shows the elevation profile too.',
  'fooldal.tud3Cim': 'It shows what is nearby',
  'fooldal.tud3': 'Seven layers from OpenStreetMap: drinking water, shelter, stops, parking, lookouts, food and drink, sights. In any country in the world, not just at home.',
  'fooldal.tud4Cim': 'It stays yours',
  'fooldal.tud4': 'What you draw is created in your browser. The shareable link carries the route itself, not a database id — and you can download it as GPX, for any watch or app.',
  'adat.menetido': 'walking time',
};
