/* Español. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — inicio',
  'fejlec.menuNyit': 'Abrir el menú',
  'fejlec.menuZar': 'Cerrar el menú',
  'fejlec.foMenu': 'Menú principal',
  'fejlec.sotetMod': 'Cambiar al modo oscuro',
  'fejlec.fok': 'Ahora {fok} grados — {ido}',
  'fejlec.jelenleg': 'Ahora mismo',

  'menu.fooldal': 'Inicio',
  'menu.fooldalLeiras': 'Señales de sendero, ejemplos y opiniones',
  'menu.tervezo': 'Planificador',
  'menu.tervezoLeiras': 'Escribe dos lugares o dibuja en el mapa',
  'menu.peldak': 'Ejemplos',
  'menu.peldakLeiras': 'Rutas ya hechas para empezar',

  'lab.terkep': 'El mapa lo hacen los colaboradores de {osm}, que también aportan las teselas.',
  'lab.becsles': 'La distancia y el tiempo de marcha son estimaciones — sobre el terreno mandan los senderos señalizados.',
  'lab.impresszum': 'Sobre el sitio y datos',

  'fooldal.cim': 'Túrabakancs — mapa para planificar rutas de senderismo',
  'fooldal.lead': 'Un mapa sobre el que dibujar. Rutas ya hechas para empezar. Un tiempo de marcha que cuenta también el desnivel.',
  'fooldal.tervezek': 'Planifico una ruta',
  'fooldal.peldak': 'Veo ejemplos',
  'fooldal.ma': 'Hoy',
  'fooldal.napkelte': 'amanecer',
  'fooldal.napnyugta': 'anochecer',
  'fooldal.vilagosMeg': 'de luz aún',
  'fooldal.lement': 'ya se puso',
  'fooldal.vanMeg': 'aún hay luz',
  'fooldal.marLement': 'el sol ya se ha puesto',
  'fooldal.napAlap': 'Para Budapest. El planificador calcula desde el inicio de tu propia ruta.',
  'fooldal.jelzesCim': '¿Qué significa la pintura en el árbol?',
  'fooldal.jelzesLead': 'Una señal de sendero húngara dice dos cosas a la vez. El color, lo grande que es la ruta; la forma, para qué sirve.',
  'fooldal.jelzesSzin': 'color',
  'fooldal.jelzesAlak': 'forma',
  'fooldal.jelzesApro': 'No lo escribimos de memoria: lo comprobamos en los senderos señalizados de OpenStreetMap para ver qué lleva adónde. Las rutas marcadas con triángulo terminan en una cima o un mirador; las marcadas con círculo vuelven al punto de partida.',
  'fooldal.keszVonal': 'Empieza por una ruta ya hecha',
  'fooldal.keszVonalLead': 'Ábrela, arrastra sus puntos, hazla tuya.',
  'fooldal.szerintunk': 'creemos',
  'fooldal.osszesPelda': 'Todos los ejemplos →',

  'peldak.kicsi': 'Ejemplos',
  'peldak.cim': 'Rutas ya hechas para empezar.',
  'peldak.bevezeto': 'Abre cualquiera, arrastra sus puntos, pon tus propias marcas — y ya es tuya.',
  'peldak.tajegyseg': 'Región',
  'peldak.mindegyik': 'Todas',
  'peldak.hossz': 'Longitud',
  'peldak.nehezseg': 'Dificultad',
  'peldak.torold': 'borrar todo',
  'peldak.szurokTorol': 'borrar filtros',
  'peldak.utvonal': 'rutas',
  'peldak.megnezem': 'Ver',
  'peldak.gyalogut': 'Las rutas siguen senderos reales',
  'peldak.gyalogutUtan': ', no en línea recta entre dos puntos — por eso la distancia y el desnivel son ciertos. Sobre el terreno siguen mandando los senderos señalizados y los mapas oficiales.',
  'peldak.darab': '{db} rutas',

  'utvonal.nincs': 'Esta ruta no existe.',
  'utvonal.tobbi': 'Aquí están los demás ejemplos.',
  'tempo.gyalog': 'A pie',
  'tempo.futas': 'Corriendo',
  'tempo.bringa': 'Bicicleta',
  'utvonal.elgepelt': 'Quizá has escrito mal la dirección.',
  'utvonal.kozelitoUtan': ' Sobre el terreno mandan los senderos señalizados y los mapas oficiales.',
  'utvonal.hossz': 'Longitud',
  'utvonal.sik': 'Calculado para terreno llano; en subida, más.',
  'utvonal.jelolesek': 'Marcas',
  'utvonal.kozelito': 'Trazado aproximado, no un sendero medido.',
  'utvonal.megnyitas': 'Abrir en el planificador',
  'utvonal.gpx': 'Descargar GPX',

  'tervezo.honnanHova': '¿De dónde a dónde?',
  'tervezo.adatok': 'Datos de la ruta',
  'tervezo.adatokCimke': 'Datos de la ruta — {km}, {ido}',
  'tervezo.eszkozok': 'Guardar, rutas ya hechas, GPX',
  'tervezo.vissza': 'Un paso atrás',
  'tervezo.retegek': 'Qué debe mostrar el mapa',
  'tervezo.ujraKeres': 'Buscar en esta zona',

  'hh.honnan': 'Desde',
  'hh.hova': 'Hasta — si lo dejas vacío, solo saltamos allí',
  'hh.honnanHely': 'Nombre del lugar o coordenadas',
  'hh.hovaHely': 'Por ejemplo: Mulhacén',
  'hh.innen': 'Salgo desde aquí',
  'hh.odaugras': 'Ir allí',
  'hh.szamolom': 'Calculando…',
  'hh.utvonalat': 'Quiero una ruta',
  'hh.keres': 'Buscando…',
  'hh.nincsHelyzet': 'No he podido obtener tu posición. Escribe el punto de partida a mano.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'longitud',
  'adat.emelkedo': 'desnivel positivo',
  'adat.lejto': 'desnivel negativo',
  'adat.nehezseg': 'dificultad',
  'adat.tempo': 'Ritmo',
  'adat.tengerszint': '{also}–{felso} m sobre el nivel del mar',
  'adat.nev': 'Por ejemplo: vuelta del domingo',

  'terkep.igazit': 'Ajusto la línea a senderos reales…',
  'terkep.masodik': 'Marca el segundo punto — la línea se ajusta sola al sendero.',
  'terkep.keszUt': 'Ruta lista. Toca el mapa para empezar otra.',
  'terkep.sug': 'Toca el mapa para poner puntos. Los puntos se arrastran; al tocarlos se borran.',
  'terkep.keszVonal': 'Listo — la línea sigue senderos reales.',
  'jeloles.ugras': 'Ir a: {nev}',
  'jeloles.neve': 'Nombre: {tipus}',
  'terkep.jelolesTorol': 'Borrar la marca',
  'terkep.tobbVan': 'aquí hay más — acerca el mapa',
  'terkep.keresem': 'buscando…',
  'terkep.nagyits': 'acerca el mapa',
  'terkep.hiba': 'no se pudo',
  'terkep.nincsAdat': 'sin datos',

  'reteg.viz': 'Agua potable, manantial',
  'reteg.menedek': 'Refugio',
  'reteg.kozlekedes': 'Parada, estación',
  'reteg.parkolo': 'Aparcamiento',
  'reteg.kilato': 'Mirador',
  'reteg.vendeglatas': 'Comer y beber',
  'reteg.latvany': 'Lugar de interés',

  'nincs.cim': 'No existe esa página',
  'nincs.magyarazat': 'O has escrito mal la dirección, o apunta a una página que ya no existe.',
  'nincs.lead': 'Desde aquí puedes seguir:',
  'nincs.kezdolap': 'Inicio',
  'nincs.tervezo': 'Planificador de rutas',
  'nincs.tervezoLeiras': 'dibuja una ruta en el mapa',
  'nincs.peldak': 'Rutas ya hechas',
  'nincs.peldakLeiras': 'ejemplos que puedes abrir',

  'meta.fooldalCim': 'Túrabakancs — rutas de senderismo, señales, opiniones',
  'meta.fooldalLeiras': 'Mapa para planificar rutas, explicación de las señales de sendero húngaras y opiniones sin nombres.',
  'meta.tervezoCim': 'Planificador — Túrabakancs',
  'meta.tervezoLeiras': 'Dibuja una ruta en el mapa, pon marcas, compártela con un enlace.',
  'meta.peldakCim': 'Rutas de ejemplo — Túrabakancs',
  'meta.peldakLeiras': 'Rutas de senderismo ya hechas en el mapa, que puedes abrir y seguir dibujando.',
  'meta.impresszumCim': 'Sobre el sitio y datos — Túrabakancs',
  'meta.impresszumLeiras': 'Para qué sirve el sitio y para qué no. Sin cuenta, sin cookies, sin medición; lo que dibujas se queda en tu navegador.',
  'meta.nincsCim': 'No existe esa página — Túrabakancs',
  'meta.nincsLeiras': 'Esta dirección no existe.',

  /* ---- Nehézség, szűrők, ajánló ---- */
  'nehez.konnyu': 'Fácil',
  'nehez.kozepes': 'Media',
  'nehez.eros': 'Exigente',
  'nehez.nehez': 'Difícil',
  'nehez.konnyuLeiras': 'Un paseo corto, cualquiera puede.',
  'nehez.kozepesLeiras': 'Media jornada, no hace falta estar en forma.',
  'nehez.erosLeiras': 'Una ruta de día completo, prepárate.',
  'nehez.nehezLeiras': 'Un día largo. Solo con experiencia y equipo.',
  'szuro.rovid': 'Corta',
  'szuro.kozepes': 'Media',
  'szuro.hosszu': 'Larga',
  'szuro.rovidLeiras': 'menos de 3 km',
  'szuro.kozepesLeiras': '3–8 km',
  'szuro.hosszuLeiras': 'más de 8 km',
  'tanacs.osszkepCimke': '{nehez} — {ido} de marcha',
  'tanacs.osszkepMagassag': '{km} km, {fel} m de desnivel. {leiras} El tiempo de marcha es sin descansos; suma al menos media hora.',
  'tanacs.osszkepNincs': '{km} km. {leiras} Aún estoy cargando el desnivel; hasta entonces el tiempo de marcha solo cuenta la distancia.',
  'tanacs.sotetCimke': 'El sol ya se ha puesto',
  'tanacs.sotetSzoveg': 'Hoy el anochecer fue a las {ido}. Si sales ahora, no vayas sin frontal.',
  'tanacs.sotetedesCimke': 'No llegarás antes de que anochezca',
  'tanacs.sotetedesSzoveg': 'Anochece a las {nyugta}, quedan {maradek}. La ruta lleva {ut}, sin descansos. Lleva frontal o sal antes.',
  'tanacs.vilagosCimke': '{maradek} hasta el anochecer',
  'tanacs.vilagosSzoveg': 'Hoy anochece a las {ido}. Si sales ahora, te sobra tiempo.',
  'tanacs.visszautCimke': 'La meta no está donde la salida',
  'tanacs.visszautSzoveg': 'Los separan {tav} km. Si vas en coche, piensa cómo vuelves a por él — o planifica un circular.',
  'tanacs.vizCimke': 'No hay punto de agua marcado',
  'tanacs.vizSzoveg': 'Para {km} km es poco. Activa la capa de agua potable: te enseño qué hay cerca.',
  'tanacs.megkozelitesCimke': 'No está marcado cómo llegar a la salida',
  'tanacs.megkozelitesSzoveg': 'Será la primera pregunta antes de salir. Con la capa de paradas ves qué hay cerca.',
  'tanacs.durvaCimke': 'La línea es muy recta',
  'tanacs.durvaSzoveg': 'De media {atlag} km por tramo. Un sendero real serpentea, así que la distancia real es mayor — añade más puntos para afinar.',
  'tanacs.emelkedoCimke': '{fel} metros de desnivel',
  'tanacs.emelkedoSzoveg': 'El punto más bajo está a {min} m y el más alto a {max} m. Solo este desnivel añade {plusz} al tiempo de marcha.',
  'tanacs.veszelyCimke': 'Has marcado un tramo difícil',
  'tanacs.veszelySzoveg': 'Tras la lluvia y con helada, los tramos empinados y rocosos son mucho más lentos y arriesgados. Mira el tiempo antes de salir.',

  /* ---- Időjárás és jelöléstípusok ---- */
  'ido.derult': 'Despejado',
  'ido.jobbaraDerult': 'Mayormente despejado',
  'ido.szakadozott': 'Nubes dispersas',
  'ido.borult': 'Cubierto',
  'ido.kod': 'Niebla',
  'ido.zuzmarasKod': 'Niebla helada',
  'ido.gyengeSzitalas': 'Llovizna débil',
  'ido.szitalas': 'Llovizna',
  'ido.erosSzitalas': 'Llovizna intensa',
  'ido.gyengeEso': 'Lluvia débil',
  'ido.eso': 'Lluvia',
  'ido.erosEso': 'Lluvia intensa',
  'ido.gyengeHavazas': 'Nieve débil',
  'ido.havazas': 'Nieve',
  'ido.erosHavazas': 'Nieve intensa',
  'ido.hoszemcsek': 'Granos de nieve',
  'ido.zapor': 'Chubascos',
  'ido.hevesZapor': 'Chubascos fuertes',
  'ido.hozapor': 'Chubascos de nieve',
  'ido.erosHozapor': 'Chubascos fuertes de nieve',
  'ido.zivatar': 'Tormenta',
  'ido.jegesoZivatar': 'Tormenta con granizo',
  'ido.hevesJegeso': 'Tormenta severa con granizo',
  'ido.ismeretlen': 'Desconocido',
  'idoFigy.zivatar': 'Se esperan tormentas. Una cresta o un mirador no son sitio para estar.',
  'idoFigy.sokCsapadek': '{mm} mm de precipitación: los tramos rocosos y las escaleras resbalarán.',
  'idoFigy.eso': 'Se espera lluvia — en las pendientes embarradas se avanza más despacio.',
  'idoFigy.meleg': '{fok} grados: en los tramos sin sombra, lleva el doble de agua.',
  'idoFigy.fagy': '{fok} grados al amanecer: el sendero puede estar helado.',
  'idoFigy.szel': 'Viento de {szel} km/h: incómodo en la cresta, frío en el mirador.',
  'tipus.kilato': 'Mirador',
  'tipus.forras': 'Manantial, agua potable',
  'tipus.pihen': 'Descanso, banco',
  'tipus.parkolo': 'Aparcamiento',
  'tipus.vendeglatas': 'Comer y beber',
  'tipus.latnivalo': 'Lugar de interés',
  'tipus.veszely': 'Peligro, tramo difícil',
  'tipus.kozlekedes': 'Parada, estación',

  /* ---- Tanácsok, túralista, napnevek ---- */
  'tanacs.lekerem': 'Consultando…',
  'tanacs.milyenIdo': '¿Qué tiempo hará?',
  'nap.ma': 'hoy',
  'nap.holnap': 'mañana',
  'turak.lead': 'Te enseño qué {jelzett} pasan por donde está el mapa. Puedes cargar cualquiera y seguir dibujando.',
  'turak.jelzett': 'senderos señalizados',
  'turak.keresem': 'Buscando…',
  'turak.keres': 'Buscar senderos en esta zona',
  'turak.tolt': 'cargando…',
  'turak.festett': 'Sobre el terreno manda la marca pintada.',

  /* ---- Impresszum és adatkezelés ---- */
  'imp.cim': 'Sobre el sitio y datos',
  'imp.felelossegCim': 'Responsabilidad — léelo antes de salir',
  'imp.felelossegLead': 'El sitio muestra rutas, distancias, desniveles, tiempos de marcha y el anochecer. Son {eros}, no garantías:',
  'imp.felelossegEros': 'cálculos y estimaciones',
  'imp.felelosseg1': 'Las líneas siguen senderos de los datos del mapa. Si un sendero es transitable ahora mismo, el mapa no lo sabe — puede haber caído un árbol, la lluvia puede haberlo arrastrado, puede estar cerrado.',
  'imp.felelosseg2': 'El tiempo de marcha supone terreno llano y ritmo medio. La carga, la nieve, el barro, el anochecer y tu propia forma lo cambian.',
  'imp.felelosseg3': 'El desnivel procede de un modelo del terreno, que puede diferir de la realidad en unos metros.',
  'imp.felelossegZaro': '{eros} Para orientarte sirven los senderos señalizados y los mapas oficiales; mira el tiempo antes de salir y dile a alguien adónde vas. Este sitio ayuda a planificar — no sustituye al sentido común.',
  'imp.felelossegZaroEros': 'Sobre el terreno cuentan tu decisión y tu responsabilidad.',
  'imp.tartalomCim': 'El contenido',
  'imp.tartalom': 'Las valoraciones con estrellas son nuestra opinión, no la media de puntuaciones ajenas. Los datos del mapa vienen de OpenStreetMap, mantenido por voluntarios. Las fotos de los lugares están bajo licencias libres, con el nombre de sus autores — la lista completa abajo, en {link}.',
  'imp.adatCim': 'Datos personales',
  'imp.adat1': 'El sitio no pide cuenta, no recoge datos personales y no usa cookies. Lo que dibujas se crea en tu navegador y ahí se queda: tus planes guardados van al almacenamiento de tu propio equipo, y el enlace para compartir mete la ruta en la propia dirección, no en una base de datos.',
  'imp.adat2': 'Lo que sí sale a internet no viene a nosotros. Las teselas del mapa y las respuestas de la búsqueda de lugares las dan los servicios públicos de OpenStreetMap, los datos de altitud Open-Meteo, y el ajuste de las rutas a los senderos el enrutador peatonal de FOSSGIS. Si señalas un lugar de interés, su foto la da Wikimedia Commons — solo cuando lo señalas. En esos momentos — como con cualquier imagen de cualquier web — tu dirección IP les es visible, y en el ajuste y la altitud también las coordenadas de tu línea. No podemos evitarlo si queremos mostrar un mapa; pero al menos lo sabes.',
  'imp.kepekCim': 'Las imágenes',
  'imp.kepek': 'Las fotos de los lugares vienen de Wikimedia Commons y están bajo licencias libres — pero libre no significa sin dueño: cada una tiene un autor al que hay que nombrar. Una imagen solo se descarga cuando señalas un lugar, y el nombre del autor siempre la acompaña. La lista de abajo recoge los quince lugares húngaros cuyas imágenes alojamos nosotros.',

  /* ---- Alfajták és ivhatóság ---- */
  'fajta.ivoviz': 'Agua potable',
  'fajta.forras': 'Manantial',
  'fajta.esobeallo': 'Refugio de lluvia',
  'fajta.menedekhaz': 'Refugio',
  'fajta.turistahaz': 'Albergue de montaña',
  'fajta.vasutallomas': 'Estación de tren',
  'fajta.megallohely': 'Apeadero',
  'fajta.buszmegallo': 'Parada de autobús',
  'fajta.parkolo': 'Aparcamiento',
  'fajta.kilatopont': 'Mirador',
  'fajta.kilatotorony': 'Torre mirador',
  'fajta.etterem': 'Restaurante',
  'fajta.kavezo': 'Cafetería',
  'fajta.kocsma': 'Bar',
  'fajta.bufe': 'Comida rápida',
  'fajta.var': 'Castillo',
  'fajta.rom': 'Ruinas',
  'fajta.regeszeti': 'Yacimiento arqueológico',
  'fajta.emlekmu': 'Monumento',
  'fajta.muzeum': 'Museo',
  'fajta.vizeses': 'Cascada',
  'fajta.barlang': 'Entrada de cueva',
  'fajta.sziklakapu': 'Arco natural',
  'fajta.vilagitotorony': 'Faro',
  'fajta.latnivalo': 'Atracción',
  'viz.ihato': 'potable',
  'viz.nemIhato': 'NO potable',
  'viz.nincsAdat': 'sin datos sobre si es potable',

  /* ---- Hibaüzenetek és apróságok ---- */
  'hiba.utvonalkereso': 'El buscador de rutas no está disponible ahora.',
  'hiba.helykereso': 'La búsqueda de lugares no está disponible ahora.',
  'hiba.helykeresoNema': 'La búsqueda de lugares no responde.',
  'hiba.haromBetu': 'Escribe al menos tres letras.',
  'hiba.nincsHely': 'No he encontrado ningún lugar para: «{mit}»',
  'hiba.elorejelzes': 'La previsión no está disponible ahora.',
  'hiba.homerseklet': 'La temperatura no está disponible ahora.',
  'hiba.magassag': 'Los datos de altitud no están disponibles ahora.',
  'hiba.osmNema': 'La búsqueda de OpenStreetMap no responde.',
  'hiba.tulterhelt': 'La búsqueda está saturada. Inténtalo en unos segundos.',
  'hiba.terheles': 'La búsqueda no da abasto. Inténtalo en unos segundos.',
  'hiba.keresesNemSikerult': 'La búsqueda ha fallado.',
  'hiba.ismeretlenReteg': 'Capa desconocida.',
  'hiba.nincsHelyzet': 'Este navegador no puede saber tu posición.',
  'gpx.nemTud': 'Este navegador no puede leer archivos GPX.',
  'gpx.serult': 'Este archivo no es un GPX legible — dañado o de otro formato.',
  'gpx.ures': 'Este archivo no tiene ni traza ni marcas.',
  'gpx.nagy': 'Este archivo supera los 5 MB. Una traza así de grande no se puede mostrar bien.',
  'gpx.nemSikerult': 'No se ha podido leer este archivo.',
  'terv.ujKezdtel': 'Has empezado una ruta nueva — con la flecha recuperas la anterior.',
  'terv.betoltve': 'Cargado. Arrastra sus puntos o añade marcas.',
  'terv.vagolapon': 'El enlace está en el portapapeles — la ruta va en la propia dirección.',
  'terv.cimsorban': 'El enlace para compartir está en la barra de direcciones.',
  'terv.elmentve': 'Guardado. En otro dispositivo lo alcanzas con el enlace para compartir.',
  'terv.nevtelen': 'Plan sin nombre',
  'terv.mentesFrissit': 'Actualizar lo guardado',
  'terv.mentesBongeszobe': 'Guardar en el navegador',
  'terkep.cel': 'Meta',
  'terkep.kozremukodoi': 'colaboradores',
  'terkep.rajt': 'Salida',
  'terkep.hanyadikPont': 'Punto {n}',
  'hh.koordinata': 'coordenadas introducidas',
  'nap.ketNapMulva': 'En dos días',
  'turak.jelzettUt': 'sendero señalizado',
  'kep.lasdForras': 'ver la fuente',
  'ut.ketPont': 'Hacen falta al menos dos puntos.',
  'ut.nemErheto': 'El buscador de rutas no está disponible. Inténtalo más tarde.',
  'ut.tulSok': 'Demasiadas peticiones en poco tiempo. Espera un momento.',
  'ut.hibat': 'El buscador de rutas ha dado un error.',
  'ut.nincsGyalogut': 'No he encontrado sendero entre estos puntos. Puede que haya agua o una valla.',
  'ut.nemSikerult': 'No se ha podido encontrar una ruta.',
  'ut.tulSokPont': 'Puedo ajustar como mucho {max} puntos a senderos de una vez. Borra algunos o divídelo en tramos.',
  'ut.nincsGyalogut2': 'No he encontrado sendero entre estos puntos. Puede que cruce agua o terreno sin caminos.',
  'terv.egyenesMarad': '{ok} La línea sigue recta por ahora, así que la distancia y el desnivel son menores que en la realidad.',
  'adat.tengerszintUtan': 'sobre el nivel del mar',

  /* ---- Főoldal: mit tud, kiemelt példa ---- */
  'fooldal.peldaKalap': 'Así es lo que obtienes',
  'fooldal.peldaNyisd': 'Abrir en el planificador',
  'fooldal.mitTud': 'Qué hace este mapa',
  'fooldal.mitTudLead': 'Cuatro razones para planificar aquí y no en un mapa general.',
  'fooldal.tud1Cim': 'La línea sigue senderos reales',
  'fooldal.tud1': 'No es una línea recta entre dos puntos. Marca dos sitios y el trazado se ajusta solo a los senderos reales — por eso la distancia y el desnivel son ciertos.',
  'fooldal.tud2Cim': 'El tiempo de marcha cuenta la subida',
  'fooldal.tud2': 'Diez kilómetros en llano y diez en montaña no son el mismo tiempo. La estimación suma por cada cien metros de subida y muestra también el perfil.',
  'fooldal.tud3Cim': 'Muestra qué hay cerca',
  'fooldal.tud3': 'Siete capas de OpenStreetMap: agua potable, refugios, paradas, aparcamientos, miradores, comida, lugares de interés. En cualquier país del mundo.',
  'fooldal.tud4Cim': 'Sigue siendo tuyo',
  'fooldal.tud4': 'Lo que dibujas se crea en tu navegador. El enlace para compartir lleva la propia ruta, no un id de base de datos — y puedes descargarla en GPX, para cualquier reloj o app.',
  'adat.menetido': 'tiempo de marcha',
};
