/* Español. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — inicio',
  'fejlec.menuNyit': 'Abrir el menú',
  'fejlec.menuZar': 'Cerrar el menú',
  'fejlec.foMenu': 'Menú principal',
  'fejlec.sotetMod': 'Cambiar al modo oscuro',
  'fejlec.fok': 'Ahora {fok} grados — {ido}',
  'fejlec.jelenleg': 'Ahora mismo',

  'menu.fooldal': 'Inicio',
  'menu.fooldalLeiras': 'Señales de sendero, ejemplos y opiniones',
  'menu.tervezo': 'Planificador',
  'menu.tervezoLeiras': 'Escribe dos lugares o dibuja en el mapa',
  'menu.peldak': 'Ejemplos',
  'menu.peldakLeiras': 'Rutas ya hechas para empezar',

  'lab.terkep': 'El mapa lo hacen los colaboradores de {osm}, que también aportan las teselas.',
  'lab.becsles': 'La distancia y el tiempo de marcha son estimaciones — sobre el terreno mandan los senderos señalizados.',
  'lab.impresszum': 'Sobre el sitio y datos',

  'fooldal.cim': 'Túrabakancs — mapa para planificar rutas de senderismo',
  'fooldal.lead': 'Un mapa sobre el que dibujar. Rutas ya hechas para empezar. Un tiempo de marcha que cuenta también el desnivel.',
  'fooldal.tervezek': 'Planifico una ruta',
  'fooldal.peldak': 'Veo ejemplos',
  'fooldal.ma': 'Hoy',
  'fooldal.napkelte': 'amanecer',
  'fooldal.napnyugta': 'anochecer',
  'fooldal.vilagosMeg': 'de luz aún',
  'fooldal.lement': 'ya se puso',
  'fooldal.vanMeg': 'aún hay luz',
  'fooldal.marLement': 'el sol ya se ha puesto',
  'fooldal.napAlap': 'Para Budapest. El planificador calcula desde el inicio de tu propia ruta.',
  'fooldal.jelzesCim': '¿Qué significa la pintura en el árbol?',
  'fooldal.jelzesLead': 'Una señal de sendero húngara dice dos cosas a la vez. El color, lo grande que es la ruta; la forma, para qué sirve.',
  'fooldal.jelzesSzin': 'color',
  'fooldal.jelzesAlak': 'forma',
  'fooldal.jelzesApro': 'No lo escribimos de memoria: lo comprobamos en los senderos señalizados de OpenStreetMap para ver qué lleva adónde. Las rutas marcadas con triángulo terminan en una cima o un mirador; las marcadas con círculo vuelven al punto de partida.',
  'fooldal.keszVonal': 'Empieza por una ruta ya hecha',
  'fooldal.keszVonalLead': 'Ábrela, arrastra sus puntos, hazla tuya.',
  'fooldal.szerintunk': 'creemos',
  'fooldal.osszesPelda': 'Todos los ejemplos →',

  'peldak.kicsi': 'Ejemplos',
  'peldak.cim': 'Rutas ya hechas para empezar.',
  'peldak.bevezeto': 'Abre cualquiera, arrastra sus puntos, pon tus propias marcas — y ya es tuya.',
  'peldak.tajegyseg': 'Región',
  'peldak.mindegyik': 'Todas',
  'peldak.hossz': 'Longitud',
  'peldak.nehezseg': 'Dificultad',
  'peldak.torold': 'borrar todo',
  'peldak.szurokTorol': 'borrar filtros',
  'peldak.utvonal': 'rutas',
  'peldak.megnezem': 'Ver',
  'peldak.gyalogut': 'Las rutas siguen senderos reales',
  'peldak.gyalogutUtan': ', no en línea recta entre dos puntos — por eso la distancia y el desnivel son ciertos. Sobre el terreno siguen mandando los senderos señalizados y los mapas oficiales.',
  'peldak.darab': '{db} rutas',

  'utvonal.nincs': 'Esta ruta no existe.',
  'utvonal.tobbi': 'Aquí están los demás ejemplos.',
  'utvonal.hossz': 'Longitud',
  'utvonal.sik': 'Calculado para terreno llano; en subida, más.',
  'utvonal.jelolesek': 'Marcas',
  'utvonal.kozelito': 'Trazado aproximado, no un sendero medido.',
  'utvonal.megnyitas': 'Abrir en el planificador',
  'utvonal.gpx': 'Descargar GPX',

  'tervezo.honnanHova': '¿De dónde a dónde?',
  'tervezo.adatok': 'Datos de la ruta',
  'tervezo.adatokCimke': 'Datos de la ruta — {km}, {ido}',
  'tervezo.eszkozok': 'Guardar, rutas ya hechas, GPX',
  'tervezo.vissza': 'Un paso atrás',
  'tervezo.retegek': 'Qué debe mostrar el mapa',
  'tervezo.ujraKeres': 'Buscar en esta zona',

  'hh.honnan': 'Desde',
  'hh.hova': 'Hasta — si lo dejas vacío, solo saltamos allí',
  'hh.honnanHely': 'Nombre del lugar o coordenadas',
  'hh.hovaHely': 'Por ejemplo: Mulhacén',
  'hh.innen': 'Salgo desde aquí',
  'hh.odaugras': 'Ir allí',
  'hh.szamolom': 'Calculando…',
  'hh.utvonalat': 'Quiero una ruta',
  'hh.keres': 'Buscando…',
  'hh.nincsHelyzet': 'No he podido obtener tu posición. Escribe el punto de partida a mano.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'longitud',
  'adat.emelkedo': 'desnivel positivo',
  'adat.lejto': 'desnivel negativo',
  'adat.nehezseg': 'dificultad',
  'adat.tempo': 'Ritmo',
  'adat.tengerszint': '{also}–{felso} m sobre el nivel del mar',
  'adat.nev': 'Por ejemplo: vuelta del domingo',

  'terkep.igazit': 'Ajusto la línea a senderos reales…',
  'terkep.masodik': 'Marca el segundo punto — la línea se ajusta sola al sendero.',
  'terkep.keszUt': 'Ruta lista. Toca el mapa para empezar otra.',
  'terkep.sug': 'Toca el mapa para poner puntos. Los puntos se arrastran; al tocarlos se borran.',
  'terkep.keszVonal': 'Listo — la línea sigue senderos reales.',
  'terkep.jelolesTorol': 'Borrar la marca',
  'terkep.tobbVan': 'aquí hay más — acerca el mapa',
  'terkep.keresem': 'buscando…',
  'terkep.nagyits': 'acerca el mapa',
  'terkep.hiba': 'no se pudo',
  'terkep.nincsAdat': 'sin datos',

  'reteg.viz': 'Agua potable, manantial',
  'reteg.menedek': 'Refugio',
  'reteg.kozlekedes': 'Parada, estación',
  'reteg.parkolo': 'Aparcamiento',
  'reteg.kilato': 'Mirador',
  'reteg.vendeglatas': 'Comer y beber',
  'reteg.latvany': 'Lugar de interés',

  'nincs.cim': 'No existe esa página',
  'nincs.magyarazat': 'O has escrito mal la dirección, o apunta a una página que ya no existe.',
  'nincs.lead': 'Desde aquí puedes seguir:',
  'nincs.kezdolap': 'Inicio',
  'nincs.tervezo': 'Planificador de rutas',
  'nincs.tervezoLeiras': 'dibuja una ruta en el mapa',
  'nincs.peldak': 'Rutas ya hechas',
  'nincs.peldakLeiras': 'ejemplos que puedes abrir',

  'meta.fooldalCim': 'Túrabakancs — rutas de senderismo, señales, opiniones',
  'meta.fooldalLeiras': 'Mapa para planificar rutas, explicación de las señales de sendero húngaras y opiniones sin nombres.',
  'meta.tervezoCim': 'Planificador — Túrabakancs',
  'meta.tervezoLeiras': 'Dibuja una ruta en el mapa, pon marcas, compártela con un enlace.',
  'meta.peldakCim': 'Rutas de ejemplo — Túrabakancs',
  'meta.peldakLeiras': 'Rutas de senderismo ya hechas en el mapa, que puedes abrir y seguir dibujando.',
  'meta.impresszumCim': 'Sobre el sitio y datos — Túrabakancs',
  'meta.impresszumLeiras': 'Para qué sirve el sitio y para qué no. Sin cuenta, sin cookies, sin medición; lo que dibujas se queda en tu navegador.',
  'meta.nincsCim': 'No existe esa página — Túrabakancs',
  'meta.nincsLeiras': 'Esta dirección no existe.',
};
