/* Français. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — accueil',
  'fejlec.menuNyit': 'Ouvrir le menu',
  'fejlec.menuZar': 'Fermer le menu',
  'fejlec.foMenu': 'Menu principal',
  'fejlec.sotetMod': 'Basculer le mode sombre',
  'fejlec.fok': 'Actuellement {fok} degrés — {ido}',
  'fejlec.jelenleg': 'Actuellement',

  'menu.fooldal': 'Accueil',
  'menu.fooldalLeiras': 'Balisage, exemples et avis',
  'menu.tervezo': 'Planificateur',
  'menu.tervezoLeiras': 'Saisis deux lieux, ou dessine sur la carte',
  'menu.peldak': 'Exemples',
  'menu.peldakLeiras': 'Des itinéraires prêts pour commencer',

  'lab.terkep': 'La carte est réalisée par les contributeurs d’{osm}, qui fournissent aussi les tuiles.',
  'lab.becsles': 'La distance et le temps de marche sont des estimations — sur le terrain, ce sont les sentiers balisés qui font foi.',
  'lab.impresszum': 'À propos et données',

  'fooldal.cim': 'Túrabakancs — carte de planification de randonnées',
  'fooldal.lead': 'Une carte sur laquelle dessiner. Des randonnées prêtes pour commencer. Un temps de marche qui tient compte du dénivelé.',
  'fooldal.tervezek': 'Je planifie une randonnée',
  'fooldal.peldak': 'Je regarde des exemples',
  'fooldal.ma': 'Aujourd’hui',
  'fooldal.napkelte': 'lever du soleil',
  'fooldal.napnyugta': 'coucher du soleil',
  'fooldal.vilagosMeg': 'de jour restant',
  'fooldal.lement': 'couché',
  'fooldal.vanMeg': 'encore clair',
  'fooldal.marLement': 'le soleil est couché',
  'fooldal.napAlap': 'Pour Budapest. Le planificateur calcule à partir du départ de ton propre itinéraire.',
  'fooldal.jelzesCim': 'Que veut dire la peinture sur l’arbre ?',
  'fooldal.jelzesLead': 'Un balisage hongrois dit deux choses à la fois. La couleur indique l’importance de l’itinéraire, la forme indique à quoi il sert.',
  'fooldal.jelzesSzin': 'couleur',
  'fooldal.jelzesAlak': 'forme',
  'fooldal.jelzesApro': 'Nous ne l’avons pas écrit de mémoire : nous avons vérifié sur les sentiers balisés d’OpenStreetMap ce qui mène où. Les itinéraires marqués d’un triangle se terminent à un sommet ou à un belvédère, ceux marqués d’un cercle reviennent à leur point de départ.',
  'fooldal.keszVonal': 'Commence par un itinéraire prêt',
  'fooldal.keszVonalLead': 'Ouvre-le, déplace ses points, fais-en le tien.',
  'fooldal.szerintunk': 'selon nous',
  'fooldal.osszesPelda': 'Tous les exemples →',

  'peldak.kicsi': 'Exemples',
  'peldak.cim': 'Des itinéraires prêts pour commencer.',
  'peldak.bevezeto': 'Ouvre n’importe lequel, déplace ses points, ajoute tes propres repères — et il est à toi.',
  'peldak.tajegyseg': 'Région',
  'peldak.mindegyik': 'Tous',
  'peldak.hossz': 'Longueur',
  'peldak.nehezseg': 'Difficulté',
  'peldak.torold': 'tout effacer',
  'peldak.szurokTorol': 'effacer les filtres',
  'peldak.utvonal': 'itinéraires',
  'peldak.megnezem': 'Voir',
  'peldak.gyalogut': 'Les tracés suivent de vrais sentiers',
  'peldak.gyalogutUtan': ', pas en ligne droite entre deux points — c’est pourquoi la distance et le dénivelé sont justes. Sur le terrain, ce sont malgré tout les sentiers balisés et les cartes officielles qui font foi.',
  'peldak.darab': '{db} itinéraires',

  'utvonal.nincs': 'Cet itinéraire n’existe pas.',
  'utvonal.tobbi': 'Voici les autres exemples.',
  'tempo.gyalog': 'À pied',
  'tempo.futas': 'Course',
  'tempo.bringa': 'Vélo',
  'utvonal.elgepelt': 'Tu t’es peut-être trompé d’adresse.',
  'utvonal.kozelitoUtan': ' Sur le terrain, ce sont les sentiers balisés et les cartes officielles qui font foi.',
  'utvonal.hossz': 'Longueur',
  'utvonal.sik': 'Calculé pour un terrain plat ; davantage en montée.',
  'utvonal.jelolesek': 'Repères',
  'utvonal.kozelito': 'Tracé approximatif, pas un sentier relevé.',
  'utvonal.megnyitas': 'Ouvrir dans le planificateur',
  'utvonal.gpx': 'Télécharger le GPX',

  'tervezo.honnanHova': 'D’où à où ?',
  'tervezo.adatok': 'Données de l’itinéraire',
  'tervezo.adatokCimke': 'Données de l’itinéraire — {km}, {ido}',
  'tervezo.eszkozok': 'Enregistrer, itinéraires prêts, GPX',
  'tervezo.vissza': 'Un pas en arrière',
  'tervezo.oldalCim': 'Planificateur d’itinéraires',
  'tervezo.retegek': 'Ce que la carte doit montrer',
  'tervezo.ujraKeres': 'Chercher dans cette zone',

  'hh.honnan': 'De',
  'hh.hova': 'À — si tu laisses vide, on s’y rend simplement',
  'hh.honnanHely': 'Nom du lieu ou coordonnées',
  'hh.hovaHely': 'Par exemple : Mont Blanc',
  'hh.innen': 'Je pars d’ici',
  'hh.odaugras': 'Aller là-bas',
  'hh.szamolom': 'Calcul…',
  'hh.utvonalat': 'Calculer l’itinéraire',
  'hh.keres': 'Recherche…',
  'hh.nincsHelyzet': 'Je n’ai pas pu obtenir ta position. Saisis le point de départ à la main.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'longueur',
  'adat.emelkedo': 'dénivelé positif',
  'adat.lejto': 'dénivelé négatif',
  'adat.nehezseg': 'difficulté',
  'adat.tempo': 'Allure',
  'adat.tengerszint': '{also}–{felso} m d’altitude',
  'adat.nev': 'Par exemple : boucle du dimanche',

  'terkep.igazit': 'J’aligne le tracé sur de vrais sentiers…',
  'terkep.masodik': 'Pose le deuxième point — le tracé se cale tout seul sur le sentier.',
  'terkep.keszUt': 'Itinéraire prêt. Touche la carte pour en commencer un nouveau.',
  'terkep.sug': 'Touche la carte pour poser des points. Les points se déplacent ; une touche les supprime.',
  'terkep.keszVonal': 'Voilà — le tracé suit de vrais sentiers.',
  'jeloles.ugras': 'Aller à : {nev}',
  'jeloles.neve': 'Nom : {tipus}',
  'terkep.jelolesTorol': 'Supprimer le repère',
  'terkep.tobbVan': 'il y en a davantage ici — zoome',
  'terkep.keresem': 'recherche…',
  'terkep.nagyits': 'zoome',
  'terkep.hiba': 'échec',
  'terkep.nincsAdat': 'pas de données',

  'reteg.viz': 'Eau potable, source',
  'reteg.menedek': 'Abri',
  'reteg.kozlekedes': 'Arrêt, gare',
  'reteg.parkolo': 'Parking',
  'reteg.kilato': 'Belvédère',
  'reteg.vendeglatas': 'Manger et boire',
  'reteg.latvany': 'Site remarquable',

  'nincs.cim': 'Cette page n’existe pas',
  'nincs.magyarazat': 'Soit tu t’es trompé d’adresse, soit elle pointe vers une page qui n’existe plus.',
  'nincs.lead': 'Tu peux continuer par ici :',
  'nincs.kezdolap': 'Accueil',
  'nincs.tervezo': 'Planificateur d’itinéraires',
  'nincs.tervezoLeiras': 'dessine une randonnée sur la carte',
  'nincs.peldak': 'Itinéraires prêts',
  'nincs.peldakLeiras': 'des exemples à ouvrir',

  'meta.fooldalCim': 'Túrabakancs — itinéraires de randonnée, balisage, avis',
  'meta.fooldalLeiras': 'Carte de planification d’itinéraires, explication du balisage hongrois et avis sans noms.',
  'meta.tervezoCim': 'Planificateur — Túrabakancs',
  'meta.tervezoLeiras': 'Dessine un itinéraire sur la carte, pose des repères, partage-le par un lien.',
  'meta.peldakCim': 'Itinéraires d’exemple — Túrabakancs',
  'meta.peldakLeiras': 'Des itinéraires de randonnée prêts sur la carte, à ouvrir et à redessiner.',
  'meta.impresszumCim': 'À propos et données — Túrabakancs',
  'meta.impresszumLeiras': 'À quoi sert le site et à quoi il ne sert pas. Pas de compte, pas de cookies, pas de mesure ; ce que tu dessines reste dans ton navigateur.',
  'meta.nincsCim': 'Cette page n’existe pas — Túrabakancs',
  'meta.nincsLeiras': 'Cette adresse n’existe pas.',

  /* ---- Nehézség, szűrők, ajánló ---- */
  'nehez.konnyu': 'Facile',
  'nehez.kozepes': 'Moyen',
  'nehez.eros': 'Exigeant',
  'nehez.nehez': 'Difficile',
  'nehez.konnyuLeiras': 'Une courte marche, à la portée de tous.',
  'nehez.kozepesLeiras': 'Une demi-journée, sans condition physique particulière.',
  'nehez.erosLeiras': 'Une randonnée à la journée, prépare-toi.',
  'nehez.nehezLeiras': 'Une longue journée. Seulement avec de l’expérience et du matériel.',
  'szuro.rovid': 'Court',
  'szuro.kozepes': 'Moyen',
  'szuro.hosszu': 'Long',
  'szuro.rovidLeiras': 'moins de 3 km',
  'szuro.kozepesLeiras': '3–8 km',
  'szuro.hosszuLeiras': 'plus de 8 km',
  'tanacs.osszkepCimke': '{nehez} — {ido} de marche',
  'tanacs.osszkepMagassag': '{km} km, {fel} m de dénivelé positif. {leiras} Le temps de marche est sans pauses ; compte au moins une demi-heure de plus.',
  'tanacs.osszkepNincs': '{km} km. {leiras} Le dénivelé est en cours de chargement ; d’ici là, le temps de marche ne tient compte que de la distance.',
  'tanacs.sotetCimke': 'Le soleil est déjà couché',
  'tanacs.sotetSzoveg': 'Le coucher du soleil était à {ido} aujourd’hui. Si tu pars maintenant, n’y va pas sans lampe frontale.',
  'tanacs.sotetedesCimke': 'Tu ne finiras pas avant la nuit',
  'tanacs.sotetedesSzoveg': 'Coucher du soleil à {nyugta}, soit dans {maradek}. L’itinéraire prend {ut}, sans pauses. Prends une frontale ou pars plus tôt.',
  'tanacs.vilagosCimke': '{maradek} avant le coucher du soleil',
  'tanacs.vilagosSzoveg': 'La nuit tombe à {ido} aujourd’hui. Si tu pars maintenant, tu as largement le temps.',
  'tanacs.visszautCimke': 'L’arrivée n’est pas au départ',
  'tanacs.visszautSzoveg': '{tav} km les séparent. Si tu viens en voiture, réfléchis à comment y revenir — ou prévois une boucle.',
  'tanacs.vizCimke': 'Aucun point d’eau indiqué',
  'tanacs.vizSzoveg': 'Pour {km} km, c’est trop peu. Active la couche eau potable : je montre ce qu’il y a autour.',
  'tanacs.megkozelitesCimke': 'Rien n’indique comment rejoindre le départ',
  'tanacs.megkozelitesSzoveg': 'Ce sera la première question avant de partir. La couche des arrêts montre ce qu’il y a autour.',
  'tanacs.durvaCimke': 'Le tracé est très droit',
  'tanacs.durvaSzoveg': 'En moyenne {atlag} km par segment. Un vrai sentier serpente, la distance réelle est donc plus longue — ajoute des points pour affiner.',
  'tanacs.emelkedoCimke': '{fel} mètres de dénivelé positif',
  'tanacs.emelkedoSzoveg': 'Le point le plus bas est à {min} m, le plus haut à {max} m. Ce dénivelé à lui seul ajoute {plusz} au temps de marche.',
  'tanacs.veszelyCimke': 'Tu as marqué une section difficile',
  'tanacs.veszelySzoveg': 'Après la pluie et par temps de gel, les sections raides et rocheuses sont bien plus lentes et risquées. Vérifie la météo avant de partir.',

  /* ---- Időjárás és jelöléstípusok ---- */
  'ido.derult': 'Dégagé',
  'ido.jobbaraDerult': 'Plutôt dégagé',
  'ido.szakadozott': 'Nuages épars',
  'ido.borult': 'Couvert',
  'ido.kod': 'Brouillard',
  'ido.zuzmarasKod': 'Brouillard givrant',
  'ido.gyengeSzitalas': 'Bruine légère',
  'ido.szitalas': 'Bruine',
  'ido.erosSzitalas': 'Bruine forte',
  'ido.gyengeEso': 'Pluie légère',
  'ido.eso': 'Pluie',
  'ido.erosEso': 'Pluie forte',
  'ido.gyengeHavazas': 'Neige légère',
  'ido.havazas': 'Neige',
  'ido.erosHavazas': 'Neige forte',
  'ido.hoszemcsek': 'Neige en grains',
  'ido.zapor': 'Averses',
  'ido.hevesZapor': 'Fortes averses',
  'ido.hozapor': 'Averses de neige',
  'ido.erosHozapor': 'Fortes averses de neige',
  'ido.zivatar': 'Orage',
  'ido.jegesoZivatar': 'Orage avec grêle',
  'ido.hevesJegeso': 'Orage violent avec grêle',
  'ido.ismeretlen': 'Inconnu',
  'idoFigy.zivatar': 'Orages attendus. Une crête ou une tour de guet n’est alors pas un endroit où être.',
  'idoFigy.sokCsapadek': '{mm} mm de précipitations : les passages rocheux et les échelles seront glissants.',
  'idoFigy.eso': 'Pluie attendue — les pentes boueuses ralentiront la progression.',
  'idoFigy.meleg': '{fok} degrés : sur les sections sans ombre, prends deux fois plus d’eau.',
  'idoFigy.fagy': '{fok} degrés à l’aube : le sentier peut être verglacé.',
  'idoFigy.szel': 'Vent de {szel} km/h : désagréable sur la crête, froid dans la tour.',
  'tipus.kilato': 'Belvédère',
  'tipus.forras': 'Source, eau potable',
  'tipus.pihen': 'Aire de repos, banc',
  'tipus.parkolo': 'Parking',
  'tipus.vendeglatas': 'Manger et boire',
  'tipus.latnivalo': 'Site remarquable',
  'tipus.veszely': 'Danger, section difficile',
  'tipus.kozlekedes': 'Arrêt, gare',

  /* ---- Tanácsok, túralista, napnevek ---- */
  'tanacs.lekerem': 'Chargement…',
  'tanacs.milyenIdo': 'Quel temps fera-t-il ?',
  'nap.ma': 'aujourd’hui',
  'nap.holnap': 'demain',
  'turak.lead': 'Je te montre quels {jelzett} passent là où se trouve la carte. Tu peux en charger un et continuer à dessiner.',
  'turak.jelzett': 'sentiers balisés',
  'turak.keresem': 'Recherche…',
  'turak.keres': 'Chercher des sentiers dans cette zone',
  'turak.tolt': 'chargement…',
  'turak.festett': 'Sur le terrain, c’est la marque peinte qui fait foi.',

  /* ---- Impresszum és adatkezelés ---- */
  'imp.cim': 'À propos et données',
  'imp.felelossegCim': 'Responsabilité — à lire avant de partir',
  'imp.felelossegLead': 'Le site affiche des itinéraires, des distances, des dénivelés, des temps de marche et le coucher du soleil. Ce sont des {eros}, pas des garanties :',
  'imp.felelossegEros': 'calculs et estimations',
  'imp.felelosseg1': 'Les tracés suivent les sentiers des données cartographiques. La carte ne peut pas savoir si un sentier est praticable en ce moment — un arbre peut être tombé, la pluie peut l’avoir emporté, il peut être fermé.',
  'imp.felelosseg2': 'Le temps de marche suppose un terrain plat et une allure moyenne. La charge, la neige, la boue, la tombée de la nuit et ta propre forme changent tout.',
  'imp.felelosseg3': 'Le dénivelé provient d’un modèle de terrain, qui peut s’écarter de la réalité de quelques mètres.',
  'imp.felelossegZaro': '{eros} Pour s’orienter, ce sont les sentiers balisés et les cartes officielles qui servent ; vérifie la météo avant de partir et dis à quelqu’un où tu vas. Ce site aide à planifier — il ne remplace pas le bon sens.',
  'imp.felelossegZaroEros': 'Sur le terrain, ce sont ta décision et ta responsabilité qui comptent.',
  'imp.tartalomCim': 'Le contenu',
  'imp.tartalom': 'Les notes en étoiles sont notre avis, pas une moyenne de notes d’autrui. Les données cartographiques viennent d’OpenStreetMap, entretenu par des bénévoles. Les photos des sites sont sous licences libres, avec le nom de leurs auteurs — la liste complète plus bas, sous {link}.',
  'imp.adatCim': 'Données personnelles',
  'imp.adat1': 'Le site ne demande pas de compte, ne collecte pas de données personnelles et n’utilise pas de cookies. Ce que tu dessines naît dans ton navigateur et y reste : tes plans enregistrés vont dans le stockage de ton appareil, et le lien de partage inscrit l’itinéraire dans l’adresse elle-même, pas dans une base de données.',
  'imp.adat2': 'Ce qui part malgré tout sur Internet ne vient pas chez nous. Les tuiles de carte et les réponses de la recherche de lieux viennent des services publics d’OpenStreetMap, les données d’altitude d’Open-Meteo, et le calage des itinéraires sur les sentiers du routeur piéton FOSSGIS. Si tu pointes un site remarquable, sa photo vient de Wikimedia Commons — seulement quand tu le pointes. À ces moments-là — comme pour toute image sur tout site — ton adresse IP leur est visible, et pour le calage et l’altitude, les coordonnées de ton tracé aussi. Nous ne pouvons pas l’éviter si nous voulons montrer une carte ; mais au moins tu le sais.',
  'imp.kepekCim': 'Les images',
  'imp.kepek': 'Les photos des sites viennent de Wikimedia Commons et sont sous licences libres — mais libre ne veut pas dire sans auteur : chacune a un auteur qu’il faut citer. Une image n’est téléchargée que lorsque tu pointes un site, et le nom de l’auteur l’accompagne toujours. La liste ci-dessous couvre les quinze lieux hongrois dont nous hébergeons nous-mêmes les images.',

  /* ---- Alfajták és ivhatóság ---- */
  'fajta.ivoviz': 'Eau potable',
  'fajta.forras': 'Source',
  'fajta.esobeallo': 'Abri',
  'fajta.menedekhaz': 'Refuge',
  'fajta.turistahaz': 'Chalet de montagne',
  'fajta.vasutallomas': 'Gare',
  'fajta.megallohely': 'Halte',
  'fajta.buszmegallo': 'Arrêt de bus',
  'fajta.parkolo': 'Parking',
  'fajta.kilatopont': 'Point de vue',
  'fajta.kilatotorony': 'Tour panoramique',
  'fajta.etterem': 'Restaurant',
  'fajta.kavezo': 'Café',
  'fajta.kocsma': 'Bar',
  'fajta.bufe': 'Restauration rapide',
  'fajta.var': 'Château',
  'fajta.rom': 'Ruines',
  'fajta.regeszeti': 'Site archéologique',
  'fajta.emlekmu': 'Monument',
  'fajta.muzeum': 'Musée',
  'fajta.vizeses': 'Cascade',
  'fajta.barlang': 'Entrée de grotte',
  'fajta.sziklakapu': 'Arche naturelle',
  'fajta.vilagitotorony': 'Phare',
  'fajta.latnivalo': 'Curiosité',
  'viz.ihato': 'potable',
  'viz.nemIhato': 'NON potable',
  'viz.nincsAdat': 'aucune donnée sur sa potabilité',

  /* ---- Hibaüzenetek és apróságok ---- */
  'hiba.utvonalkereso': 'Le calculateur d’itinéraire est indisponible.',
  'hiba.helykereso': 'La recherche de lieux est indisponible.',
  'hiba.helykeresoNema': 'La recherche de lieux ne répond pas.',
  'hiba.haromBetu': 'Saisis au moins trois lettres.',
  'hiba.nincsHely': 'Aucun lieu trouvé pour : « {mit} »',
  'hiba.elorejelzes': 'Les prévisions sont indisponibles.',
  'hiba.homerseklet': 'La température est indisponible.',
  'hiba.magassag': 'Les données d’altitude sont indisponibles.',
  'hiba.osmNema': 'La recherche OpenStreetMap ne répond pas.',
  'hiba.tulterhelt': 'La recherche est surchargée. Réessaie dans quelques secondes.',
  'hiba.terheles': 'La recherche ne suit pas la charge. Réessaie dans quelques secondes.',
  'hiba.keresesNemSikerult': 'La recherche a échoué.',
  'hiba.ismeretlenReteg': 'Couche inconnue.',
  'hiba.nincsHelyzet': 'Ce navigateur ne peut pas déterminer ta position.',
  'gpx.nemTud': 'Ce navigateur ne peut pas lire les fichiers GPX.',
  'gpx.serult': 'Ce fichier n’est pas un GPX lisible — corrompu ou d’un autre format.',
  'gpx.ures': 'Ce fichier ne contient ni trace ni repère.',
  'gpx.nagy': 'Ce fichier dépasse 5 Mo. Une trace aussi grande ne peut pas être affichée correctement.',
  'gpx.nemSikerult': 'Ce fichier n’a pas pu être lu.',
  'terv.ujKezdtel': 'Tu as commencé un nouvel itinéraire — la flèche ramène le précédent.',
  'terv.betoltve': 'Chargé. Déplace ses points ou ajoute des repères.',
  'terv.vagolapon': 'Le lien est dans le presse-papiers — l’itinéraire est dans l’adresse même.',
  'terv.cimsorban': 'Le lien de partage est dans la barre d’adresse du navigateur.',
  'terv.elmentve': 'Enregistré. Sur un autre appareil, retrouve-le avec le lien de partage.',
  'terv.nevtelen': 'Plan sans nom',
  'terv.mentesFrissit': 'Mettre à jour l’enregistrement',
  'terv.mentesBongeszobe': 'Enregistrer dans le navigateur',
  'terkep.cel': 'Arrivée',
  'terkep.kozremukodoi': 'contributeurs',
  'terkep.rajt': 'Départ',
  'terkep.hanyadikPont': 'Point {n}',
  'hh.koordinata': 'coordonnées saisies',
  'nap.ketNapMulva': 'Dans deux jours',
  'turak.jelzettUt': 'sentier balisé',
  'kep.lasdForras': 'voir la source',
  'ut.ketPont': 'Il faut au moins deux points.',
  'ut.nemErheto': 'Le calculateur d’itinéraire est indisponible. Réessaie plus tard.',
  'ut.tulSok': 'Trop de requêtes en peu de temps. Attends un instant.',
  'ut.hibat': 'Le calculateur d’itinéraire a renvoyé une erreur.',
  'ut.nincsGyalogut': 'Je n’ai trouvé aucun sentier entre ces points. Il y a peut-être de l’eau ou une clôture.',
  'ut.nemSikerult': 'Aucun itinéraire n’a pu être trouvé.',
  'ut.tulSokPont': 'Je peux caler au plus {max} points sur les sentiers à la fois. Supprimes-en, ou découpe en sections.',
  'ut.nincsGyalogut2': 'Je n’ai trouvé aucun sentier entre ces points. Le trajet passe peut-être par l’eau ou hors sentier.',
  'terv.egyenesMarad': '{ok} Le tracé reste droit pour l’instant, la distance et le dénivelé sont donc inférieurs à la réalité.',
  'adat.tengerszintUtan': 'd’altitude',

  /* ---- Főoldal: mit tud, kiemelt példa ---- */
  'fooldal.peldaKalap': 'Voilà ce que tu obtiens',
  'fooldal.peldaNyisd': 'Ouvrir dans le planificateur',
  'fooldal.osvenyCim': 'Un sentier, au fil du défilement',
  'fooldal.osvenyLead': 'Ce n’est pas une illustration : l’une des randonnées classiques d’une journée dans les monts Pilis, tracée à partir de ses propres points. Les repères s’allument là où ils se trouvent vraiment.',
  'fooldal.osvenyGomb': 'Voir cette randonnée',
  'fooldal.mitTud': 'Ce que fait cette carte',
  'fooldal.mitTudLead': 'Quatre raisons de planifier ici plutôt que sur une carte généraliste.',
  'fooldal.tud1Cim': 'Le tracé suit de vrais sentiers',
  'fooldal.tud1': 'Pas une ligne droite entre deux points. Marque deux lieux et le tracé se cale sur les sentiers réels — c’est pour ça que la distance et le dénivelé sont justes.',
  'fooldal.tud2Cim': 'Le temps de marche compte la montée',
  'fooldal.tud2': 'Dix kilomètres à plat et dix en montagne, ce n’est pas la même durée. L’estimation ajoute pour chaque centaine de mètres de dénivelé et affiche aussi le profil.',
  'fooldal.tud3Cim': 'Il montre ce qu’il y a autour',
  'fooldal.tud3': 'Sept couches issues d’OpenStreetMap : eau potable, abris, arrêts, parkings, belvédères, restauration, sites remarquables. Dans n’importe quel pays.',
  'fooldal.tud4Cim': 'Ça reste à toi',
  'fooldal.tud4': 'Ce que tu dessines naît dans ton navigateur. Le lien de partage porte l’itinéraire lui-même, pas un identifiant de base — et tu peux le télécharger en GPX, pour n’importe quelle montre ou appli.',
  'adat.menetido': 'temps de marche',
};
