/* Français. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — accueil',
  'fejlec.menuNyit': 'Ouvrir le menu',
  'fejlec.menuZar': 'Fermer le menu',
  'fejlec.foMenu': 'Menu principal',
  'fejlec.sotetMod': 'Basculer le mode sombre',
  'fejlec.fok': 'Actuellement {fok} degrés — {ido}',
  'fejlec.jelenleg': 'Actuellement',

  'menu.fooldal': 'Accueil',
  'menu.fooldalLeiras': 'Balisage, exemples et avis',
  'menu.tervezo': 'Planificateur',
  'menu.tervezoLeiras': 'Saisis deux lieux, ou dessine sur la carte',
  'menu.peldak': 'Exemples',
  'menu.peldakLeiras': 'Des itinéraires prêts pour commencer',

  'lab.terkep': 'La carte est réalisée par les contributeurs d’{osm}, qui fournissent aussi les tuiles.',
  'lab.becsles': 'La distance et le temps de marche sont des estimations — sur le terrain, ce sont les sentiers balisés qui font foi.',
  'lab.impresszum': 'À propos et données',

  'fooldal.cim': 'Túrabakancs — carte de planification de randonnées',
  'fooldal.lead': 'Une carte sur laquelle dessiner. Des randonnées prêtes pour commencer. Un temps de marche qui tient compte du dénivelé.',
  'fooldal.tervezek': 'Je planifie une randonnée',
  'fooldal.peldak': 'Je regarde des exemples',
  'fooldal.ma': 'Aujourd’hui',
  'fooldal.napkelte': 'lever du soleil',
  'fooldal.napnyugta': 'coucher du soleil',
  'fooldal.vilagosMeg': 'de jour restant',
  'fooldal.lement': 'couché',
  'fooldal.vanMeg': 'encore clair',
  'fooldal.marLement': 'le soleil est couché',
  'fooldal.napAlap': 'Pour Budapest. Le planificateur calcule à partir du départ de ton propre itinéraire.',
  'fooldal.jelzesCim': 'Que veut dire la peinture sur l’arbre ?',
  'fooldal.jelzesLead': 'Un balisage hongrois dit deux choses à la fois. La couleur indique l’importance de l’itinéraire, la forme indique à quoi il sert.',
  'fooldal.jelzesSzin': 'couleur',
  'fooldal.jelzesAlak': 'forme',
  'fooldal.jelzesApro': 'Nous ne l’avons pas écrit de mémoire : nous avons vérifié sur les sentiers balisés d’OpenStreetMap ce qui mène où. Les itinéraires marqués d’un triangle se terminent à un sommet ou à un belvédère, ceux marqués d’un cercle reviennent à leur point de départ.',
  'fooldal.keszVonal': 'Commence par un itinéraire prêt',
  'fooldal.keszVonalLead': 'Ouvre-le, déplace ses points, fais-en le tien.',
  'fooldal.szerintunk': 'selon nous',
  'fooldal.osszesPelda': 'Tous les exemples →',

  'peldak.kicsi': 'Exemples',
  'peldak.cim': 'Des itinéraires prêts pour commencer.',
  'peldak.bevezeto': 'Ouvre n’importe lequel, déplace ses points, ajoute tes propres repères — et il est à toi.',
  'peldak.tajegyseg': 'Région',
  'peldak.mindegyik': 'Tous',
  'peldak.hossz': 'Longueur',
  'peldak.nehezseg': 'Difficulté',
  'peldak.torold': 'tout effacer',
  'peldak.szurokTorol': 'effacer les filtres',
  'peldak.utvonal': 'itinéraires',
  'peldak.megnezem': 'Voir',
  'peldak.gyalogut': 'Les tracés suivent de vrais sentiers',
  'peldak.gyalogutUtan': ', pas en ligne droite entre deux points — c’est pourquoi la distance et le dénivelé sont justes. Sur le terrain, ce sont malgré tout les sentiers balisés et les cartes officielles qui font foi.',
  'peldak.darab': '{db} itinéraires',

  'utvonal.nincs': 'Cet itinéraire n’existe pas.',
  'utvonal.tobbi': 'Voici les autres exemples.',
  'utvonal.hossz': 'Longueur',
  'utvonal.sik': 'Calculé pour un terrain plat ; davantage en montée.',
  'utvonal.jelolesek': 'Repères',
  'utvonal.kozelito': 'Tracé approximatif, pas un sentier relevé.',
  'utvonal.megnyitas': 'Ouvrir dans le planificateur',
  'utvonal.gpx': 'Télécharger le GPX',

  'tervezo.honnanHova': 'D’où à où ?',
  'tervezo.adatok': 'Données de l’itinéraire',
  'tervezo.adatokCimke': 'Données de l’itinéraire — {km}, {ido}',
  'tervezo.eszkozok': 'Enregistrer, itinéraires prêts, GPX',
  'tervezo.vissza': 'Un pas en arrière',
  'tervezo.retegek': 'Ce que la carte doit montrer',
  'tervezo.ujraKeres': 'Chercher dans cette zone',

  'hh.honnan': 'De',
  'hh.hova': 'À — si tu laisses vide, on s’y rend simplement',
  'hh.honnanHely': 'Nom du lieu ou coordonnées',
  'hh.hovaHely': 'Par exemple : Mont Blanc',
  'hh.innen': 'Je pars d’ici',
  'hh.odaugras': 'Aller là-bas',
  'hh.szamolom': 'Calcul…',
  'hh.utvonalat': 'Calculer l’itinéraire',
  'hh.keres': 'Recherche…',
  'hh.nincsHelyzet': 'Je n’ai pas pu obtenir ta position. Saisis le point de départ à la main.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'longueur',
  'adat.emelkedo': 'dénivelé positif',
  'adat.lejto': 'dénivelé négatif',
  'adat.nehezseg': 'difficulté',
  'adat.tempo': 'Allure',
  'adat.tengerszint': '{also}–{felso} m d’altitude',
  'adat.nev': 'Par exemple : boucle du dimanche',

  'terkep.igazit': 'J’aligne le tracé sur de vrais sentiers…',
  'terkep.masodik': 'Pose le deuxième point — le tracé se cale tout seul sur le sentier.',
  'terkep.keszUt': 'Itinéraire prêt. Touche la carte pour en commencer un nouveau.',
  'terkep.sug': 'Touche la carte pour poser des points. Les points se déplacent ; une touche les supprime.',
  'terkep.keszVonal': 'Voilà — le tracé suit de vrais sentiers.',
  'terkep.jelolesTorol': 'Supprimer le repère',
  'terkep.tobbVan': 'il y en a davantage ici — zoome',
  'terkep.keresem': 'recherche…',
  'terkep.nagyits': 'zoome',
  'terkep.hiba': 'échec',
  'terkep.nincsAdat': 'pas de données',

  'reteg.viz': 'Eau potable, source',
  'reteg.menedek': 'Abri',
  'reteg.kozlekedes': 'Arrêt, gare',
  'reteg.parkolo': 'Parking',
  'reteg.kilato': 'Belvédère',
  'reteg.vendeglatas': 'Manger et boire',
  'reteg.latvany': 'Site remarquable',

  'nincs.cim': 'Cette page n’existe pas',
  'nincs.magyarazat': 'Soit tu t’es trompé d’adresse, soit elle pointe vers une page qui n’existe plus.',
  'nincs.lead': 'Tu peux continuer par ici :',
  'nincs.kezdolap': 'Accueil',
  'nincs.tervezo': 'Planificateur d’itinéraires',
  'nincs.tervezoLeiras': 'dessine une randonnée sur la carte',
  'nincs.peldak': 'Itinéraires prêts',
  'nincs.peldakLeiras': 'des exemples à ouvrir',

  'meta.fooldalCim': 'Túrabakancs — itinéraires de randonnée, balisage, avis',
  'meta.fooldalLeiras': 'Carte de planification d’itinéraires, explication du balisage hongrois et avis sans noms.',
  'meta.tervezoCim': 'Planificateur — Túrabakancs',
  'meta.tervezoLeiras': 'Dessine un itinéraire sur la carte, pose des repères, partage-le par un lien.',
  'meta.peldakCim': 'Itinéraires d’exemple — Túrabakancs',
  'meta.peldakLeiras': 'Des itinéraires de randonnée prêts sur la carte, à ouvrir et à redessiner.',
  'meta.impresszumCim': 'À propos et données — Túrabakancs',
  'meta.impresszumLeiras': 'À quoi sert le site et à quoi il ne sert pas. Pas de compte, pas de cookies, pas de mesure ; ce que tu dessines reste dans ton navigateur.',
  'meta.nincsCim': 'Cette page n’existe pas — Túrabakancs',
  'meta.nincsLeiras': 'Cette adresse n’existe pas.',
};
