/* Magyar — ez a forrásnyelv.

   Minden más nyelv ennek a kulcsaira felel. Ha itt új kulcs kerül be, a
   többi fájlban is meg kell jelennie; a hiányzót a `nyelv/index.js`
   magyarral pótolja, hogy soha ne üres doboz legyen a felületen.

   A kapcsos zárójeles helyek ({km}, {perc}) behelyettesítődnek. A
   sorrendjük nyelvenként más lehet — ezért nevesítettek, nem sorszámozottak. */

export default {
  /* ---- Fejléc, menü ---- */
  'fejlec.kezdolap': 'Túrabakancs — kezdőlap',
  'fejlec.menuNyit': 'Menü megnyitása',
  'fejlec.menuZar': 'Menü bezárása',
  'fejlec.foMenu': 'Fő menü',
  'fejlec.sotetMod': 'Sötét mód váltása',
  'fejlec.fok': 'Most {fok} fok — {ido}',
  'fejlec.jelenleg': 'Jelenleg',

  'menu.fooldal': 'Főoldal',
  'menu.fooldalLeiras': 'Jelzések, példák és vélemények',
  'menu.tervezo': 'Tervező',
  'menu.tervezoLeiras': 'Írd be a két helyet, vagy rajzolj a térképre',
  'menu.peldak': 'Példák',
  'menu.peldakLeiras': 'Kész vonalak, amikből kiindulhatsz',

  /* ---- Lábjegyzet ---- */
  'lab.terkep': 'A térképet az {osm} közreműködői készítik, és ők is adják hozzá a csempéket.',
  'lab.becsles': 'A távolság és a menetidő becslés — a terepen a jelzett turistautak a mérvadók.',
  'lab.impresszum': 'Impresszum és adatkezelés',

  /* ---- Főoldal ---- */
  'fooldal.cim': 'Túrabakancs — túraútvonal-tervező térkép',
  'fooldal.lead': 'Térkép, amire rajzolhatsz. Kész túrák, amikből kiindulhatsz. Menetidő, ami az emelkedővel is számol.',
  'fooldal.tervezek': 'Tervezek egy túrát',
  'fooldal.peldak': 'Nézek példákat',
  'fooldal.ma': 'Ma',
  'fooldal.napkelte': 'napkelte',
  'fooldal.napnyugta': 'napnyugta',
  'fooldal.vilagosMeg': 'világos még',
  'fooldal.lement': 'lement',
  'fooldal.vanMeg': 'világos van még',
  'fooldal.marLement': 'a nap már lement',
  'fooldal.napAlap': 'Budapestre. A tervező a saját útvonalad kezdőpontjára számol.',
  'fooldal.jelzesCim': 'Mit jelent a festék a fán?',
  'fooldal.jelzesLead': 'A magyar turistajelzés két dolgot mond meg egyszerre. A szín azt, mekkora út, az alak pedig azt, mire való.',
  'fooldal.jelzesSzin': 'szín',
  'fooldal.jelzesAlak': 'alak',
  'fooldal.jelzesApro': 'Ezt nem fejből írtuk: az OpenStreetMap jelzett útjaiból ellenőriztük, mi hova vezet. A háromszöggel jelöltek neve csúcsnál vagy kilátónál végződik, a körrel jelöltek ugyanoda érnek vissza, ahonnan indultak.',
  'fooldal.keszVonal': 'Kezdd egy kész vonallal',
  'fooldal.keszVonalLead': 'Nyisd meg, húzd arrébb a pontjait, tedd rá a sajátodat.',
  'fooldal.szerintunk': 'szerintünk',
  'fooldal.osszesPelda': 'Az összes példa →',

  /* ---- Példák oldal ---- */
  'peldak.kicsi': 'Példák',
  'peldak.cim': 'Kész vonalak, amikből kiindulhatsz.',
  'peldak.bevezeto': 'Nyisd meg bármelyiket, húzd arrébb a pontjait, tegyél rá saját jelöléseket — és már a tiéd.',
  'peldak.tajegyseg': 'Tájegység',
  'peldak.mindegyik': 'Mindegyik',
  'peldak.hossz': 'Hossz',
  'peldak.nehezseg': 'Nehézség',
  'peldak.torold': 'töröld mindet',
  'peldak.szurokTorol': 'szűrők törlése',
  'peldak.utvonal': 'útvonal',
  'peldak.megnezem': 'Megnézem',
  'peldak.gyalogut': 'A vonalak a tényleges gyalogutakon futnak',
  'peldak.gyalogutUtan': ', nem két pont közé húzott egyenesen — a táv és az emelkedő ezért igaz. A terepen ettől még a jelzett turistautak és a hivatalos térképek a mérvadók.',
  'peldak.darab': '{db} vonal',

  /* ---- Egy útvonal oldala ---- */
  'utvonal.nincs': 'Ez az útvonal nincs meg.',
  'utvonal.tobbi': 'Itt a többi példa.',
  'tempo.gyalog': 'Gyalog',
  'tempo.futas': 'Futás',
  'tempo.bringa': 'Kerékpár',
  'utvonal.elgepelt': 'Lehet, hogy elgépelted a címet.',
  'utvonal.kozelitoUtan': ' A terepen a jelzett turistautak és a hivatalos térképek a mérvadók.',
  'utvonal.hossz': 'Hossz',
  'utvonal.sik': 'Sík terepre számolva; emelkedőn több.',
  'utvonal.jelolesek': 'Jelölések',
  'utvonal.kozelito': 'Hozzávetőleges vonalvezetés, nem felmért turistaút.',
  'utvonal.megnyitas': 'Megnyitás a tervezőben',
  'utvonal.gpx': 'GPX letöltése',

  /* ---- Tervező: eszközrúd ---- */
  'tervezo.honnanHova': 'Honnan hova?',
  'tervezo.adatok': 'Az útvonal adatai',
  'tervezo.adatokCimke': 'Az útvonal adatai — {km}, {ido}',
  'tervezo.eszkozok': 'Mentés, kész útvonalak, GPX',
  'tervezo.vissza': 'Egy lépés vissza',
  'tervezo.retegek': 'Mit mutasson a térkép',
  'tervezo.ujraKeres': 'Keresés ezen a területen',

  /* ---- Tervező: honnan hova ---- */
  'hh.honnan': 'Honnan',
  'hh.hova': 'Hova — ha üresen hagyod, csak odaugrunk',
  'hh.honnanHely': 'Hely neve vagy koordináta',
  'hh.hovaHely': 'Például: Dobogókő',
  'hh.innen': 'Innen indulok',
  'hh.odaugras': 'Odaugrás',
  'hh.szamolom': 'Számolom…',
  'hh.utvonalat': 'Útvonalat kérek',
  'hh.keres': 'Keresem…',
  'hh.nincsHelyzet': 'Nem kaptam meg a helyzetedet. Írd be a kiindulópontot kézzel.',

  /* ---- Tervező: adatok ---- */
  'ido.perc': '{p} perc',
  'ido.oraPerc': '{o} óra {p} perc',
  'ido.rovidPerc': '{p} perc',
  'ido.rovidOra': '{o} ó {p} p',
  'adat.hossz': 'hossz',
  'adat.emelkedo': 'emelkedő',
  'adat.lejto': 'lejtő',
  'adat.nehezseg': 'nehézség',
  'adat.tempo': 'Haladási tempó',
  'adat.tengerszint': '{also}–{felso} m tengerszint felett',
  'adat.nev': 'Például: vasárnapi kör',

  /* ---- Tervező: térkép ---- */
  'terkep.igazit': 'Ráigazítom a vonalat a valódi gyalogutakra…',
  'terkep.masodik': 'Jelöld be a második pontot — a vonal magától az ösvényre kerül.',
  'terkep.keszUt': 'Kész útvonal. Érints a térképre, ha újat kezdenél.',
  'terkep.sug': 'Érintsd a térképet a pontokért. A pontok húzhatók; rájuk koppintva törlődnek.',
  'terkep.keszVonal': 'Kész — a vonal a tényleges gyalogutakon fut.',
  'jeloles.ugras': 'Ugrás ide: {nev}',
  'jeloles.neve': '{tipus} neve',
  'terkep.jelolesTorol': 'Jelölés törlése',
  'terkep.tobbVan': 'ennél több van itt — nagyíts rá',
  'terkep.keresem': 'keresem…',
  'terkep.nagyits': 'nagyíts rá',
  'terkep.hiba': 'nem sikerült',
  'terkep.nincsAdat': 'nincs adat',

  /* ---- Rétegek ---- */
  'reteg.viz': 'Ivóvíz, forrás',
  'reteg.menedek': 'Menedék, esőbeálló',
  'reteg.kozlekedes': 'Megálló, állomás',
  'reteg.parkolo': 'Parkoló',
  'reteg.kilato': 'Kilátó',
  'reteg.vendeglatas': 'Büfé, kocsma',
  'reteg.latvany': 'Látványosság',

  /* ---- Nincs ilyen oldal ---- */
  'nincs.cim': 'Nincs ilyen oldal',
  'nincs.magyarazat': 'Vagy elgépelted a címet, vagy olyan oldalra mutat, ami már nincs meg.',
  'nincs.lead': 'Innen tudsz továbbmenni:',
  'nincs.kezdolap': 'Kezdőlap',
  'nincs.tervezo': 'Útvonaltervező',
  'nincs.tervezoLeiras': 'rajzolj egy túrát a térképre',
  'nincs.peldak': 'Kész útvonalak',
  'nincs.peldakLeiras': 'példák, amiket megnyithatsz',

  /* ---- Oldalcímek és leírások (a lap fejlécében, keresőben) ---- */
  'meta.fooldalCim': 'Túrabakancs — túraútvonalak, jelzések, vélemények',
  'meta.fooldalLeiras': 'Útvonaltervező térkép, a magyar turistajelzések magyarázata és név nélküli vélemények.',
  'meta.tervezoCim': 'Tervező — Túrabakancs',
  'meta.tervezoLeiras': 'Rajzolj útvonalat a térképre, tegyél ki jelöléseket, oszd meg egy linkkel.',
  'meta.peldakCim': 'Példa útvonalak — Túrabakancs',
  'meta.peldakLeiras': 'Kész túraútvonalak a térképen, amiket megnyithatsz és továbbrajzolhatsz.',
  'meta.impresszumCim': 'Impresszum és adatkezelés — Túrabakancs',
  'meta.impresszumLeiras': 'Mire jó az oldal és mire nem. Nincs fiók, nincs süti, nincs mérőkód; amit rajzolsz, a böngésződben marad.',
  'meta.nincsCim': 'Nincs ilyen oldal — Túrabakancs',
  'meta.nincsLeiras': 'Ez a cím nem létezik.',

  /* ---- Nehézség, szűrők, ajánló ---- */
  'nehez.konnyu': 'Könnyű',
  'nehez.kozepes': 'Közepes',
  'nehez.eros': 'Erős',
  'nehez.nehez': 'Nehéz',
  'nehez.konnyuLeiras': 'Rövid séta, bárkinek megy.',
  'nehez.kozepesLeiras': 'Fél nap, edzettség nem kell hozzá.',
  'nehez.erosLeiras': 'Egész napos túra, készülj rá.',
  'nehez.nehezLeiras': 'Hosszú nap. Csak gyakorlattal és felszereléssel.',
  'szuro.rovid': 'Rövid',
  'szuro.kozepes': 'Közepes',
  'szuro.hosszu': 'Hosszú',
  'szuro.rovidLeiras': '3 km alatt',
  'szuro.kozepesLeiras': '3–8 km',
  'szuro.hosszuLeiras': '8 km fölött',
  'tanacs.osszkepCimke': '{nehez} — {ido} menetidő',
  'tanacs.osszkepMagassag': '{km} km, {fel} m emelkedő. {leiras} A menetidő pihenők nélkül értendő; számolj még legalább fél órát.',
  'tanacs.osszkepNincs': '{km} km. {leiras} Az emelkedőt még töltöm; addig a menetidő csak a távból számol.',
  'tanacs.sotetCimke': 'Már lement a nap',
  'tanacs.sotetSzoveg': 'Ma {ido}-kor volt a napnyugta. Ha most indulsz, fejlámpa nélkül ne vágj neki.',
  'tanacs.sotetedesCimke': 'Nem éred be sötétedés előtt',
  'tanacs.sotetedesSzoveg': 'Napnyugta {nyugta}-kor, addig {maradek} van. Az út {ut}, pihenők nélkül. Vigyél fejlámpát, vagy indulj korábban.',
  'tanacs.vilagosCimke': 'Napnyugtáig {maradek}',
  'tanacs.vilagosSzoveg': 'Ma {ido}-kor sötétedik. Ha most indulsz, bőven beéred.',
  'tanacs.visszautCimke': 'A cél nem ott van, ahol a rajt',
  'tanacs.visszautSzoveg': '{tav} km választja el őket. Ha autóval mész, gondold végig, hogyan jutsz vissza érte — vagy tervezz kört.',
  'tanacs.vizCimke': 'Nincs vízvételi hely jelölve',
  'tanacs.vizSzoveg': '{km} km-hez ez kevés. Kapcsold be a térkép ivóvíz-gombját: megmutatom, mi van a környéken.',
  'tanacs.megkozelitesCimke': 'Nincs jelölve, hogyan jutsz a rajthoz',
  'tanacs.megkozelitesSzoveg': 'Indulás előtt ez lesz az első kérdés. A térkép megálló-gombjával megnézheted, mi van a környéken.',
  'tanacs.durvaCimke': 'A vonal nagyon egyenes',
  'tanacs.durvaSzoveg': 'Szakaszonként átlag {atlag} km. A valódi ösvény kanyarog, tehát a tényleges táv ennél hosszabb — kattints be több pontot a pontosabb képhez.',
  'tanacs.emelkedoCimke': '{fel} méter emelkedő',
  'tanacs.emelkedoSzoveg': 'A legalacsonyabb pont {min} m, a legmagasabb {max} m. Ez az emelkedő önmagában {plusz}-cel hosszabbítja a menetidőt.',
  'tanacs.veszelyCimke': 'Nehéz szakaszt jelöltél be',
  'tanacs.veszelySzoveg': 'Eső után és fagyban a meredek, sziklás részek jóval lassabbak és kockázatosabbak. Nézd meg az időjárást indulás előtt.',

  /* ---- Időjárás és jelöléstípusok ---- */
  'ido.derult': 'Derült',
  'ido.jobbaraDerult': 'Jobbára derült',
  'ido.szakadozott': 'Szakadozott felhőzet',
  'ido.borult': 'Borult',
  'ido.kod': 'Köd',
  'ido.zuzmarasKod': 'Zúzmarás köd',
  'ido.gyengeSzitalas': 'Gyenge szitálás',
  'ido.szitalas': 'Szitálás',
  'ido.erosSzitalas': 'Erős szitálás',
  'ido.gyengeEso': 'Gyenge eső',
  'ido.eso': 'Eső',
  'ido.erosEso': 'Erős eső',
  'ido.gyengeHavazas': 'Gyenge havazás',
  'ido.havazas': 'Havazás',
  'ido.erosHavazas': 'Erős havazás',
  'ido.hoszemcsek': 'Hószemcsék',
  'ido.zapor': 'Zápor',
  'ido.hevesZapor': 'Heves zápor',
  'ido.hozapor': 'Hózápor',
  'ido.erosHozapor': 'Erős hózápor',
  'ido.zivatar': 'Zivatar',
  'ido.jegesoZivatar': 'Jégesős zivatar',
  'ido.hevesJegeso': 'Heves jégesős zivatar',
  'ido.ismeretlen': 'Ismeretlen',
  'idoFigy.zivatar': 'Zivatar várható. Gerincen és kilátóban ilyenkor nincs keresnivalód.',
  'idoFigy.sokCsapadek': '{mm} mm csapadék: a sziklás és létrás szakaszok csúsznak.',
  'idoFigy.eso': 'Eső várható — a sáros lejtőkön lassabb lesz a haladás.',
  'idoFigy.meleg': '{fok} fok: árnyék nélküli szakaszon vigyél dupla vizet.',
  'idoFigy.fagy': 'Hajnalban {fok} fok: jeges lehet a nyomvonal.',
  'idoFigy.szel': '{szel} km/h szél: gerincen kellemetlen, kilátóban hideg.',
  'tipus.kilato': 'Kilátó',
  'tipus.forras': 'Forrás, ivóvíz',
  'tipus.pihen': 'Pihenő, pad',
  'tipus.parkolo': 'Parkoló',
  'tipus.vendeglatas': 'Büfé, kocsma',
  'tipus.latnivalo': 'Látnivaló',
  'tipus.veszely': 'Veszély, nehéz szakasz',
  'tipus.kozlekedes': 'Megálló, állomás',

  /* ---- Tanácsok, túralista, napnevek ---- */
  'tanacs.lekerem': 'Lekérem…',
  'tanacs.milyenIdo': 'Milyen idő lesz?',
  'nap.ma': 'ma',
  'nap.holnap': 'holnap',
  'turak.lead': 'Megmutatom, milyen {jelzett} fut ott, ahol épp a térkép áll. Bármelyiket betöltheted és továbbrajzolhatod.',
  'turak.jelzett': 'jelzett turistaút',
  'turak.keresem': 'Keresem…',
  'turak.keres': 'Utak keresése ezen a területen',
  'turak.tolt': 'töltöm…',
  'turak.festett': 'A terepen a festett jelzés a mérvadó.',

  /* ---- Impresszum és adatkezelés ---- */
  'imp.cim': 'Impresszum és adatkezelés',
  'imp.felelossegCim': 'Felelősség — ezt olvasd el, ha túrázni indulsz',
  'imp.felelossegLead': 'Az oldal útvonalakat, távolságokat, emelkedőket, menetidőt és napnyugtát mutat. Ezek {eros}, nem garanciák:',
  'imp.felelossegEros': 'számítások és becslések',
  'imp.felelosseg1': 'A vonalak a térképadatból származó gyalogutakat követik. Hogy az adott ösvény most járható-e, azt a térkép nem tudja — fa dőlhet rá, elmoshatja az eső, lezárhatják.',
  'imp.felelosseg2': 'A menetidő sík terepre és átlagos tempóra számol. Terhelés, hó, sár, sötétedés és a saját erőnléted mind felülírja.',
  'imp.felelosseg3': 'Az emelkedő domborzatmodellből jön, ami néhány méterrel eltérhet a valóságtól.',
  'imp.felelossegZaro': '{eros} Tájékozódásra a jelzett turistautak és a hivatalos térképek valók; indulás előtt nézd meg az időjárást, és mondd meg valakinek, hova mész. Ez az oldal segít tervezni — nem helyettesíti a józan észt.',
  'imp.felelossegZaroEros': 'A terepen a saját döntésed és felelősséged számít.',
  'imp.tartalomCim': 'A tartalom',
  'imp.tartalom': 'A csillagos értékelések a mi véleményünk, nem mások pontszámainak átlaga. A térképadat az OpenStreetMapből jön, amit önkéntesek tartanak karban. A látványosságok fotói szabad licenc alatt állnak, a szerzőik nevével együtt — a teljes jegyzék lent, {link} alatt.',
  'imp.adatCim': 'Adatkezelés',
  'imp.adat1': 'Az oldal nem kér fiókot, nem gyűjt személyes adatot, és nem használ sütiket. Amit rajzolsz, a böngésződben keletkezik, és ott is marad: a mentett terveid a saját géped tárolójába kerülnek, a megosztható link pedig magába a címbe teszi az útvonalat, nem egy adatbázisba.',
  'imp.adat2': 'Ami mégis kimegy az internetre, az nem hozzánk megy. A térképcsempéket és a helykeresés válaszát az OpenStreetMap nyilvános szolgáltatásai adják, a magassági adatot az Open-Meteo, az útvonalak ösvényre húzását pedig a FOSSGIS gyalogos útvonalkeresője. Ha egy látványosságra mutatsz, a képét a Wikimedia Commons adja — csak akkor, amikor rámutatsz. Ilyenkor — mint minden weboldal minden képénél — látszik feléjük az IP-címed, a húzásnál és a magasságnál pedig a vonalad koordinátái is. Ezt nem tudjuk megkerülni, ha térképet akarunk mutatni; de legalább tudsz róla.',
  'imp.kepekCim': 'A képek',
  'imp.kepek': 'A látványosságok fotói a Wikimedia Commonsról valók, és szabad licenc alatt állnak — de a szabad nem azt jelenti, hogy gazdátlan: mindegyiknek van szerzője, akit meg kell nevezni. A kép csak akkor töltődik le, amikor rámutatsz egy látványosságra, és a szerző neve mindig ott van mellette. Az alábbi lista azt a tizenöt magyar helyet sorolja fel, amelyeknek a képét saját oldalunkra töltöttük le.',

  /* ---- Alfajták és ivhatóság ---- */
  'fajta.ivoviz': 'Ivóvíz',
  'fajta.forras': 'Forrás',
  'fajta.esobeallo': 'Esőbeálló',
  'fajta.menedekhaz': 'Menedékház',
  'fajta.turistahaz': 'Turistaház',
  'fajta.vasutallomas': 'Vasútállomás',
  'fajta.megallohely': 'Megállóhely',
  'fajta.buszmegallo': 'Buszmegálló',
  'fajta.parkolo': 'Parkoló',
  'fajta.kilatopont': 'Kilátópont',
  'fajta.kilatotorony': 'Kilátótorony',
  'fajta.etterem': 'Étterem',
  'fajta.kavezo': 'Kávézó',
  'fajta.kocsma': 'Kocsma',
  'fajta.bufe': 'Büfé',
  'fajta.var': 'Vár, kastély',
  'fajta.rom': 'Rom',
  'fajta.regeszeti': 'Régészeti lelőhely',
  'fajta.emlekmu': 'Emlékmű',
  'fajta.muzeum': 'Múzeum',
  'fajta.vizeses': 'Vízesés',
  'fajta.barlang': 'Barlangbejárat',
  'fajta.sziklakapu': 'Sziklakapu',
  'fajta.vilagitotorony': 'Világítótorony',
  'fajta.latnivalo': 'Látnivaló',
  'viz.ihato': 'iható',
  'viz.nemIhato': 'NEM iható',
  'viz.nincsAdat': 'nincs adat róla, hogy iható-e',

  /* ---- Hibaüzenetek és apróságok ---- */
  'hiba.utvonalkereso': 'Az útvonalkereső most nem érhető el.',
  'hiba.helykereso': 'A helykereső most nem érhető el.',
  'hiba.helykeresoNema': 'A helykereső most nem válaszol.',
  'hiba.haromBetu': 'Írj be legalább három betűt.',
  'hiba.nincsHely': 'Erre nem találtam helyet: „{mit}”',
  'hiba.elorejelzes': 'Az előrejelzés most nem érhető el.',
  'hiba.homerseklet': 'A hőmérséklet most nem érhető el.',
  'hiba.magassag': 'A magassági adat most nem érhető el.',
  'hiba.osmNema': 'Az OpenStreetMap keresője most nem válaszol.',
  'hiba.tulterhelt': 'A kereső most túlterhelt. Próbáld pár másodperc múlva.',
  'hiba.terheles': 'A kereső most nem bírja a terhelést. Próbáld pár másodperc múlva.',
  'hiba.keresesNemSikerult': 'A keresés nem sikerült.',
  'hiba.ismeretlenReteg': 'Ismeretlen réteg.',
  'hiba.nincsHelyzet': 'Ez a böngésző nem tudja megmondani a helyzetedet.',
  'gpx.nemTud': 'Ez a böngésző nem tud GPX-et beolvasni.',
  'gpx.serult': 'Ez a fájl nem olvasható GPX — sérült vagy más formátum.',
  'gpx.ures': 'Ebben a fájlban nincs sem nyomvonal, sem jelölés.',
  'gpx.nagy': 'Ez a fájl 5 MB-nál nagyobb. Ekkora nyomvonalat nem tudok értelmesen megjeleníteni.',
  'gpx.nemSikerult': 'Ezt a fájlt nem sikerült beolvasni.',
  'terv.ujKezdtel': 'Új útvonalat kezdtél — a nyíllal visszakapod az előzőt.',
  'terv.betoltve': 'Betöltve. Húzd arrébb a pontjait, vagy tegyél rá jelöléseket.',
  'terv.vagolapon': 'A link a vágólapon — az útvonal magában a címben van.',
  'terv.cimsorban': 'A böngésző címsorában ott a megosztható link.',
  'terv.elmentve': 'Elmentve. Másik gépen a megosztható linkkel éred el.',
  'terv.nevtelen': 'Névtelen terv',
  'terv.mentesFrissit': 'Mentés frissítése',
  'terv.mentesBongeszobe': 'Mentés a böngészőbe',
  'terkep.cel': 'Cél',
  'terkep.kozremukodoi': 'közreműködői',
  'terkep.rajt': 'Rajt',
  'terkep.hanyadikPont': '{n}. pont',
  'hh.koordinata': 'megadott koordináta',
  'nap.ketNapMulva': 'Két nap múlva',
  'turak.jelzettUt': 'jelzett út',
  'kep.lasdForras': 'lásd a forrásnál',
  'ut.ketPont': 'Legalább két pont kell hozzá.',
  'ut.nemErheto': 'Az útvonalkereső most nem érhető el. Próbáld később.',
  'ut.tulSok': 'Túl sok kérés ment ki rövid idő alatt. Várj egy kicsit.',
  'ut.hibat': 'Az útvonalkereső hibát adott.',
  'ut.nincsGyalogut': 'Ezek közt a pontok közt nem találtam gyalogutat. Lehet, hogy víz vagy kerítés van közte.',
  'ut.nemSikerult': 'Nem sikerült útvonalat találni.',
  'ut.tulSokPont': 'Egyszerre legfeljebb {max} pontot tudok ösvényre húzni. Törölj néhányat, vagy darabold szakaszokra.',
  'ut.nincsGyalogut2': 'Ezek közt a pontok közt nem találtam gyalogutat. Lehet, hogy vízen vagy úttalan területen visz át.',
  'terv.egyenesMarad': '{ok} A vonal addig egyenes marad, a táv és az emelkedő ezért kevesebb a valóságosnál.',
  'adat.tengerszintUtan': 'tengerszint felett',

  /* ---- Főoldal: mit tud, kiemelt példa ---- */
  'fooldal.peldaKalap': 'Így néz ki, amit kapsz',
  'fooldal.peldaNyisd': 'Nyisd meg a tervezőben',
  'fooldal.mitTud': 'Mit tud ez a térkép',
  'fooldal.mitTudLead': 'Négy dolog, amiért érdemesebb itt tervezni, mint egy általános térképen.',
  'fooldal.tud1Cim': 'A vonal a gyalogutakon fut',
  'fooldal.tud1': 'Nem két pont közé húzott egyenes. Ha bejelölsz két helyet, a nyomvonal magától ráigazodik a tényleges ösvényekre — ezért igaz a táv és az emelkedő.',
  'fooldal.tud2Cim': 'A menetidő az emelkedővel számol',
  'fooldal.tud2': 'Tíz kilométer sík terepen és tíz kilométer hegyen nem ugyanannyi idő. A becslés minden száz méter emelkedőt hozzáad, és megmutatja a magassági profilt is.',
  'fooldal.tud3Cim': 'Megmutatja, mi van a környéken',
  'fooldal.tud3': 'Hét réteg az OpenStreetMapből: ivóvíz, menedék, megálló, parkoló, kilátó, vendéglátás, látványosság. A világ bármelyik országában, nem csak itthon.',
  'fooldal.tud4Cim': 'A tiéd marad',
  'fooldal.tud4': 'Amit rajzolsz, a böngésződben keletkezik. A megosztható link magát az útvonalat viszi, nem egy adatbázis-azonosítót — és GPX-ben is letöltheted, bármelyik órára vagy alkalmazásba.',
  'adat.menetido': 'menetidő',
};
