/* Polski. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — strona główna',
  'fejlec.menuNyit': 'Otwórz menu',
  'fejlec.menuZar': 'Zamknij menu',
  'fejlec.foMenu': 'Menu główne',
  'fejlec.sotetMod': 'Przełącz tryb ciemny',
  'fejlec.fok': 'Teraz {fok} stopni — {ido}',
  'fejlec.jelenleg': 'Obecnie',

  'menu.fooldal': 'Strona główna',
  'menu.fooldalLeiras': 'Znaki szlaków, przykłady i opinie',
  'menu.tervezo': 'Planer',
  'menu.tervezoLeiras': 'Wpisz dwa miejsca albo rysuj na mapie',
  'menu.peldak': 'Przykłady',
  'menu.peldakLeiras': 'Gotowe trasy na początek',

  'lab.terkep': 'Mapę tworzą współtwórcy {osm}, którzy dostarczają też kafelki.',
  'lab.becsles': 'Odległość i czas przejścia to szacunki — w terenie liczą się oznakowane szlaki.',
  'lab.impresszum': 'O stronie i prywatność',

  'fooldal.cim': 'Túrabakancs — mapa do planowania tras pieszych',
  'fooldal.lead': 'Mapa, po której można rysować. Gotowe wycieczki na początek. Czas przejścia, który liczy też podejście.',
  'fooldal.tervezek': 'Zaplanuję wycieczkę',
  'fooldal.peldak': 'Zobaczę przykłady',
  'fooldal.ma': 'Dziś',
  'fooldal.napkelte': 'wschód słońca',
  'fooldal.napnyugta': 'zachód słońca',
  'fooldal.vilagosMeg': 'jeszcze widno',
  'fooldal.lement': 'zaszło',
  'fooldal.vanMeg': 'jeszcze widno',
  'fooldal.marLement': 'słońce już zaszło',
  'fooldal.napAlap': 'Dla Budapesztu. Planer liczy od początku twojej własnej trasy.',
  'fooldal.jelzesCim': 'Co oznacza farba na drzewie?',
  'fooldal.jelzesLead': 'Węgierski znak szlaku mówi dwie rzeczy naraz. Kolor — jak duża jest trasa, kształt — do czego służy.',
  'fooldal.jelzesSzin': 'kolor',
  'fooldal.jelzesAlak': 'kształt',
  'fooldal.jelzesApro': 'Nie pisaliśmy tego z pamięci: sprawdziliśmy na oznakowanych ścieżkach w OpenStreetMap, co dokąd prowadzi. Trasy z trójkątem kończą się na szczycie albo przy wieży widokowej, trasy z kołem wracają tam, skąd wyszły.',
  'fooldal.keszVonal': 'Zacznij od gotowej trasy',
  'fooldal.keszVonalLead': 'Otwórz ją, przesuń punkty, zrób z niej swoją.',
  'fooldal.szerintunk': 'naszym zdaniem',
  'fooldal.osszesPelda': 'Wszystkie przykłady →',

  'peldak.kicsi': 'Przykłady',
  'peldak.cim': 'Gotowe trasy na początek.',
  'peldak.bevezeto': 'Otwórz dowolną, przesuń punkty, dodaj własne znaczniki — i jest twoja.',
  'peldak.tajegyseg': 'Region',
  'peldak.mindegyik': 'Wszystkie',
  'peldak.hossz': 'Długość',
  'peldak.nehezseg': 'Trudność',
  'peldak.torold': 'wyczyść wszystko',
  'peldak.szurokTorol': 'wyczyść filtry',
  'peldak.utvonal': 'tras',
  'peldak.megnezem': 'Zobacz',
  'peldak.gyalogut': 'Trasy biegną rzeczywistymi ścieżkami',
  'peldak.gyalogutUtan': ', nie po linii prostej między dwoma punktami — dlatego odległość i podejście są prawdziwe. W terenie i tak liczą się oznakowane szlaki i mapy oficjalne.',
  'peldak.darab': 'Tras: {db}',

  'utvonal.nincs': 'Tej trasy nie ma.',
  'utvonal.tobbi': 'Oto pozostałe przykłady.',
  'tempo.gyalog': 'Pieszo',
  'tempo.futas': 'Bieg',
  'tempo.bringa': 'Rower',
  'utvonal.elgepelt': 'Może pomyliłeś adres.',
  'utvonal.kozelitoUtan': ' W terenie liczą się oznakowane szlaki i mapy oficjalne.',
  'utvonal.hossz': 'Długość',
  'utvonal.sik': 'Liczone dla płaskiego terenu; pod górę więcej.',
  'utvonal.jelolesek': 'Znaczniki',
  'utvonal.kozelito': 'Przybliżony przebieg, nie zmierzony szlak.',
  'utvonal.megnyitas': 'Otwórz w planerze',
  'utvonal.gpx': 'Pobierz GPX',

  'tervezo.honnanHova': 'Skąd dokąd?',
  'tervezo.adatok': 'Dane trasy',
  'tervezo.adatokCimke': 'Dane trasy — {km}, {ido}',
  'tervezo.eszkozok': 'Zapis, gotowe trasy, GPX',
  'tervezo.vissza': 'Krok wstecz',
  'tervezo.oldalCim': 'Planer tras',
  'tervezo.retegek': 'Co ma pokazywać mapa',
  'tervezo.ujraKeres': 'Szukaj na tym obszarze',

  'hh.honnan': 'Skąd',
  'hh.hova': 'Dokąd — jeśli zostawisz puste, tylko tam skoczymy',
  'hh.honnanHely': 'Nazwa miejsca albo współrzędne',
  'hh.hovaHely': 'Na przykład: Rysy',
  'hh.innen': 'Ruszam stąd',
  'hh.odaugras': 'Skocz tam',
  'hh.szamolom': 'Liczę…',
  'hh.utvonalat': 'Poproszę trasę',
  'hh.keres': 'Szukam…',
  'hh.nincsHelyzet': 'Nie udało się ustalić twojego położenia. Wpisz punkt startowy ręcznie.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} godz. {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} g {p} m',
  'adat.hossz': 'długość',
  'adat.emelkedo': 'podejście',
  'adat.lejto': 'zejście',
  'adat.nehezseg': 'trudność',
  'adat.tempo': 'Tempo',
  'adat.tengerszint': '{also}–{felso} m n.p.m.',
  'adat.nev': 'Na przykład: niedzielna pętla',

  'terkep.igazit': 'Dopasowuję linię do prawdziwych ścieżek…',
  'terkep.masodik': 'Zaznacz drugi punkt — linia sama trafi na ścieżkę.',
  'terkep.keszUt': 'Trasa gotowa. Dotknij mapy, żeby zacząć nową.',
  'terkep.sug': 'Dotknij mapy, żeby dodać punkty. Punkty można przeciągać; dotknięcie usuwa je.',
  'terkep.keszVonal': 'Gotowe — linia biegnie rzeczywistymi ścieżkami.',
  'jeloles.ugras': 'Skocz do: {nev}',
  'jeloles.neve': 'Nazwa: {tipus}',
  'terkep.jelolesTorol': 'Usuń znacznik',
  'terkep.tobbVan': 'jest tu tego więcej — przybliż',
  'terkep.keresem': 'szukam…',
  'terkep.nagyits': 'przybliż',
  'terkep.hiba': 'nie udało się',
  'terkep.nincsAdat': 'brak danych',

  'reteg.viz': 'Woda pitna, źródło',
  'reteg.menedek': 'Schronienie',
  'reteg.kozlekedes': 'Przystanek, stacja',
  'reteg.parkolo': 'Parking',
  'reteg.kilato': 'Punkt widokowy',
  'reteg.vendeglatas': 'Jedzenie i picie',
  'reteg.latvany': 'Atrakcja',

  'nincs.cim': 'Nie ma takiej strony',
  'nincs.magyarazat': 'Albo pomyliłeś adres, albo prowadzi on do strony, której już nie ma.',
  'nincs.lead': 'Stąd możesz pójść dalej:',
  'nincs.kezdolap': 'Strona główna',
  'nincs.tervezo': 'Planer tras',
  'nincs.tervezoLeiras': 'narysuj wycieczkę na mapie',
  'nincs.peldak': 'Gotowe trasy',
  'nincs.peldakLeiras': 'przykłady, które możesz otworzyć',

  'meta.fooldalCim': 'Túrabakancs — trasy piesze, znaki szlaków, opinie',
  'meta.fooldalLeiras': 'Mapa do planowania tras, wyjaśnienie węgierskich znaków szlaków i opinie bez nazwisk.',
  'meta.tervezoCim': 'Planer — Túrabakancs',
  'meta.tervezoLeiras': 'Narysuj trasę na mapie, dodaj znaczniki, udostępnij linkiem.',
  'meta.peldakCim': 'Przykładowe trasy — Túrabakancs',
  'meta.peldakLeiras': 'Gotowe trasy piesze na mapie, które możesz otworzyć i rysować dalej.',
  'meta.impresszumCim': 'O stronie i prywatność — Túrabakancs',
  'meta.impresszumLeiras': 'Do czego strona służy, a do czego nie. Bez konta, bez ciasteczek, bez śledzenia; co narysujesz, zostaje w twojej przeglądarce.',
  'meta.nincsCim': 'Nie ma takiej strony — Túrabakancs',
  'meta.nincsLeiras': 'Ten adres nie istnieje.',

  /* ---- Nehézség, szűrők, ajánló ---- */
  'nehez.konnyu': 'Łatwa',
  'nehez.kozepes': 'Średnia',
  'nehez.eros': 'Wymagająca',
  'nehez.nehez': 'Trudna',
  'nehez.konnyuLeiras': 'Krótki spacer, poradzi sobie każdy.',
  'nehez.kozepesLeiras': 'Pół dnia, nie trzeba kondycji.',
  'nehez.erosLeiras': 'Całodniowa wycieczka, przygotuj się.',
  'nehez.nehezLeiras': 'Długi dzień. Tylko z doświadczeniem i sprzętem.',
  'szuro.rovid': 'Krótka',
  'szuro.kozepes': 'Średnia',
  'szuro.hosszu': 'Długa',
  'szuro.rovidLeiras': 'poniżej 3 km',
  'szuro.kozepesLeiras': '3–8 km',
  'szuro.hosszuLeiras': 'powyżej 8 km',
  'tanacs.osszkepCimke': '{nehez} — {ido} marszu',
  'tanacs.osszkepMagassag': '{km} km, {fel} m podejścia. {leiras} Czas marszu jest bez przerw; dolicz co najmniej pół godziny.',
  'tanacs.osszkepNincs': '{km} km. {leiras} Podejście jeszcze się wczytuje; na razie czas marszu liczy tylko odległość.',
  'tanacs.sotetCimke': 'Słońce już zaszło',
  'tanacs.sotetSzoveg': 'Zachód słońca był dziś o {ido}. Jeśli ruszasz teraz, nie idź bez czołówki.',
  'tanacs.sotetedesCimke': 'Nie zdążysz przed zmrokiem',
  'tanacs.sotetedesSzoveg': 'Zachód słońca o {nyugta}, zostało {maradek}. Trasa zajmie {ut}, bez przerw. Weź czołówkę albo ruszaj wcześniej.',
  'tanacs.vilagosCimke': '{maradek} do zachodu słońca',
  'tanacs.vilagosSzoveg': 'Dziś ściemnia się o {ido}. Jeśli ruszasz teraz, masz mnóstwo czasu.',
  'tanacs.visszautCimke': 'Meta nie jest tam, gdzie start',
  'tanacs.visszautSzoveg': 'Dzieli je {tav} km. Jeśli jedziesz autem, przemyśl, jak do niego wrócisz — albo zaplanuj pętlę.',
  'tanacs.vizCimke': 'Nie zaznaczono miejsca z wodą',
  'tanacs.vizSzoveg': 'Na {km} km to za mało. Włącz warstwę wody pitnej: pokażę, co jest w okolicy.',
  'tanacs.megkozelitesCimke': 'Nie zaznaczono, jak dotrzesz na start',
  'tanacs.megkozelitesSzoveg': 'To będzie pierwsze pytanie przed wyjściem. Warstwą przystanków zobaczysz, co jest w okolicy.',
  'tanacs.durvaCimke': 'Linia jest bardzo prosta',
  'tanacs.durvaSzoveg': 'Średnio {atlag} km na odcinek. Prawdziwa ścieżka wije się, więc rzeczywisty dystans jest dłuższy — dodaj więcej punktów, żeby było dokładniej.',
  'tanacs.emelkedoCimke': '{fel} metrów podejścia',
  'tanacs.emelkedoSzoveg': 'Najniższy punkt to {min} m, najwyższy {max} m. Samo to podejście wydłuża czas marszu o {plusz}.',
  'tanacs.veszelyCimke': 'Zaznaczyłeś trudny odcinek',
  'tanacs.veszelySzoveg': 'Po deszczu i na mrozie strome, skaliste odcinki są dużo wolniejsze i bardziej ryzykowne. Sprawdź pogodę przed wyjściem.',

  /* ---- Időjárás és jelöléstípusok ---- */
  'ido.derult': 'Bezchmurnie',
  'ido.jobbaraDerult': 'Przeważnie bezchmurnie',
  'ido.szakadozott': 'Zachmurzenie umiarkowane',
  'ido.borult': 'Pochmurno',
  'ido.kod': 'Mgła',
  'ido.zuzmarasKod': 'Mgła osadzająca szadź',
  'ido.gyengeSzitalas': 'Słaba mżawka',
  'ido.szitalas': 'Mżawka',
  'ido.erosSzitalas': 'Silna mżawka',
  'ido.gyengeEso': 'Słaby deszcz',
  'ido.eso': 'Deszcz',
  'ido.erosEso': 'Silny deszcz',
  'ido.gyengeHavazas': 'Słabe opady śniegu',
  'ido.havazas': 'Opady śniegu',
  'ido.erosHavazas': 'Silne opady śniegu',
  'ido.hoszemcsek': 'Śnieg ziarnisty',
  'ido.zapor': 'Przelotny deszcz',
  'ido.hevesZapor': 'Silny przelotny deszcz',
  'ido.hozapor': 'Przelotne opady śniegu',
  'ido.erosHozapor': 'Silne przelotne opady śniegu',
  'ido.zivatar': 'Burza',
  'ido.jegesoZivatar': 'Burza z gradem',
  'ido.hevesJegeso': 'Silna burza z gradem',
  'ido.ismeretlen': 'Nieznane',
  'idoFigy.zivatar': 'Spodziewane burze. Na grani ani na wieży widokowej nie masz wtedy czego szukać.',
  'idoFigy.sokCsapadek': '{mm} mm opadów: skalne odcinki i drabinki będą śliskie.',
  'idoFigy.eso': 'Spodziewany deszcz — na błotnistych stokach pójdzie wolniej.',
  'idoFigy.meleg': '{fok} stopni: na odcinkach bez cienia weź podwójny zapas wody.',
  'idoFigy.fagy': 'O świcie {fok} stopni: szlak może być oblodzony.',
  'idoFigy.szel': 'Wiatr {szel} km/h: na grani nieprzyjemny, na wieży zimny.',
  'tipus.kilato': 'Punkt widokowy',
  'tipus.forras': 'Źródło, woda pitna',
  'tipus.pihen': 'Miejsce odpoczynku, ławka',
  'tipus.parkolo': 'Parking',
  'tipus.vendeglatas': 'Jedzenie i picie',
  'tipus.latnivalo': 'Atrakcja',
  'tipus.veszely': 'Niebezpieczeństwo, trudny odcinek',
  'tipus.kozlekedes': 'Przystanek, stacja',

  /* ---- Tanácsok, túralista, napnevek ---- */
  'tanacs.lekerem': 'Pobieram…',
  'tanacs.milyenIdo': 'Jaka będzie pogoda?',
  'nap.ma': 'dziś',
  'nap.holnap': 'jutro',
  'turak.lead': 'Pokażę, jakie {jelzett} biegną tam, gdzie właśnie jest mapa. Każdy możesz wczytać i rysować dalej.',
  'turak.jelzett': 'oznakowane szlaki',
  'turak.keresem': 'Szukam…',
  'turak.keres': 'Szukaj szlaków na tym obszarze',
  'turak.tolt': 'wczytuję…',
  'turak.festett': 'W terenie liczy się malowany znak.',

  /* ---- Impresszum és adatkezelés ---- */
  'imp.cim': 'O stronie i prywatność',
  'imp.felelossegCim': 'Odpowiedzialność — przeczytaj, zanim ruszysz',
  'imp.felelossegLead': 'Strona pokazuje trasy, odległości, podejścia, czasy marszu i zachód słońca. To {eros}, nie gwarancje:',
  'imp.felelossegEros': 'obliczenia i szacunki',
  'imp.felelosseg1': 'Linie biegną ścieżkami z danych mapowych. Czy dana ścieżka jest teraz przejezdna, mapa nie wie — może spaść na nią drzewo, może ją zmyć deszcz, może być zamknięta.',
  'imp.felelosseg2': 'Czas marszu liczy dla terenu płaskiego i średniego tempa. Obciążenie, śnieg, błoto, zmrok i twoja kondycja to zmieniają.',
  'imp.felelosseg3': 'Podejście pochodzi z modelu terenu, który może różnić się od rzeczywistości o kilka metrów.',
  'imp.felelossegZaro': '{eros} Do orientacji służą oznakowane szlaki i mapy oficjalne; przed wyjściem sprawdź pogodę i powiedz komuś, dokąd idziesz. Ta strona pomaga planować — nie zastępuje zdrowego rozsądku.',
  'imp.felelossegZaroEros': 'W terenie liczy się twoja własna decyzja i odpowiedzialność.',
  'imp.tartalomCim': 'Treść',
  'imp.tartalom': 'Oceny w gwiazdkach to nasza opinia, nie średnia cudzych punktów. Dane mapowe pochodzą z OpenStreetMap, utrzymywanego przez wolontariuszy. Zdjęcia atrakcji są na wolnych licencjach, z nazwiskami autorów — pełna lista niżej, pod {link}.',
  'imp.adatCim': 'Prywatność',
  'imp.adat1': 'Strona nie wymaga konta, nie zbiera danych osobowych i nie używa ciasteczek. To, co rysujesz, powstaje w twojej przeglądarce i tam zostaje: zapisane plany trafiają do pamięci twojego urządzenia, a link do udostępnienia umieszcza trasę w samym adresie, nie w bazie danych.',
  'imp.adat2': 'To, co jednak wychodzi do internetu, nie trafia do nas. Kafelki mapy i odpowiedzi wyszukiwarki miejsc dają publiczne usługi OpenStreetMap, dane wysokościowe Open-Meteo, a dopasowanie tras do ścieżek pieszy router FOSSGIS. Gdy wskażesz atrakcję, jej zdjęcie dostarcza Wikimedia Commons — dopiero wtedy, gdy ją wskażesz. Wtedy — jak przy każdym obrazku na każdej stronie — widoczny jest dla nich twój adres IP, a przy dopasowaniu i wysokości także współrzędne twojej linii. Nie da się tego ominąć, jeśli chcemy pokazać mapę; ale przynajmniej o tym wiesz.',
  'imp.kepekCim': 'Zdjęcia',
  'imp.kepek': 'Zdjęcia atrakcji pochodzą z Wikimedia Commons i są na wolnych licencjach — ale wolne nie znaczy bezpańskie: każde ma autora, którego trzeba wymienić. Obraz pobiera się dopiero wtedy, gdy wskażesz atrakcję, a nazwisko autora zawsze jest obok. Poniższa lista obejmuje piętnaście węgierskich miejsc, których zdjęcia trzymamy u siebie.',

  /* ---- Alfajták és ivhatóság ---- */
  'fajta.ivoviz': 'Woda pitna',
  'fajta.forras': 'Źródło',
  'fajta.esobeallo': 'Wiata',
  'fajta.menedekhaz': 'Schron',
  'fajta.turistahaz': 'Schronisko',
  'fajta.vasutallomas': 'Stacja kolejowa',
  'fajta.megallohely': 'Przystanek kolejowy',
  'fajta.buszmegallo': 'Przystanek autobusowy',
  'fajta.parkolo': 'Parking',
  'fajta.kilatopont': 'Punkt widokowy',
  'fajta.kilatotorony': 'Wieża widokowa',
  'fajta.etterem': 'Restauracja',
  'fajta.kavezo': 'Kawiarnia',
  'fajta.kocsma': 'Pub',
  'fajta.bufe': 'Bar szybkiej obsługi',
  'fajta.var': 'Zamek',
  'fajta.rom': 'Ruiny',
  'fajta.regeszeti': 'Stanowisko archeologiczne',
  'fajta.emlekmu': 'Pomnik',
  'fajta.muzeum': 'Muzeum',
  'fajta.vizeses': 'Wodospad',
  'fajta.barlang': 'Wejście do jaskini',
  'fajta.sziklakapu': 'Brama skalna',
  'fajta.vilagitotorony': 'Latarnia morska',
  'fajta.latnivalo': 'Atrakcja',
  'viz.ihato': 'zdatna do picia',
  'viz.nemIhato': 'NIE nadaje się do picia',
  'viz.nincsAdat': 'brak danych, czy nadaje się do picia',

  /* ---- Hibaüzenetek és apróságok ---- */
  'hiba.utvonalkereso': 'Wyszukiwarka tras jest teraz niedostępna.',
  'hiba.helykereso': 'Wyszukiwarka miejsc jest teraz niedostępna.',
  'hiba.helykeresoNema': 'Wyszukiwarka miejsc nie odpowiada.',
  'hiba.haromBetu': 'Wpisz co najmniej trzy litery.',
  'hiba.nincsHely': 'Nie znalazłem miejsca dla: „{mit}”',
  'hiba.elorejelzes': 'Prognoza jest teraz niedostępna.',
  'hiba.homerseklet': 'Temperatura jest teraz niedostępna.',
  'hiba.magassag': 'Dane wysokościowe są teraz niedostępne.',
  'hiba.osmNema': 'Wyszukiwarka OpenStreetMap nie odpowiada.',
  'hiba.tulterhelt': 'Wyszukiwarka jest przeciążona. Spróbuj za kilka sekund.',
  'hiba.terheles': 'Wyszukiwarka nie wyrabia. Spróbuj za kilka sekund.',
  'hiba.keresesNemSikerult': 'Wyszukiwanie się nie powiodło.',
  'hiba.ismeretlenReteg': 'Nieznana warstwa.',
  'hiba.nincsHelyzet': 'Ta przeglądarka nie potrafi ustalić twojego położenia.',
  'gpx.nemTud': 'Ta przeglądarka nie potrafi czytać GPX.',
  'gpx.serult': 'Ten plik to nie czytelny GPX — uszkodzony albo inny format.',
  'gpx.ures': 'W tym pliku nie ma ani śladu, ani znaczników.',
  'gpx.nagy': 'Ten plik ma ponad 5 MB. Tak dużego śladu nie da się sensownie pokazać.',
  'gpx.nemSikerult': 'Nie udało się wczytać tego pliku.',
  'terv.ujKezdtel': 'Zacząłeś nową trasę — strzałką odzyskasz poprzednią.',
  'terv.betoltve': 'Wczytane. Przesuń punkty albo dodaj znaczniki.',
  'terv.vagolapon': 'Link jest w schowku — trasa jest w samym adresie.',
  'terv.cimsorban': 'Link do udostępnienia jest w pasku adresu przeglądarki.',
  'terv.elmentve': 'Zapisane. Na innym urządzeniu dotrzesz przez link do udostępnienia.',
  'terv.nevtelen': 'Plan bez nazwy',
  'terv.mentesFrissit': 'Zaktualizuj zapis',
  'terv.mentesBongeszobe': 'Zapisz w przeglądarce',
  'terkep.cel': 'Meta',
  'terkep.kozremukodoi': 'współtwórcy',
  'terkep.rajt': 'Start',
  'terkep.hanyadikPont': 'Punkt {n}',
  'hh.koordinata': 'podane współrzędne',
  'nap.ketNapMulva': 'Za dwa dni',
  'turak.jelzettUt': 'oznakowany szlak',
  'kep.lasdForras': 'zobacz źródło',
  'ut.ketPont': 'Potrzebne są co najmniej dwa punkty.',
  'ut.nemErheto': 'Wyszukiwarka tras jest teraz niedostępna. Spróbuj później.',
  'ut.tulSok': 'Zbyt wiele zapytań w krótkim czasie. Poczekaj chwilę.',
  'ut.hibat': 'Wyszukiwarka tras zwróciła błąd.',
  'ut.nincsGyalogut': 'Między tymi punktami nie znalazłem ścieżki. Może jest tam woda albo płot.',
  'ut.nemSikerult': 'Nie udało się znaleźć trasy.',
  'ut.tulSokPont': 'Naraz mogę dopasować do ścieżek najwyżej {max} punktów. Usuń kilka albo podziel na odcinki.',
  'ut.nincsGyalogut2': 'Między tymi punktami nie znalazłem ścieżki. Może prowadzi przez wodę albo bezdroża.',
  'terv.egyenesMarad': '{ok} Linia na razie zostaje prosta, więc odległość i podejście są mniejsze niż w rzeczywistości.',
  'adat.tengerszintUtan': 'n.p.m.',

  /* ---- Főoldal: mit tud, kiemelt példa ---- */
  'fooldal.peldaKalap': 'Tak wygląda to, co dostajesz',
  'fooldal.peldaNyisd': 'Otwórz w planerze',
  'fooldal.osvenyCim': 'Ścieżka, gdy przewijasz',
  'fooldal.osvenyLead': 'To nie ilustracja: jedna z klasycznych jednodniowych wycieczek w górach Pilis, narysowana z jej własnych punktów. Oznaczenia zapalają się tam, gdzie naprawdę są.',
  'fooldal.osvenyGomb': 'Zobacz tę wycieczkę',
  'fooldal.mitTud': 'Co potrafi ta mapa',
  'fooldal.mitTudLead': 'Cztery powody, żeby planować tutaj, a nie na zwykłej mapie.',
  'fooldal.tud1Cim': 'Linia biegnie prawdziwymi ścieżkami',
  'fooldal.tud1': 'To nie linia prosta między dwoma punktami. Zaznacz dwa miejsca, a trasa sama trafi na prawdziwe ścieżki — dlatego odległość i podejście są prawdziwe.',
  'fooldal.tud2Cim': 'Czas marszu liczy podejście',
  'fooldal.tud2': 'Dziesięć kilometrów po płaskim i dziesięć w górach to nie ten sam czas. Szacunek dolicza za każde sto metrów podejścia i pokazuje też profil wysokościowy.',
  'fooldal.tud3Cim': 'Pokazuje, co jest w okolicy',
  'fooldal.tud3': 'Siedem warstw z OpenStreetMap: woda pitna, schronienia, przystanki, parkingi, punkty widokowe, jedzenie, atrakcje. W dowolnym kraju na świecie.',
  'fooldal.tud4Cim': 'Zostaje twoje',
  'fooldal.tud4': 'To, co rysujesz, powstaje w twojej przeglądarce. Link do udostępnienia niesie samą trasę, nie identyfikator z bazy — i pobierzesz ją w GPX, do dowolnego zegarka czy aplikacji.',
  'adat.menetido': 'czas marszu',
};
