/* Polski. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — strona główna',
  'fejlec.menuNyit': 'Otwórz menu',
  'fejlec.menuZar': 'Zamknij menu',
  'fejlec.foMenu': 'Menu główne',
  'fejlec.sotetMod': 'Przełącz tryb ciemny',
  'fejlec.fok': 'Teraz {fok} stopni — {ido}',
  'fejlec.jelenleg': 'Obecnie',

  'menu.fooldal': 'Strona główna',
  'menu.fooldalLeiras': 'Znaki szlaków, przykłady i opinie',
  'menu.tervezo': 'Planer',
  'menu.tervezoLeiras': 'Wpisz dwa miejsca albo rysuj na mapie',
  'menu.peldak': 'Przykłady',
  'menu.peldakLeiras': 'Gotowe trasy na początek',

  'lab.terkep': 'Mapę tworzą współtwórcy {osm}, którzy dostarczają też kafelki.',
  'lab.becsles': 'Odległość i czas przejścia to szacunki — w terenie liczą się oznakowane szlaki.',
  'lab.impresszum': 'O stronie i prywatność',

  'fooldal.cim': 'Túrabakancs — mapa do planowania tras pieszych',
  'fooldal.lead': 'Mapa, po której można rysować. Gotowe wycieczki na początek. Czas przejścia, który liczy też podejście.',
  'fooldal.tervezek': 'Zaplanuję wycieczkę',
  'fooldal.peldak': 'Zobaczę przykłady',
  'fooldal.ma': 'Dziś',
  'fooldal.napkelte': 'wschód słońca',
  'fooldal.napnyugta': 'zachód słońca',
  'fooldal.vilagosMeg': 'jeszcze widno',
  'fooldal.lement': 'zaszło',
  'fooldal.vanMeg': 'jeszcze widno',
  'fooldal.marLement': 'słońce już zaszło',
  'fooldal.napAlap': 'Dla Budapesztu. Planer liczy od początku twojej własnej trasy.',
  'fooldal.jelzesCim': 'Co oznacza farba na drzewie?',
  'fooldal.jelzesLead': 'Węgierski znak szlaku mówi dwie rzeczy naraz. Kolor — jak duża jest trasa, kształt — do czego służy.',
  'fooldal.jelzesSzin': 'kolor',
  'fooldal.jelzesAlak': 'kształt',
  'fooldal.jelzesApro': 'Nie pisaliśmy tego z pamięci: sprawdziliśmy na oznakowanych ścieżkach w OpenStreetMap, co dokąd prowadzi. Trasy z trójkątem kończą się na szczycie albo przy wieży widokowej, trasy z kołem wracają tam, skąd wyszły.',
  'fooldal.keszVonal': 'Zacznij od gotowej trasy',
  'fooldal.keszVonalLead': 'Otwórz ją, przesuń punkty, zrób z niej swoją.',
  'fooldal.szerintunk': 'naszym zdaniem',
  'fooldal.osszesPelda': 'Wszystkie przykłady →',

  'peldak.kicsi': 'Przykłady',
  'peldak.cim': 'Gotowe trasy na początek.',
  'peldak.bevezeto': 'Otwórz dowolną, przesuń punkty, dodaj własne znaczniki — i jest twoja.',
  'peldak.tajegyseg': 'Region',
  'peldak.mindegyik': 'Wszystkie',
  'peldak.hossz': 'Długość',
  'peldak.nehezseg': 'Trudność',
  'peldak.torold': 'wyczyść wszystko',
  'peldak.szurokTorol': 'wyczyść filtry',
  'peldak.utvonal': 'tras',
  'peldak.megnezem': 'Zobacz',
  'peldak.gyalogut': 'Trasy biegną rzeczywistymi ścieżkami',
  'peldak.gyalogutUtan': ', nie po linii prostej między dwoma punktami — dlatego odległość i podejście są prawdziwe. W terenie i tak liczą się oznakowane szlaki i mapy oficjalne.',
  'peldak.darab': 'Tras: {db}',

  'utvonal.nincs': 'Tej trasy nie ma.',
  'utvonal.tobbi': 'Oto pozostałe przykłady.',
  'utvonal.hossz': 'Długość',
  'utvonal.sik': 'Liczone dla płaskiego terenu; pod górę więcej.',
  'utvonal.jelolesek': 'Znaczniki',
  'utvonal.kozelito': 'Przybliżony przebieg, nie zmierzony szlak.',
  'utvonal.megnyitas': 'Otwórz w planerze',
  'utvonal.gpx': 'Pobierz GPX',

  'tervezo.honnanHova': 'Skąd dokąd?',
  'tervezo.adatok': 'Dane trasy',
  'tervezo.adatokCimke': 'Dane trasy — {km}, {ido}',
  'tervezo.eszkozok': 'Zapis, gotowe trasy, GPX',
  'tervezo.vissza': 'Krok wstecz',
  'tervezo.retegek': 'Co ma pokazywać mapa',
  'tervezo.ujraKeres': 'Szukaj na tym obszarze',

  'hh.honnan': 'Skąd',
  'hh.hova': 'Dokąd — jeśli zostawisz puste, tylko tam skoczymy',
  'hh.honnanHely': 'Nazwa miejsca albo współrzędne',
  'hh.hovaHely': 'Na przykład: Rysy',
  'hh.innen': 'Ruszam stąd',
  'hh.odaugras': 'Skocz tam',
  'hh.szamolom': 'Liczę…',
  'hh.utvonalat': 'Poproszę trasę',
  'hh.keres': 'Szukam…',
  'hh.nincsHelyzet': 'Nie udało się ustalić twojego położenia. Wpisz punkt startowy ręcznie.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} godz. {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} g {p} m',
  'adat.hossz': 'długość',
  'adat.emelkedo': 'podejście',
  'adat.lejto': 'zejście',
  'adat.nehezseg': 'trudność',
  'adat.tempo': 'Tempo',
  'adat.tengerszint': '{also}–{felso} m n.p.m.',
  'adat.nev': 'Na przykład: niedzielna pętla',

  'terkep.igazit': 'Dopasowuję linię do prawdziwych ścieżek…',
  'terkep.masodik': 'Zaznacz drugi punkt — linia sama trafi na ścieżkę.',
  'terkep.keszUt': 'Trasa gotowa. Dotknij mapy, żeby zacząć nową.',
  'terkep.sug': 'Dotknij mapy, żeby dodać punkty. Punkty można przeciągać; dotknięcie usuwa je.',
  'terkep.keszVonal': 'Gotowe — linia biegnie rzeczywistymi ścieżkami.',
  'terkep.jelolesTorol': 'Usuń znacznik',
  'terkep.tobbVan': 'jest tu tego więcej — przybliż',
  'terkep.keresem': 'szukam…',
  'terkep.nagyits': 'przybliż',
  'terkep.hiba': 'nie udało się',
  'terkep.nincsAdat': 'brak danych',

  'reteg.viz': 'Woda pitna, źródło',
  'reteg.menedek': 'Schronienie',
  'reteg.kozlekedes': 'Przystanek, stacja',
  'reteg.parkolo': 'Parking',
  'reteg.kilato': 'Punkt widokowy',
  'reteg.vendeglatas': 'Jedzenie i picie',
  'reteg.latvany': 'Atrakcja',

  'nincs.cim': 'Nie ma takiej strony',
  'nincs.magyarazat': 'Albo pomyliłeś adres, albo prowadzi on do strony, której już nie ma.',
  'nincs.lead': 'Stąd możesz pójść dalej:',
  'nincs.kezdolap': 'Strona główna',
  'nincs.tervezo': 'Planer tras',
  'nincs.tervezoLeiras': 'narysuj wycieczkę na mapie',
  'nincs.peldak': 'Gotowe trasy',
  'nincs.peldakLeiras': 'przykłady, które możesz otworzyć',

  'meta.fooldalCim': 'Túrabakancs — trasy piesze, znaki szlaków, opinie',
  'meta.fooldalLeiras': 'Mapa do planowania tras, wyjaśnienie węgierskich znaków szlaków i opinie bez nazwisk.',
  'meta.tervezoCim': 'Planer — Túrabakancs',
  'meta.tervezoLeiras': 'Narysuj trasę na mapie, dodaj znaczniki, udostępnij linkiem.',
  'meta.peldakCim': 'Przykładowe trasy — Túrabakancs',
  'meta.peldakLeiras': 'Gotowe trasy piesze na mapie, które możesz otworzyć i rysować dalej.',
  'meta.impresszumCim': 'O stronie i prywatność — Túrabakancs',
  'meta.impresszumLeiras': 'Do czego strona służy, a do czego nie. Bez konta, bez ciasteczek, bez śledzenia; co narysujesz, zostaje w twojej przeglądarce.',
  'meta.nincsCim': 'Nie ma takiej strony — Túrabakancs',
  'meta.nincsLeiras': 'Ten adres nie istnieje.',
};
