/* Română. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — pagina principală',
  'fejlec.menuNyit': 'Deschide meniul',
  'fejlec.menuZar': 'Închide meniul',
  'fejlec.foMenu': 'Meniu principal',
  'fejlec.sotetMod': 'Comută modul întunecat',
  'fejlec.fok': 'Acum {fok} grade — {ido}',
  'fejlec.jelenleg': 'În prezent',

  'menu.fooldal': 'Acasă',
  'menu.fooldalLeiras': 'Marcaje turistice, exemple și păreri',
  'menu.tervezo': 'Planificator',
  'menu.tervezoLeiras': 'Scrie două locuri sau desenează pe hartă',
  'menu.peldak': 'Exemple',
  'menu.peldakLeiras': 'Trasee gata făcute de la care poți porni',

  'lab.terkep': 'Harta este făcută de colaboratorii {osm}, care furnizează și dalele.',
  'lab.becsles': 'Distanța și timpul de mers sunt estimări — pe teren contează traseele marcate.',
  'lab.impresszum': 'Despre site și date',

  'fooldal.cim': 'Túrabakancs — hartă pentru planificarea traseelor',
  'fooldal.lead': 'O hartă pe care poți desena. Trasee gata făcute de la care să pornești. Timp de mers care ține cont și de urcare.',
  'fooldal.tervezek': 'Planific o drumeție',
  'fooldal.peldak': 'Văd exemple',
  'fooldal.ma': 'Azi',
  'fooldal.napkelte': 'răsărit',
  'fooldal.napnyugta': 'apus',
  'fooldal.vilagosMeg': 'lumină rămasă',
  'fooldal.lement': 'a apus',
  'fooldal.vanMeg': 'încă e lumină',
  'fooldal.marLement': 'soarele a apus',
  'fooldal.napAlap': 'Pentru Budapesta. Planificatorul calculează pentru punctul de plecare al traseului tău.',
  'fooldal.jelzesCim': 'Ce înseamnă vopseaua de pe copac?',
  'fooldal.jelzesLead': 'Un marcaj turistic maghiar spune două lucruri deodată. Culoarea arată cât de mare este traseul, forma arată la ce folosește.',
  'fooldal.jelzesSzin': 'culoare',
  'fooldal.jelzesAlak': 'formă',
  'fooldal.jelzesApro': 'Nu am scris asta din memorie: am verificat pe potecile marcate din OpenStreetMap ce unde duce. Traseele cu triunghi se termină pe un vârf sau la un punct de belvedere, cele cu cerc se întorc de unde au plecat.',
  'fooldal.keszVonal': 'Începe cu un traseu gata făcut',
  'fooldal.keszVonalLead': 'Deschide-l, trage punctele, fă-l al tău.',
  'fooldal.szerintunk': 'după noi',
  'fooldal.osszesPelda': 'Toate exemplele →',

  'peldak.kicsi': 'Exemple',
  'peldak.cim': 'Trasee gata făcute de la care poți porni.',
  'peldak.bevezeto': 'Deschide oricare, trage punctele, pune propriile marcaje — și e al tău.',
  'peldak.tajegyseg': 'Regiune',
  'peldak.mindegyik': 'Toate',
  'peldak.hossz': 'Lungime',
  'peldak.nehezseg': 'Dificultate',
  'peldak.torold': 'șterge tot',
  'peldak.szurokTorol': 'șterge filtrele',
  'peldak.utvonal': 'trasee',
  'peldak.megnezem': 'Vezi',
  'peldak.gyalogut': 'Traseele urmează poteci reale',
  'peldak.gyalogutUtan': ', nu pe o linie dreaptă între două puncte — de aceea distanța și urcarea sunt corecte. Pe teren rămân valabile traseele marcate și hărțile oficiale.',
  'peldak.darab': '{db} trasee',

  'utvonal.nincs': 'Acest traseu nu există.',
  'utvonal.tobbi': 'Iată celelalte exemple.',
  'tempo.gyalog': 'Pe jos',
  'tempo.futas': 'Alergare',
  'tempo.bringa': 'Bicicletă',
  'utvonal.elgepelt': 'Poate ai greșit adresa.',
  'utvonal.kozelitoUtan': ' Pe teren contează traseele marcate și hărțile oficiale.',
  'utvonal.hossz': 'Lungime',
  'utvonal.sik': 'Calculat pentru teren plat; la urcare mai mult.',
  'utvonal.jelolesek': 'Marcaje',
  'utvonal.kozelito': 'Traseu aproximativ, nu potecă măsurată.',
  'utvonal.megnyitas': 'Deschide în planificator',
  'utvonal.gpx': 'Descarcă GPX',

  'tervezo.honnanHova': 'De unde până unde?',
  'tervezo.adatok': 'Datele traseului',
  'tervezo.adatokCimke': 'Datele traseului — {km}, {ido}',
  'tervezo.eszkozok': 'Salvare, trasee gata făcute, GPX',
  'tervezo.vissza': 'Un pas înapoi',
  'tervezo.retegek': 'Ce să arate harta',
  'tervezo.ujraKeres': 'Caută în această zonă',

  'hh.honnan': 'De unde',
  'hh.hova': 'Până unde — dacă lași gol, doar sărim acolo',
  'hh.honnanHely': 'Numele locului sau coordonate',
  'hh.hovaHely': 'De exemplu: Vârful Omu',
  'hh.innen': 'Pornesc de aici',
  'hh.odaugras': 'Sari acolo',
  'hh.szamolom': 'Calculez…',
  'hh.utvonalat': 'Vreau un traseu',
  'hh.keres': 'Caut…',
  'hh.nincsHelyzet': 'Nu am putut obține poziția ta. Scrie punctul de plecare manual.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'lungime',
  'adat.emelkedo': 'urcare',
  'adat.lejto': 'coborâre',
  'adat.nehezseg': 'dificultate',
  'adat.tempo': 'Ritm',
  'adat.tengerszint': '{also}–{felso} m deasupra nivelului mării',
  'adat.nev': 'De exemplu: tura de duminică',

  'terkep.igazit': 'Aliniez linia la potecile reale…',
  'terkep.masodik': 'Marchează al doilea punct — linia se așază singură pe potecă.',
  'terkep.keszUt': 'Traseu gata. Atinge harta dacă vrei unul nou.',
  'terkep.sug': 'Atinge harta pentru puncte. Punctele pot fi trase; o atingere le șterge.',
  'terkep.keszVonal': 'Gata — linia urmează poteci reale.',
  'jeloles.ugras': 'Sari la: {nev}',
  'jeloles.neve': 'Numele: {tipus}',
  'terkep.jelolesTorol': 'Șterge marcajul',
  'terkep.tobbVan': 'sunt mai multe aici — apropie harta',
  'terkep.keresem': 'caut…',
  'terkep.nagyits': 'apropie harta',
  'terkep.hiba': 'nu a reușit',
  'terkep.nincsAdat': 'fără date',

  'reteg.viz': 'Apă potabilă, izvor',
  'reteg.menedek': 'Adăpost',
  'reteg.kozlekedes': 'Stație, gară',
  'reteg.parkolo': 'Parcare',
  'reteg.kilato': 'Belvedere',
  'reteg.vendeglatas': 'Mâncare și băutură',
  'reteg.latvany': 'Obiectiv turistic',

  'nincs.cim': 'Nu există o astfel de pagină',
  'nincs.magyarazat': 'Fie ai greșit adresa, fie duce la o pagină care nu mai există.',
  'nincs.lead': 'De aici poți merge mai departe:',
  'nincs.kezdolap': 'Acasă',
  'nincs.tervezo': 'Planificator de trasee',
  'nincs.tervezoLeiras': 'desenează o drumeție pe hartă',
  'nincs.peldak': 'Trasee gata făcute',
  'nincs.peldakLeiras': 'exemple pe care le poți deschide',

  'meta.fooldalCim': 'Túrabakancs — trasee, marcaje, păreri',
  'meta.fooldalLeiras': 'Hartă pentru planificarea traseelor, explicarea marcajelor turistice maghiare și păreri fără nume.',
  'meta.tervezoCim': 'Planificator — Túrabakancs',
  'meta.tervezoLeiras': 'Desenează un traseu pe hartă, pune marcaje, trimite-l cu un link.',
  'meta.peldakCim': 'Trasee exemplu — Túrabakancs',
  'meta.peldakLeiras': 'Trasee gata făcute pe hartă, pe care le poți deschide și redesena.',
  'meta.impresszumCim': 'Despre site și date — Túrabakancs',
  'meta.impresszumLeiras': 'La ce e bun site-ul și la ce nu. Fără cont, fără cookie-uri, fără urmărire; ce desenezi rămâne în browserul tău.',
  'meta.nincsCim': 'Nu există o astfel de pagină — Túrabakancs',
  'meta.nincsLeiras': 'Această adresă nu există.',

  /* ---- Nehézség, szűrők, ajánló ---- */
  'nehez.konnyu': 'Ușor',
  'nehez.kozepes': 'Mediu',
  'nehez.eros': 'Solicitant',
  'nehez.nehez': 'Greu',
  'nehez.konnyuLeiras': 'O plimbare scurtă, oricine o poate face.',
  'nehez.kozepesLeiras': 'O jumătate de zi, fără condiție fizică specială.',
  'nehez.erosLeiras': 'O drumeție de o zi întreagă, pregătește-te.',
  'nehez.nehezLeiras': 'O zi lungă. Doar cu experiență și echipament.',
  'szuro.rovid': 'Scurt',
  'szuro.kozepes': 'Mediu',
  'szuro.hosszu': 'Lung',
  'szuro.rovidLeiras': 'sub 3 km',
  'szuro.kozepesLeiras': '3–8 km',
  'szuro.hosszuLeiras': 'peste 8 km',
  'tanacs.osszkepCimke': '{nehez} — {ido} de mers',
  'tanacs.osszkepMagassag': '{km} km, {fel} m urcare. {leiras} Timpul de mers este fără pauze; mai adaugă cel puțin o jumătate de oră.',
  'tanacs.osszkepNincs': '{km} km. {leiras} Încă încarc urcarea; până atunci timpul de mers ține cont doar de distanță.',
  'tanacs.sotetCimke': 'Soarele a apus deja',
  'tanacs.sotetSzoveg': 'Apusul a fost azi la {ido}. Dacă pleci acum, nu porni fără frontală.',
  'tanacs.sotetedesCimke': 'Nu termini înainte de lăsarea întunericului',
  'tanacs.sotetedesSzoveg': 'Apusul la {nyugta}, mai sunt {maradek}. Traseul durează {ut}, fără pauze. Ia o frontală sau pleacă mai devreme.',
  'tanacs.vilagosCimke': '{maradek} până la apus',
  'tanacs.vilagosSzoveg': 'Azi se întunecă la {ido}. Dacă pleci acum, ai timp berechet.',
  'tanacs.visszautCimke': 'Sosirea nu e acolo unde e startul',
  'tanacs.visszautSzoveg': 'Sunt la {tav} km distanță. Dacă mergi cu mașina, gândește-te cum te întorci la ea — sau planifică un circuit.',
  'tanacs.vizCimke': 'Niciun punct de apă marcat',
  'tanacs.vizSzoveg': 'Pentru {km} km e prea puțin. Pornește stratul cu apă potabilă: îți arăt ce e în zonă.',
  'tanacs.megkozelitesCimke': 'Nu e marcat cum ajungi la start',
  'tanacs.megkozelitesSzoveg': 'Asta va fi prima întrebare înainte de plecare. Cu stratul de stații vezi ce e în zonă.',
  'tanacs.durvaCimke': 'Linia e foarte dreaptă',
  'tanacs.durvaSzoveg': 'În medie {atlag} km pe segment. O potecă reală șerpuiește, deci distanța efectivă e mai mare — pune mai multe puncte pentru o imagine mai exactă.',
  'tanacs.emelkedoCimke': '{fel} metri urcare',
  'tanacs.emelkedoSzoveg': 'Punctul cel mai jos e la {min} m, cel mai înalt la {max} m. Doar urcarea asta adaugă {plusz} la timpul de mers.',
  'tanacs.veszelyCimke': 'Ai marcat o porțiune dificilă',
  'tanacs.veszelySzoveg': 'După ploaie și pe ger, porțiunile abrupte și stâncoase sunt mult mai lente și mai riscante. Verifică vremea înainte de plecare.',

  /* ---- Időjárás és jelöléstípusok ---- */
  'ido.derult': 'Senin',
  'ido.jobbaraDerult': 'În general senin',
  'ido.szakadozott': 'Parțial noros',
  'ido.borult': 'Acoperit',
  'ido.kod': 'Ceață',
  'ido.zuzmarasKod': 'Ceață cu chiciură',
  'ido.gyengeSzitalas': 'Burniță slabă',
  'ido.szitalas': 'Burniță',
  'ido.erosSzitalas': 'Burniță puternică',
  'ido.gyengeEso': 'Ploaie slabă',
  'ido.eso': 'Ploaie',
  'ido.erosEso': 'Ploaie puternică',
  'ido.gyengeHavazas': 'Ninsoare slabă',
  'ido.havazas': 'Ninsoare',
  'ido.erosHavazas': 'Ninsoare puternică',
  'ido.hoszemcsek': 'Grăunțe de zăpadă',
  'ido.zapor': 'Averse',
  'ido.hevesZapor': 'Averse puternice',
  'ido.hozapor': 'Averse de zăpadă',
  'ido.erosHozapor': 'Averse puternice de zăpadă',
  'ido.zivatar': 'Furtună',
  'ido.jegesoZivatar': 'Furtună cu grindină',
  'ido.hevesJegeso': 'Furtună violentă cu grindină',
  'ido.ismeretlen': 'Necunoscut',
  'idoFigy.zivatar': 'Se așteaptă furtuni. Pe creastă sau în foișor nu ai ce căuta atunci.',
  'idoFigy.sokCsapadek': '{mm} mm de precipitații: porțiunile stâncoase și scările vor fi alunecoase.',
  'idoFigy.eso': 'Se așteaptă ploaie — pe pantele noroioase vei avansa mai greu.',
  'idoFigy.meleg': '{fok} grade: pe porțiunile fără umbră ia dublu de apă.',
  'idoFigy.fagy': 'În zori {fok} grade: traseul poate fi înghețat.',
  'idoFigy.szel': 'Vânt de {szel} km/h: neplăcut pe creastă, rece în foișor.',
  'tipus.kilato': 'Belvedere',
  'tipus.forras': 'Izvor, apă potabilă',
  'tipus.pihen': 'Loc de odihnă, bancă',
  'tipus.parkolo': 'Parcare',
  'tipus.vendeglatas': 'Mâncare și băutură',
  'tipus.latnivalo': 'Obiectiv',
  'tipus.veszely': 'Pericol, porțiune dificilă',
  'tipus.kozlekedes': 'Stație, gară',

  /* ---- Tanácsok, túralista, napnevek ---- */
  'tanacs.lekerem': 'Se încarcă…',
  'tanacs.milyenIdo': 'Cum va fi vremea?',
  'nap.ma': 'azi',
  'nap.holnap': 'mâine',
  'turak.lead': 'Îți arăt ce {jelzett} trec pe unde e harta acum. Poți încărca oricare și să desenezi mai departe.',
  'turak.jelzett': 'trasee marcate',
  'turak.keresem': 'Caut…',
  'turak.keres': 'Caută trasee în zona asta',
  'turak.tolt': 'încarc…',
  'turak.festett': 'Pe teren contează marcajul vopsit.',

  /* ---- Impresszum és adatkezelés ---- */
  'imp.cim': 'Despre site și date',
  'imp.felelossegCim': 'Responsabilitate — citește asta înainte de plecare',
  'imp.felelossegLead': 'Site-ul arată trasee, distanțe, urcări, timpi de mers și apusul. Acestea sunt {eros}, nu garanții:',
  'imp.felelossegEros': 'calcule și estimări',
  'imp.felelosseg1': 'Liniile urmează poteci din datele hărții. Dacă o potecă e practicabilă chiar acum, harta nu poate ști — poate a căzut un copac pe ea, poate a spălat-o ploaia, poate e închisă.',
  'imp.felelosseg2': 'Timpul de mers presupune teren plat și un ritm mediu. Greutatea, zăpada, noroiul, întunericul și condiția ta fizică îl schimbă.',
  'imp.felelosseg3': 'Urcarea provine dintr-un model al terenului, care poate diferi de realitate cu câțiva metri.',
  'imp.felelossegZaro': '{eros} Pentru orientare folosește traseele marcate și hărțile oficiale; verifică vremea înainte de plecare și spune-i cuiva unde mergi. Site-ul ajută la planificare — nu înlocuiește bunul-simț.',
  'imp.felelossegZaroEros': 'Pe teren contează decizia și responsabilitatea ta.',
  'imp.tartalomCim': 'Conținutul',
  'imp.tartalom': 'Evaluările cu stele sunt părerea noastră, nu media punctajelor altora. Datele hărții vin din OpenStreetMap, întreținut de voluntari. Fotografiile obiectivelor sunt sub licențe libere, cu numele autorilor — lista completă mai jos, la {link}.',
  'imp.adatCim': 'Date personale',
  'imp.adat1': 'Site-ul nu cere cont, nu colectează date personale și nu folosește cookie-uri. Ce desenezi se creează în browserul tău și acolo rămâne: planurile salvate ajung în stocarea dispozitivului tău, iar linkul de partajat pune traseul chiar în adresă, nu într-o bază de date.',
  'imp.adat2': 'Ce pleacă totuși pe internet nu vine la noi. Dalele hărții și răspunsurile căutării de locuri vin de la serviciile publice OpenStreetMap, datele de altitudine de la Open-Meteo, iar alinierea traseelor pe poteci de la routerul pietonal FOSSGIS. Dacă arăți spre un obiectiv, imaginea lui vine de la Wikimedia Commons — doar atunci când arăți spre el. În acele momente — ca la orice imagine de pe orice site — adresa ta IP le este vizibilă, iar la aliniere și altitudine și coordonatele liniei tale. Nu putem ocoli asta dacă vrem să arătăm o hartă; măcar știi despre ea.',
  'imp.kepekCim': 'Imaginile',
  'imp.kepek': 'Fotografiile obiectivelor provin de la Wikimedia Commons și sunt sub licențe libere — dar liber nu înseamnă fără stăpân: fiecare are un autor care trebuie menționat. Imaginea se descarcă doar când arăți spre un obiectiv, iar numele autorului e mereu lângă ea. Lista de mai jos cuprinde cele cincisprezece locuri maghiare ale căror imagini le găzduim noi.',

  /* ---- Alfajták és ivhatóság ---- */
  'fajta.ivoviz': 'Apă potabilă',
  'fajta.forras': 'Izvor',
  'fajta.esobeallo': 'Adăpost de ploaie',
  'fajta.menedekhaz': 'Refugiu',
  'fajta.turistahaz': 'Cabană',
  'fajta.vasutallomas': 'Gară',
  'fajta.megallohely': 'Haltă',
  'fajta.buszmegallo': 'Stație de autobuz',
  'fajta.parkolo': 'Parcare',
  'fajta.kilatopont': 'Punct de belvedere',
  'fajta.kilatotorony': 'Turn de observație',
  'fajta.etterem': 'Restaurant',
  'fajta.kavezo': 'Cafenea',
  'fajta.kocsma': 'Bar',
  'fajta.bufe': 'Fast-food',
  'fajta.var': 'Cetate, castel',
  'fajta.rom': 'Ruine',
  'fajta.regeszeti': 'Sit arheologic',
  'fajta.emlekmu': 'Monument',
  'fajta.muzeum': 'Muzeu',
  'fajta.vizeses': 'Cascadă',
  'fajta.barlang': 'Intrare în peșteră',
  'fajta.sziklakapu': 'Arcadă naturală',
  'fajta.vilagitotorony': 'Far',
  'fajta.latnivalo': 'Atracție',
  'viz.ihato': 'potabilă',
  'viz.nemIhato': 'NU e potabilă',
  'viz.nincsAdat': 'fără date dacă e potabilă',

  /* ---- Hibaüzenetek és apróságok ---- */
  'hiba.utvonalkereso': 'Calculatorul de trasee nu e disponibil acum.',
  'hiba.helykereso': 'Căutarea de locuri nu e disponibilă acum.',
  'hiba.helykeresoNema': 'Căutarea de locuri nu răspunde.',
  'hiba.haromBetu': 'Scrie cel puțin trei litere.',
  'hiba.nincsHely': 'Nu am găsit niciun loc pentru: „{mit}”',
  'hiba.elorejelzes': 'Prognoza nu e disponibilă acum.',
  'hiba.homerseklet': 'Temperatura nu e disponibilă acum.',
  'hiba.magassag': 'Datele de altitudine nu sunt disponibile acum.',
  'hiba.osmNema': 'Căutarea OpenStreetMap nu răspunde.',
  'hiba.tulterhelt': 'Căutarea e supraîncărcată. Încearcă peste câteva secunde.',
  'hiba.terheles': 'Căutarea nu face față. Încearcă peste câteva secunde.',
  'hiba.keresesNemSikerult': 'Căutarea a eșuat.',
  'hiba.ismeretlenReteg': 'Strat necunoscut.',
  'hiba.nincsHelyzet': 'Acest browser nu îți poate spune poziția.',
  'gpx.nemTud': 'Acest browser nu poate citi GPX.',
  'gpx.serult': 'Acest fișier nu e GPX lizibil — corupt sau alt format.',
  'gpx.ures': 'În acest fișier nu e nici traseu, nici marcaje.',
  'gpx.nagy': 'Fișierul are peste 5 MB. Un traseu atât de mare nu poate fi afișat rezonabil.',
  'gpx.nemSikerult': 'Fișierul nu a putut fi citit.',
  'terv.ujKezdtel': 'Ai început un traseu nou — cu săgeata îl recuperezi pe cel anterior.',
  'terv.betoltve': 'Încărcat. Trage punctele sau adaugă marcaje.',
  'terv.vagolapon': 'Linkul e în clipboard — traseul e chiar în adresă.',
  'terv.cimsorban': 'Linkul de partajat e în bara de adrese a browserului.',
  'terv.elmentve': 'Salvat. Pe alt dispozitiv ajungi la el cu linkul de partajat.',
  'terv.nevtelen': 'Plan fără nume',
  'terv.mentesFrissit': 'Actualizează salvarea',
  'terv.mentesBongeszobe': 'Salvează în browser',
  'terkep.cel': 'Sosire',
  'terkep.kozremukodoi': 'contribuitori',
  'hh.koordinata': 'coordonate introduse',
  'nap.ketNapMulva': 'Peste două zile',
  'turak.jelzettUt': 'traseu marcat',
  'kep.lasdForras': 'vezi sursa',
  'ut.ketPont': 'Sunt nevoie de cel puțin două puncte.',
  'ut.nemErheto': 'Calculatorul de trasee nu e disponibil acum. Încearcă mai târziu.',
  'ut.tulSok': 'Prea multe cereri într-un timp scurt. Așteaptă puțin.',
  'ut.hibat': 'Calculatorul de trasee a dat eroare.',
  'ut.nincsGyalogut': 'Între aceste puncte nu am găsit potecă. Poate e apă sau un gard între ele.',
  'ut.nemSikerult': 'Nu s-a găsit niciun traseu.',
  'ut.tulSokPont': 'Pot alinia pe poteci cel mult {max} puncte odată. Șterge câteva sau împarte în segmente.',
  'ut.nincsGyalogut2': 'Între aceste puncte nu am găsit potecă. Poate trece peste apă sau teren fără drum.',
  'terv.egyenesMarad': '{ok} Linia rămâne deocamdată dreaptă, așa că distanța și urcarea sunt mai mici decât în realitate.',
  'adat.tengerszintUtan': 'deasupra nivelului mării',

  /* ---- Főoldal: mit tud, kiemelt példa ---- */
  'fooldal.peldaKalap': 'Așa arată ce primești',
  'fooldal.peldaNyisd': 'Deschide în planificator',
  'fooldal.mitTud': 'Ce poate harta asta',
  'fooldal.mitTudLead': 'Patru motive să planifici aici, nu pe o hartă generală.',
  'fooldal.tud1Cim': 'Linia urmează poteci reale',
  'fooldal.tud1': 'Nu e o linie dreaptă între două puncte. Marchează două locuri și traseul se așază singur pe potecile reale — de aceea distanța și urcarea sunt corecte.',
  'fooldal.tud2Cim': 'Timpul de mers ține cont de urcare',
  'fooldal.tud2': 'Zece kilometri pe plat și zece pe munte nu înseamnă același timp. Estimarea adaugă pentru fiecare sută de metri de urcare și arată și profilul altimetric.',
  'fooldal.tud3Cim': 'Îți arată ce e prin apropiere',
  'fooldal.tud3': 'Șapte straturi din OpenStreetMap: apă potabilă, adăposturi, stații, parcări, belvedere, mâncare, obiective. În orice țară din lume.',
  'fooldal.tud4Cim': 'Rămâne al tău',
  'fooldal.tud4': 'Ce desenezi se creează în browserul tău. Linkul de partajat duce traseul însuși, nu un id din bază — și îl poți descărca în GPX, pentru orice ceas sau aplicație.',
  'adat.menetido': 'timp de mers',
};
