/* Română. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — pagina principală',
  'fejlec.menuNyit': 'Deschide meniul',
  'fejlec.menuZar': 'Închide meniul',
  'fejlec.foMenu': 'Meniu principal',
  'fejlec.sotetMod': 'Comută modul întunecat',
  'fejlec.fok': 'Acum {fok} grade — {ido}',
  'fejlec.jelenleg': 'În prezent',

  'menu.fooldal': 'Acasă',
  'menu.fooldalLeiras': 'Marcaje turistice, exemple și păreri',
  'menu.tervezo': 'Planificator',
  'menu.tervezoLeiras': 'Scrie două locuri sau desenează pe hartă',
  'menu.peldak': 'Exemple',
  'menu.peldakLeiras': 'Trasee gata făcute de la care poți porni',

  'lab.terkep': 'Harta este făcută de colaboratorii {osm}, care furnizează și dalele.',
  'lab.becsles': 'Distanța și timpul de mers sunt estimări — pe teren contează traseele marcate.',
  'lab.impresszum': 'Despre site și date',

  'fooldal.cim': 'Túrabakancs — hartă pentru planificarea traseelor',
  'fooldal.lead': 'O hartă pe care poți desena. Trasee gata făcute de la care să pornești. Timp de mers care ține cont și de urcare.',
  'fooldal.tervezek': 'Planific o drumeție',
  'fooldal.peldak': 'Văd exemple',
  'fooldal.ma': 'Azi',
  'fooldal.napkelte': 'răsărit',
  'fooldal.napnyugta': 'apus',
  'fooldal.vilagosMeg': 'lumină rămasă',
  'fooldal.lement': 'a apus',
  'fooldal.vanMeg': 'încă e lumină',
  'fooldal.marLement': 'soarele a apus',
  'fooldal.napAlap': 'Pentru Budapesta. Planificatorul calculează pentru punctul de plecare al traseului tău.',
  'fooldal.jelzesCim': 'Ce înseamnă vopseaua de pe copac?',
  'fooldal.jelzesLead': 'Un marcaj turistic maghiar spune două lucruri deodată. Culoarea arată cât de mare este traseul, forma arată la ce folosește.',
  'fooldal.jelzesSzin': 'culoare',
  'fooldal.jelzesAlak': 'formă',
  'fooldal.jelzesApro': 'Nu am scris asta din memorie: am verificat pe potecile marcate din OpenStreetMap ce unde duce. Traseele cu triunghi se termină pe un vârf sau la un punct de belvedere, cele cu cerc se întorc de unde au plecat.',
  'fooldal.keszVonal': 'Începe cu un traseu gata făcut',
  'fooldal.keszVonalLead': 'Deschide-l, trage punctele, fă-l al tău.',
  'fooldal.szerintunk': 'după noi',
  'fooldal.osszesPelda': 'Toate exemplele →',

  'peldak.kicsi': 'Exemple',
  'peldak.cim': 'Trasee gata făcute de la care poți porni.',
  'peldak.bevezeto': 'Deschide oricare, trage punctele, pune propriile marcaje — și e al tău.',
  'peldak.tajegyseg': 'Regiune',
  'peldak.mindegyik': 'Toate',
  'peldak.hossz': 'Lungime',
  'peldak.nehezseg': 'Dificultate',
  'peldak.torold': 'șterge tot',
  'peldak.szurokTorol': 'șterge filtrele',
  'peldak.utvonal': 'trasee',
  'peldak.megnezem': 'Vezi',
  'peldak.gyalogut': 'Traseele urmează poteci reale',
  'peldak.gyalogutUtan': ', nu pe o linie dreaptă între două puncte — de aceea distanța și urcarea sunt corecte. Pe teren rămân valabile traseele marcate și hărțile oficiale.',
  'peldak.darab': '{db} trasee',

  'utvonal.nincs': 'Acest traseu nu există.',
  'utvonal.tobbi': 'Iată celelalte exemple.',
  'utvonal.hossz': 'Lungime',
  'utvonal.sik': 'Calculat pentru teren plat; la urcare mai mult.',
  'utvonal.jelolesek': 'Marcaje',
  'utvonal.kozelito': 'Traseu aproximativ, nu potecă măsurată.',
  'utvonal.megnyitas': 'Deschide în planificator',
  'utvonal.gpx': 'Descarcă GPX',

  'tervezo.honnanHova': 'De unde până unde?',
  'tervezo.adatok': 'Datele traseului',
  'tervezo.adatokCimke': 'Datele traseului — {km}, {ido}',
  'tervezo.eszkozok': 'Salvare, trasee gata făcute, GPX',
  'tervezo.vissza': 'Un pas înapoi',
  'tervezo.retegek': 'Ce să arate harta',
  'tervezo.ujraKeres': 'Caută în această zonă',

  'hh.honnan': 'De unde',
  'hh.hova': 'Până unde — dacă lași gol, doar sărim acolo',
  'hh.honnanHely': 'Numele locului sau coordonate',
  'hh.hovaHely': 'De exemplu: Vârful Omu',
  'hh.innen': 'Pornesc de aici',
  'hh.odaugras': 'Sari acolo',
  'hh.szamolom': 'Calculez…',
  'hh.utvonalat': 'Vreau un traseu',
  'hh.keres': 'Caut…',
  'hh.nincsHelyzet': 'Nu am putut obține poziția ta. Scrie punctul de plecare manual.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'lungime',
  'adat.emelkedo': 'urcare',
  'adat.lejto': 'coborâre',
  'adat.nehezseg': 'dificultate',
  'adat.tempo': 'Ritm',
  'adat.tengerszint': '{also}–{felso} m deasupra nivelului mării',
  'adat.nev': 'De exemplu: tura de duminică',

  'terkep.igazit': 'Aliniez linia la potecile reale…',
  'terkep.masodik': 'Marchează al doilea punct — linia se așază singură pe potecă.',
  'terkep.keszUt': 'Traseu gata. Atinge harta dacă vrei unul nou.',
  'terkep.sug': 'Atinge harta pentru puncte. Punctele pot fi trase; o atingere le șterge.',
  'terkep.keszVonal': 'Gata — linia urmează poteci reale.',
  'terkep.jelolesTorol': 'Șterge marcajul',
  'terkep.tobbVan': 'sunt mai multe aici — apropie harta',
  'terkep.keresem': 'caut…',
  'terkep.nagyits': 'apropie harta',
  'terkep.hiba': 'nu a reușit',
  'terkep.nincsAdat': 'fără date',

  'reteg.viz': 'Apă potabilă, izvor',
  'reteg.menedek': 'Adăpost',
  'reteg.kozlekedes': 'Stație, gară',
  'reteg.parkolo': 'Parcare',
  'reteg.kilato': 'Belvedere',
  'reteg.vendeglatas': 'Mâncare și băutură',
  'reteg.latvany': 'Obiectiv turistic',

  'nincs.cim': 'Nu există o astfel de pagină',
  'nincs.magyarazat': 'Fie ai greșit adresa, fie duce la o pagină care nu mai există.',
  'nincs.lead': 'De aici poți merge mai departe:',
  'nincs.kezdolap': 'Acasă',
  'nincs.tervezo': 'Planificator de trasee',
  'nincs.tervezoLeiras': 'desenează o drumeție pe hartă',
  'nincs.peldak': 'Trasee gata făcute',
  'nincs.peldakLeiras': 'exemple pe care le poți deschide',

  'meta.fooldalCim': 'Túrabakancs — trasee, marcaje, păreri',
  'meta.fooldalLeiras': 'Hartă pentru planificarea traseelor, explicarea marcajelor turistice maghiare și păreri fără nume.',
  'meta.tervezoCim': 'Planificator — Túrabakancs',
  'meta.tervezoLeiras': 'Desenează un traseu pe hartă, pune marcaje, trimite-l cu un link.',
  'meta.peldakCim': 'Trasee exemplu — Túrabakancs',
  'meta.peldakLeiras': 'Trasee gata făcute pe hartă, pe care le poți deschide și redesena.',
  'meta.impresszumCim': 'Despre site și date — Túrabakancs',
  'meta.impresszumLeiras': 'La ce e bun site-ul și la ce nu. Fără cont, fără cookie-uri, fără urmărire; ce desenezi rămâne în browserul tău.',
  'meta.nincsCim': 'Nu există o astfel de pagină — Túrabakancs',
  'meta.nincsLeiras': 'Această adresă nu există.',
};
