/* Slovenčina. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — domov',
  'fejlec.menuNyit': 'Otvoriť ponuku',
  'fejlec.menuZar': 'Zavrieť ponuku',
  'fejlec.foMenu': 'Hlavná ponuka',
  'fejlec.sotetMod': 'Prepnúť tmavý režim',
  'fejlec.fok': 'Teraz {fok} stupňov — {ido}',
  'fejlec.jelenleg': 'Práve teraz',

  'menu.fooldal': 'Domov',
  'menu.fooldalLeiras': 'Turistické značky, príklady a názory',
  'menu.tervezo': 'Plánovač',
  'menu.tervezoLeiras': 'Zadaj dve miesta alebo kresli do mapy',
  'menu.peldak': 'Príklady',
  'menu.peldakLeiras': 'Hotové trasy, z ktorých môžeš vyjsť',

  'lab.terkep': 'Mapu tvoria prispievatelia {osm}, ktorí dodávajú aj dlaždice.',
  'lab.becsles': 'Vzdialenosť a čas chôdze sú odhady — v teréne platia značené turistické chodníky.',
  'lab.impresszum': 'O stránke a ochrana údajov',

  'fooldal.cim': 'Túrabakancs — mapa na plánovanie turistických trás',
  'fooldal.lead': 'Mapa, do ktorej sa dá kresliť. Hotové túry na začiatok. Čas chôdze, ktorý ráta aj so stúpaním.',
  'fooldal.tervezek': 'Naplánujem túru',
  'fooldal.peldak': 'Pozriem príklady',
  'fooldal.ma': 'Dnes',
  'fooldal.napkelte': 'východ slnka',
  'fooldal.napnyugta': 'západ slnka',
  'fooldal.vilagosMeg': 'ešte svetla',
  'fooldal.lement': 'zapadlo',
  'fooldal.vanMeg': 'ešte je svetlo',
  'fooldal.marLement': 'slnko už zapadlo',
  'fooldal.napAlap': 'Pre Budapešť. Plánovač ráta so začiatkom tvojej vlastnej trasy.',
  'fooldal.jelzesCim': 'Čo znamená farba na strome?',
  'fooldal.jelzesLead': 'Maďarská turistická značka hovorí dve veci naraz. Farba to, aká veľká je trasa, tvar to, na čo slúži.',
  'fooldal.jelzesSzin': 'farba',
  'fooldal.jelzesAlak': 'tvar',
  'fooldal.jelzesApro': 'Nepísali sme to spamäti: overili sme si to na značených chodníkoch v OpenStreetMape, čo kam vedie. Trasy s trojuholníkom končia na vrchole alebo pri rozhľadni, trasy s kruhom sa vracajú tam, odkiaľ vyšli.',
  'fooldal.keszVonal': 'Začni hotovou trasou',
  'fooldal.keszVonalLead': 'Otvor ju, potiahni body, sprav si ju vlastnou.',
  'fooldal.szerintunk': 'podľa nás',
  'fooldal.osszesPelda': 'Všetky príklady →',

  'peldak.kicsi': 'Príklady',
  'peldak.cim': 'Hotové trasy, z ktorých môžeš vyjsť.',
  'peldak.bevezeto': 'Otvor ktorúkoľvek, potiahni jej body, pridaj vlastné značky — a je tvoja.',
  'peldak.tajegyseg': 'Oblasť',
  'peldak.mindegyik': 'Všetky',
  'peldak.hossz': 'Dĺžka',
  'peldak.nehezseg': 'Náročnosť',
  'peldak.torold': 'zmazať všetko',
  'peldak.szurokTorol': 'zrušiť filtre',
  'peldak.utvonal': 'trás',
  'peldak.megnezem': 'Pozrieť',
  'peldak.gyalogut': 'Trasy vedú po skutočných peších chodníkoch',
  'peldak.gyalogutUtan': ', nie po priamke medzi dvoma bodmi — preto vzdialenosť a stúpanie sedia. V teréne aj tak platia značené chodníky a oficiálne mapy.',
  'peldak.darab': '{db} trás',

  'utvonal.nincs': 'Táto trasa neexistuje.',
  'utvonal.tobbi': 'Tu sú ostatné príklady.',
  'tempo.gyalog': 'Pešo',
  'tempo.futas': 'Beh',
  'tempo.bringa': 'Bicykel',
  'utvonal.elgepelt': 'Možno si sa preklepol v adrese.',
  'utvonal.kozelitoUtan': ' V teréne platia značené turistické chodníky a oficiálne mapy.',
  'utvonal.hossz': 'Dĺžka',
  'utvonal.sik': 'Rátané pre rovinu; do kopca viac.',
  'utvonal.jelolesek': 'Značky',
  'utvonal.kozelito': 'Približný priebeh, nie zameraný turistický chodník.',
  'utvonal.megnyitas': 'Otvoriť v plánovači',
  'utvonal.gpx': 'Stiahnuť GPX',

  'tervezo.honnanHova': 'Odkiaľ kam?',
  'tervezo.adatok': 'Údaje o trase',
  'tervezo.adatokCimke': 'Údaje o trase — {km}, {ido}',
  'tervezo.eszkozok': 'Uloženie, hotové trasy, GPX',
  'tervezo.vissza': 'O krok späť',
  'tervezo.retegek': 'Čo má mapa ukazovať',
  'tervezo.ujraKeres': 'Hľadať v tejto oblasti',

  'hh.honnan': 'Odkiaľ',
  'hh.hova': 'Kam — ak necháš prázdne, iba tam skočíme',
  'hh.honnanHely': 'Názov miesta alebo súradnice',
  'hh.hovaHely': 'Napríklad: Kriváň',
  'hh.innen': 'Vyrazím odtiaľto',
  'hh.odaugras': 'Skočiť tam',
  'hh.szamolom': 'Počítam…',
  'hh.utvonalat': 'Chcem trasu',
  'hh.keres': 'Hľadám…',
  'hh.nincsHelyzet': 'Nepodarilo sa zistiť tvoju polohu. Zadaj východiskový bod ručne.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'dĺžka',
  'adat.emelkedo': 'stúpanie',
  'adat.lejto': 'klesanie',
  'adat.nehezseg': 'náročnosť',
  'adat.tempo': 'Tempo',
  'adat.tengerszint': '{also}–{felso} m n. m.',
  'adat.nev': 'Napríklad: nedeľný okruh',

  'terkep.igazit': 'Prikladám líniu na skutočné chodníky…',
  'terkep.masodik': 'Označ druhý bod — línia si sama sadne na chodník.',
  'terkep.keszUt': 'Trasa hotová. Ťukni do mapy, ak chceš novú.',
  'terkep.sug': 'Ťukni do mapy a pridaj body. Body sa dajú ťahať; ťuknutím sa zmažú.',
  'terkep.keszVonal': 'Hotovo — línia vedie po skutočných peších chodníkoch.',
  'jeloles.ugras': 'Skočiť sem: {nev}',
  'jeloles.neve': 'Názov: {tipus}',
  'terkep.jelolesTorol': 'Zmazať značku',
  'terkep.tobbVan': 'je toho tu viac — priblíž si to',
  'terkep.keresem': 'hľadám…',
  'terkep.nagyits': 'priblíž si to',
  'terkep.hiba': 'nepodarilo sa',
  'terkep.nincsAdat': 'bez údajov',

  'reteg.viz': 'Pitná voda, prameň',
  'reteg.menedek': 'Prístrešok',
  'reteg.kozlekedes': 'Zastávka, stanica',
  'reteg.parkolo': 'Parkovisko',
  'reteg.kilato': 'Rozhľadňa',
  'reteg.vendeglatas': 'Jedlo a pitie',
  'reteg.latvany': 'Pamiatka',

  'nincs.cim': 'Takáto stránka neexistuje',
  'nincs.magyarazat': 'Buď si sa preklepol v adrese, alebo ukazuje na stránku, ktorá už neexistuje.',
  'nincs.lead': 'Odtiaľto môžeš pokračovať:',
  'nincs.kezdolap': 'Domov',
  'nincs.tervezo': 'Plánovač trás',
  'nincs.tervezoLeiras': 'nakresli túru do mapy',
  'nincs.peldak': 'Hotové trasy',
  'nincs.peldakLeiras': 'príklady, ktoré môžeš otvoriť',

  'meta.fooldalCim': 'Túrabakancs — turistické trasy, značky, názory',
  'meta.fooldalLeiras': 'Mapa na plánovanie trás, vysvetlenie maďarských turistických značiek a názory bez mien.',
  'meta.tervezoCim': 'Plánovač — Túrabakancs',
  'meta.tervezoLeiras': 'Nakresli trasu do mapy, pridaj značky, zdieľaj ju odkazom.',
  'meta.peldakCim': 'Vzorové trasy — Túrabakancs',
  'meta.peldakLeiras': 'Hotové turistické trasy v mape, ktoré môžeš otvoriť a ďalej kresliť.',
  'meta.impresszumCim': 'O stránke a ochrana údajov — Túrabakancs',
  'meta.impresszumLeiras': 'Na čo stránka je a na čo nie. Žiadny účet, žiadne cookies, žiadne meranie; čo nakreslíš, zostáva v tvojom prehliadači.',
  'meta.nincsCim': 'Takáto stránka neexistuje — Túrabakancs',
  'meta.nincsLeiras': 'Táto adresa neexistuje.',

  /* ---- Nehézség, szűrők, ajánló ---- */
  'nehez.konnyu': 'Ľahká',
  'nehez.kozepes': 'Stredná',
  'nehez.eros': 'Náročná',
  'nehez.nehez': 'Ťažká',
  'nehez.konnyuLeiras': 'Krátka prechádzka, zvládne ju každý.',
  'nehez.kozepesLeiras': 'Pol dňa, netreba na to kondíciu.',
  'nehez.erosLeiras': 'Celodenná túra, priprav sa na ňu.',
  'nehez.nehezLeiras': 'Dlhý deň. Len so skúsenosťami a výstrojom.',
  'szuro.rovid': 'Krátka',
  'szuro.kozepes': 'Stredná',
  'szuro.hosszu': 'Dlhá',
  'szuro.rovidLeiras': 'pod 3 km',
  'szuro.kozepesLeiras': '3–8 km',
  'szuro.hosszuLeiras': 'nad 8 km',
  'tanacs.osszkepCimke': '{nehez} — {ido} chôdze',
  'tanacs.osszkepMagassag': '{km} km, {fel} m stúpania. {leiras} Čas chôdze je bez prestávok; prirátaj aspoň pol hodiny.',
  'tanacs.osszkepNincs': '{km} km. {leiras} Stúpanie sa ešte načítava; dovtedy čas chôdze ráta len so vzdialenosťou.',
  'tanacs.sotetCimke': 'Slnko už zapadlo',
  'tanacs.sotetSzoveg': 'Západ slnka bol dnes o {ido}. Ak vyrážaš teraz, nechoď bez čelovky.',
  'tanacs.sotetedesCimke': 'Nestihneš to pred zotmením',
  'tanacs.sotetedesSzoveg': 'Západ slnka o {nyugta}, dovtedy je {maradek}. Trasa trvá {ut}, bez prestávok. Vezmi si čelovku alebo vyraz skôr.',
  'tanacs.vilagosCimke': '{maradek} do západu slnka',
  'tanacs.vilagosSzoveg': 'Dnes sa stmieva o {ido}. Ak vyrážaš teraz, máš času dosť.',
  'tanacs.visszautCimke': 'Cieľ nie je tam, kde štart',
  'tanacs.visszautSzoveg': 'Delí ich {tav} km. Ak ideš autom, premysli si, ako sa k nemu vrátiš — alebo naplánuj okruh.',
  'tanacs.vizCimke': 'Nie je označené miesto na vodu',
  'tanacs.vizSzoveg': 'Na {km} km je to málo. Zapni vrstvu s pitnou vodou: ukážem, čo je v okolí.',
  'tanacs.megkozelitesCimke': 'Nie je označené, ako sa dostaneš na štart',
  'tanacs.megkozelitesSzoveg': 'Pred vyrazením to bude prvá otázka. Vrstvou so zastávkami zistíš, čo je v okolí.',
  'tanacs.durvaCimke': 'Línia je veľmi rovná',
  'tanacs.durvaSzoveg': 'Priemerne {atlag} km na úsek. Skutočný chodník sa kľukatí, takže reálna vzdialenosť je väčšia — naklikaj viac bodov pre presnejší obraz.',
  'tanacs.emelkedoCimke': '{fel} metrov stúpania',
  'tanacs.emelkedoSzoveg': 'Najnižší bod je {min} m, najvyšší {max} m. Samotné toto stúpanie predĺži čas chôdze o {plusz}.',
  'tanacs.veszelyCimke': 'Označil si ťažký úsek',
  'tanacs.veszelySzoveg': 'Po daždi a v mraze sú strmé, skalnaté úseky oveľa pomalšie a rizikovejšie. Pred vyrazením si pozri počasie.',

  /* ---- Időjárás és jelöléstípusok ---- */
  'ido.derult': 'Jasno',
  'ido.jobbaraDerult': 'Prevažne jasno',
  'ido.szakadozott': 'Polooblačno',
  'ido.borult': 'Zamračené',
  'ido.kod': 'Hmla',
  'ido.zuzmarasKod': 'Mrznúca hmla',
  'ido.gyengeSzitalas': 'Slabé mrholenie',
  'ido.szitalas': 'Mrholenie',
  'ido.erosSzitalas': 'Silné mrholenie',
  'ido.gyengeEso': 'Slabý dážď',
  'ido.eso': 'Dážď',
  'ido.erosEso': 'Silný dážď',
  'ido.gyengeHavazas': 'Slabé sneženie',
  'ido.havazas': 'Sneženie',
  'ido.erosHavazas': 'Silné sneženie',
  'ido.hoszemcsek': 'Snehové zrnká',
  'ido.zapor': 'Prehánky',
  'ido.hevesZapor': 'Silné prehánky',
  'ido.hozapor': 'Snehové prehánky',
  'ido.erosHozapor': 'Silné snehové prehánky',
  'ido.zivatar': 'Búrka',
  'ido.jegesoZivatar': 'Búrka s krupobitím',
  'ido.hevesJegeso': 'Silná búrka s krupobitím',
  'ido.ismeretlen': 'Neznáme',
  'idoFigy.zivatar': 'Očakávajú sa búrky. Na hrebeni ani na rozhľadni vtedy nemáš čo robiť.',
  'idoFigy.sokCsapadek': '{mm} mm zrážok: skalnaté úseky a rebríky budú klzké.',
  'idoFigy.eso': 'Očakáva sa dážď — na blatistých svahoch pôjdeš pomalšie.',
  'idoFigy.meleg': '{fok} stupňov: na úsekoch bez tieňa si vezmi dvojnásobok vody.',
  'idoFigy.fagy': 'Nad ránom {fok} stupňov: trasa môže byť zľadovatená.',
  'idoFigy.szel': 'Vietor {szel} km/h: na hrebeni nepríjemný, na rozhľadni studený.',
  'tipus.kilato': 'Rozhľadňa',
  'tipus.forras': 'Prameň, pitná voda',
  'tipus.pihen': 'Odpočívadlo, lavička',
  'tipus.parkolo': 'Parkovisko',
  'tipus.vendeglatas': 'Jedlo a pitie',
  'tipus.latnivalo': 'Pamiatka',
  'tipus.veszely': 'Nebezpečenstvo, ťažký úsek',
  'tipus.kozlekedes': 'Zastávka, stanica',

  /* ---- Tanácsok, túralista, napnevek ---- */
  'tanacs.lekerem': 'Načítavam…',
  'tanacs.milyenIdo': 'Aké bude počasie?',
  'nap.ma': 'dnes',
  'nap.holnap': 'zajtra',
  'turak.lead': 'Ukážem ti, aké {jelzett} vedú tam, kde je práve mapa. Ktorúkoľvek môžeš načítať a kresliť ďalej.',
  'turak.jelzett': 'značené chodníky',
  'turak.keresem': 'Hľadám…',
  'turak.keres': 'Hľadať chodníky v tejto oblasti',
  'turak.tolt': 'načítavam…',
  'turak.festett': 'V teréne platí namaľovaná značka.',

  /* ---- Impresszum és adatkezelés ---- */
  'imp.cim': 'O stránke a ochrana údajov',
  'imp.felelossegCim': 'Zodpovednosť — prečítaj si to, než vyrazíš',
  'imp.felelossegLead': 'Stránka ukazuje trasy, vzdialenosti, stúpania, časy chôdze a západ slnka. Sú to {eros}, nie záruky:',
  'imp.felelossegEros': 'výpočty a odhady',
  'imp.felelosseg1': 'Línie sledujú pešie chodníky z mapových údajov. Či je daný chodník práve schodný, mapa nevie — môže naň spadnúť strom, môže ho vymyť dážď, môže byť uzavretý.',
  'imp.felelosseg2': 'Čas chôdze ráta s rovinou a priemerným tempom. Záťaž, sneh, blato, zotmenie a tvoja kondícia to všetko prebijú.',
  'imp.felelosseg3': 'Stúpanie pochádza z výškového modelu, ktorý sa môže o pár metrov líšiť od skutočnosti.',
  'imp.felelossegZaro': '{eros} Na orientáciu slúžia značené turistické chodníky a oficiálne mapy; pred vyrazením si pozri počasie a povedz niekomu, kam ideš. Táto stránka pomáha plánovať — nenahrádza zdravý rozum.',
  'imp.felelossegZaroEros': 'V teréne platí tvoje vlastné rozhodnutie a zodpovednosť.',
  'imp.tartalomCim': 'Obsah',
  'imp.tartalom': 'Hviezdičkové hodnotenia sú náš názor, nie priemer cudzích bodov. Mapové údaje pochádzajú z OpenStreetMap, ktorý udržiavajú dobrovoľníci. Fotografie pamiatok sú pod voľnými licenciami, s menami autorov — celý zoznam nižšie, pod {link}.',
  'imp.adatCim': 'Ochrana údajov',
  'imp.adat1': 'Stránka nežiada účet, nezbiera osobné údaje a nepoužíva cookies. Čo nakreslíš, vzniká v tvojom prehliadači a tam aj zostáva: uložené plány idú do úložiska tvojho zariadenia a zdieľateľný odkaz vkladá trasu priamo do adresy, nie do databázy.',
  'imp.adat2': 'To, čo predsa len ide na internet, nejde k nám. Mapové dlaždice a odpovede vyhľadávania miest dávajú verejné služby OpenStreetMap, výškové údaje Open-Meteo a prikladanie trás na chodníky pešia navigácia FOSSGIS. Keď ukážeš na pamiatku, jej obrázok dodá Wikimedia Commons — až vtedy, keď na ňu ukážeš. Vtedy — ako pri každom obrázku na každej stránke — im je vidieť tvoju IP adresu a pri prikladaní a výške aj súradnice tvojej línie. Tomu sa nedá vyhnúť, ak chceme ukázať mapu; aspoň však o tom vieš.',
  'imp.kepekCim': 'Obrázky',
  'imp.kepek': 'Fotografie pamiatok pochádzajú z Wikimedia Commons a sú pod voľnými licenciami — voľné však neznamená bez majiteľa: každá má autora, ktorého treba uviesť. Obrázok sa načíta až vtedy, keď ukážeš na pamiatku, a meno autora je vždy pri ňom. Zoznam nižšie uvádza pätnásť maďarských miest, ktorých obrázky máme u seba.',

  /* ---- Alfajták és ivhatóság ---- */
  'fajta.ivoviz': 'Pitná voda',
  'fajta.forras': 'Prameň',
  'fajta.esobeallo': 'Prístrešok',
  'fajta.menedekhaz': 'Útulňa',
  'fajta.turistahaz': 'Chata',
  'fajta.vasutallomas': 'Železničná stanica',
  'fajta.megallohely': 'Zastávka',
  'fajta.buszmegallo': 'Autobusová zastávka',
  'fajta.parkolo': 'Parkovisko',
  'fajta.kilatopont': 'Vyhliadka',
  'fajta.kilatotorony': 'Rozhľadňa',
  'fajta.etterem': 'Reštaurácia',
  'fajta.kavezo': 'Kaviareň',
  'fajta.kocsma': 'Krčma',
  'fajta.bufe': 'Bufet',
  'fajta.var': 'Hrad, zámok',
  'fajta.rom': 'Zrúcanina',
  'fajta.regeszeti': 'Archeologická lokalita',
  'fajta.emlekmu': 'Pamätník',
  'fajta.muzeum': 'Múzeum',
  'fajta.vizeses': 'Vodopád',
  'fajta.barlang': 'Vchod do jaskyne',
  'fajta.sziklakapu': 'Skalná brána',
  'fajta.vilagitotorony': 'Maják',
  'fajta.latnivalo': 'Zaujímavosť',
  'viz.ihato': 'pitná',
  'viz.nemIhato': 'NIE je pitná',
  'viz.nincsAdat': 'bez údaja, či je pitná',

  /* ---- Hibaüzenetek és apróságok ---- */
  'hiba.utvonalkereso': 'Vyhľadávač trás je momentálne nedostupný.',
  'hiba.helykereso': 'Vyhľadávanie miest je momentálne nedostupné.',
  'hiba.helykeresoNema': 'Vyhľadávanie miest neodpovedá.',
  'hiba.haromBetu': 'Napíš aspoň tri písmená.',
  'hiba.nincsHely': 'Pre toto som nenašiel miesto: „{mit}“',
  'hiba.elorejelzes': 'Predpoveď je momentálne nedostupná.',
  'hiba.homerseklet': 'Teplota je momentálne nedostupná.',
  'hiba.magassag': 'Výškové údaje sú momentálne nedostupné.',
  'hiba.osmNema': 'Vyhľadávanie OpenStreetMap neodpovedá.',
  'hiba.tulterhelt': 'Vyhľadávanie je preťažené. Skús to o pár sekúnd.',
  'hiba.terheles': 'Vyhľadávanie nezvláda záťaž. Skús to o pár sekúnd.',
  'hiba.keresesNemSikerult': 'Vyhľadávanie zlyhalo.',
  'hiba.ismeretlenReteg': 'Neznáma vrstva.',
  'hiba.nincsHelyzet': 'Tento prehliadač nevie zistiť tvoju polohu.',
  'gpx.nemTud': 'Tento prehliadač nevie čítať GPX.',
  'gpx.serult': 'Tento súbor nie je čitateľné GPX — poškodený alebo iný formát.',
  'gpx.ures': 'V tomto súbore nie je ani trasa, ani značky.',
  'gpx.nagy': 'Tento súbor má viac ako 5 MB. Takú veľkú trasu neviem rozumne zobraziť.',
  'gpx.nemSikerult': 'Tento súbor sa nepodarilo načítať.',
  'terv.ujKezdtel': 'Začal si novú trasu — šípkou získaš späť predchádzajúcu.',
  'terv.betoltve': 'Načítané. Potiahni body alebo pridaj značky.',
  'terv.vagolapon': 'Odkaz je v schránke — trasa je priamo v adrese.',
  'terv.cimsorban': 'Zdieľateľný odkaz je v adresnom riadku prehliadača.',
  'terv.elmentve': 'Uložené. Na inom zariadení sa k tomu dostaneš cez zdieľateľný odkaz.',
  'terv.nevtelen': 'Nepomenovaný plán',
  'terv.mentesFrissit': 'Aktualizovať uloženie',
  'terv.mentesBongeszobe': 'Uložiť do prehliadača',
  'terkep.cel': 'Cieľ',
  'terkep.kozremukodoi': 'prispievatelia',
  'terkep.rajt': 'Štart',
  'terkep.hanyadikPont': '{n}. bod',
  'hh.koordinata': 'zadané súradnice',
  'nap.ketNapMulva': 'O dva dni',
  'turak.jelzettUt': 'značený chodník',
  'kep.lasdForras': 'pozri zdroj',
  'ut.ketPont': 'Treba na to aspoň dva body.',
  'ut.nemErheto': 'Vyhľadávač trás je teraz nedostupný. Skús to neskôr.',
  'ut.tulSok': 'Príliš veľa požiadaviek za krátky čas. Chvíľu počkaj.',
  'ut.hibat': 'Vyhľadávač trás vrátil chybu.',
  'ut.nincsGyalogut': 'Medzi týmito bodmi som nenašiel pešiu cestu. Možno je medzi nimi voda alebo plot.',
  'ut.nemSikerult': 'Nepodarilo sa nájsť trasu.',
  'ut.tulSokPont': 'Naraz viem priložiť na chodníky najviac {max} bodov. Zmaž niekoľko alebo to rozdeľ na úseky.',
  'ut.nincsGyalogut2': 'Medzi týmito bodmi som nenašiel pešiu cestu. Možno vedie cez vodu alebo bezcestný terén.',
  'terv.egyenesMarad': '{ok} Línia zatiaľ zostáva rovná, preto sú vzdialenosť a stúpanie menšie než v skutočnosti.',
  'adat.tengerszintUtan': 'n. m.',

  /* ---- Főoldal: mit tud, kiemelt példa ---- */
  'fooldal.peldaKalap': 'Takto vyzerá, čo dostaneš',
  'fooldal.peldaNyisd': 'Otvoriť v plánovači',
  'fooldal.mitTud': 'Čo táto mapa vie',
  'fooldal.mitTudLead': 'Štyri dôvody plánovať tu, a nie na všeobecnej mape.',
  'fooldal.tud1Cim': 'Línia vedie po skutočných chodníkoch',
  'fooldal.tud1': 'Nie priamka medzi dvoma bodmi. Označ dve miesta a trasa si sama sadne na skutočné chodníky — preto vzdialenosť a stúpanie sedia.',
  'fooldal.tud2Cim': 'Čas chôdze ráta so stúpaním',
  'fooldal.tud2': 'Desať kilometrov po rovine a desať v horách nie je ten istý čas. Odhad priráta za každých sto metrov stúpania a ukáže aj výškový profil.',
  'fooldal.tud3Cim': 'Ukáže, čo je v okolí',
  'fooldal.tud3': 'Sedem vrstiev z OpenStreetMap: pitná voda, prístrešky, zastávky, parkoviská, rozhľadne, jedlo a pitie, pamiatky. V ktorejkoľvek krajine sveta.',
  'fooldal.tud4Cim': 'Zostáva to tvoje',
  'fooldal.tud4': 'Čo nakreslíš, vzniká v tvojom prehliadači. Zdieľateľný odkaz nesie samotnú trasu, nie identifikátor z databázy — a stiahneš si ju aj v GPX, do akýchkoľvek hodiniek či aplikácie.',
  'adat.menetido': 'čas chôdze',
};
