/* Slovenčina. A kulcsokat lásd a hu.js-ben — az a forrás. */

export default {
  'fejlec.kezdolap': 'Túrabakancs — domov',
  'fejlec.menuNyit': 'Otvoriť ponuku',
  'fejlec.menuZar': 'Zavrieť ponuku',
  'fejlec.foMenu': 'Hlavná ponuka',
  'fejlec.sotetMod': 'Prepnúť tmavý režim',
  'fejlec.fok': 'Teraz {fok} stupňov — {ido}',
  'fejlec.jelenleg': 'Práve teraz',

  'menu.fooldal': 'Domov',
  'menu.fooldalLeiras': 'Turistické značky, príklady a názory',
  'menu.tervezo': 'Plánovač',
  'menu.tervezoLeiras': 'Zadaj dve miesta alebo kresli do mapy',
  'menu.peldak': 'Príklady',
  'menu.peldakLeiras': 'Hotové trasy, z ktorých môžeš vyjsť',

  'lab.terkep': 'Mapu tvoria prispievatelia {osm}, ktorí dodávajú aj dlaždice.',
  'lab.becsles': 'Vzdialenosť a čas chôdze sú odhady — v teréne platia značené turistické chodníky.',
  'lab.impresszum': 'O stránke a ochrana údajov',

  'fooldal.cim': 'Túrabakancs — mapa na plánovanie turistických trás',
  'fooldal.lead': 'Mapa, do ktorej sa dá kresliť. Hotové túry na začiatok. Čas chôdze, ktorý ráta aj so stúpaním.',
  'fooldal.tervezek': 'Naplánujem túru',
  'fooldal.peldak': 'Pozriem príklady',
  'fooldal.ma': 'Dnes',
  'fooldal.napkelte': 'východ slnka',
  'fooldal.napnyugta': 'západ slnka',
  'fooldal.vilagosMeg': 'ešte svetla',
  'fooldal.lement': 'zapadlo',
  'fooldal.vanMeg': 'ešte je svetlo',
  'fooldal.marLement': 'slnko už zapadlo',
  'fooldal.napAlap': 'Pre Budapešť. Plánovač ráta so začiatkom tvojej vlastnej trasy.',
  'fooldal.jelzesCim': 'Čo znamená farba na strome?',
  'fooldal.jelzesLead': 'Maďarská turistická značka hovorí dve veci naraz. Farba to, aká veľká je trasa, tvar to, na čo slúži.',
  'fooldal.jelzesSzin': 'farba',
  'fooldal.jelzesAlak': 'tvar',
  'fooldal.jelzesApro': 'Nepísali sme to spamäti: overili sme si to na značených chodníkoch v OpenStreetMape, čo kam vedie. Trasy s trojuholníkom končia na vrchole alebo pri rozhľadni, trasy s kruhom sa vracajú tam, odkiaľ vyšli.',
  'fooldal.keszVonal': 'Začni hotovou trasou',
  'fooldal.keszVonalLead': 'Otvor ju, potiahni body, sprav si ju vlastnou.',
  'fooldal.szerintunk': 'podľa nás',
  'fooldal.osszesPelda': 'Všetky príklady →',

  'peldak.kicsi': 'Príklady',
  'peldak.cim': 'Hotové trasy, z ktorých môžeš vyjsť.',
  'peldak.bevezeto': 'Otvor ktorúkoľvek, potiahni jej body, pridaj vlastné značky — a je tvoja.',
  'peldak.tajegyseg': 'Oblasť',
  'peldak.mindegyik': 'Všetky',
  'peldak.hossz': 'Dĺžka',
  'peldak.nehezseg': 'Náročnosť',
  'peldak.torold': 'zmazať všetko',
  'peldak.szurokTorol': 'zrušiť filtre',
  'peldak.utvonal': 'trás',
  'peldak.megnezem': 'Pozrieť',
  'peldak.gyalogut': 'Trasy vedú po skutočných peších chodníkoch',
  'peldak.gyalogutUtan': ', nie po priamke medzi dvoma bodmi — preto vzdialenosť a stúpanie sedia. V teréne aj tak platia značené chodníky a oficiálne mapy.',
  'peldak.darab': '{db} trás',

  'utvonal.nincs': 'Táto trasa neexistuje.',
  'utvonal.tobbi': 'Tu sú ostatné príklady.',
  'utvonal.hossz': 'Dĺžka',
  'utvonal.sik': 'Rátané pre rovinu; do kopca viac.',
  'utvonal.jelolesek': 'Značky',
  'utvonal.kozelito': 'Približný priebeh, nie zameraný turistický chodník.',
  'utvonal.megnyitas': 'Otvoriť v plánovači',
  'utvonal.gpx': 'Stiahnuť GPX',

  'tervezo.honnanHova': 'Odkiaľ kam?',
  'tervezo.adatok': 'Údaje o trase',
  'tervezo.adatokCimke': 'Údaje o trase — {km}, {ido}',
  'tervezo.eszkozok': 'Uloženie, hotové trasy, GPX',
  'tervezo.vissza': 'O krok späť',
  'tervezo.retegek': 'Čo má mapa ukazovať',
  'tervezo.ujraKeres': 'Hľadať v tejto oblasti',

  'hh.honnan': 'Odkiaľ',
  'hh.hova': 'Kam — ak necháš prázdne, iba tam skočíme',
  'hh.honnanHely': 'Názov miesta alebo súradnice',
  'hh.hovaHely': 'Napríklad: Kriváň',
  'hh.innen': 'Vyrazím odtiaľto',
  'hh.odaugras': 'Skočiť tam',
  'hh.szamolom': 'Počítam…',
  'hh.utvonalat': 'Chcem trasu',
  'hh.keres': 'Hľadám…',
  'hh.nincsHelyzet': 'Nepodarilo sa zistiť tvoju polohu. Zadaj východiskový bod ručne.',

  'ido.perc': '{p} min',
  'ido.oraPerc': '{o} h {p} min',
  'ido.rovidPerc': '{p} min',
  'ido.rovidOra': '{o} h {p} m',
  'adat.hossz': 'dĺžka',
  'adat.emelkedo': 'stúpanie',
  'adat.lejto': 'klesanie',
  'adat.nehezseg': 'náročnosť',
  'adat.tempo': 'Tempo',
  'adat.tengerszint': '{also}–{felso} m n. m.',
  'adat.nev': 'Napríklad: nedeľný okruh',

  'terkep.igazit': 'Prikladám líniu na skutočné chodníky…',
  'terkep.masodik': 'Označ druhý bod — línia si sama sadne na chodník.',
  'terkep.keszUt': 'Trasa hotová. Ťukni do mapy, ak chceš novú.',
  'terkep.sug': 'Ťukni do mapy a pridaj body. Body sa dajú ťahať; ťuknutím sa zmažú.',
  'terkep.keszVonal': 'Hotovo — línia vedie po skutočných peších chodníkoch.',
  'terkep.jelolesTorol': 'Zmazať značku',
  'terkep.tobbVan': 'je toho tu viac — priblíž si to',
  'terkep.keresem': 'hľadám…',
  'terkep.nagyits': 'priblíž si to',
  'terkep.hiba': 'nepodarilo sa',
  'terkep.nincsAdat': 'bez údajov',

  'reteg.viz': 'Pitná voda, prameň',
  'reteg.menedek': 'Prístrešok',
  'reteg.kozlekedes': 'Zastávka, stanica',
  'reteg.parkolo': 'Parkovisko',
  'reteg.kilato': 'Rozhľadňa',
  'reteg.vendeglatas': 'Jedlo a pitie',
  'reteg.latvany': 'Pamiatka',

  'nincs.cim': 'Takáto stránka neexistuje',
  'nincs.magyarazat': 'Buď si sa preklepol v adrese, alebo ukazuje na stránku, ktorá už neexistuje.',
  'nincs.lead': 'Odtiaľto môžeš pokračovať:',
  'nincs.kezdolap': 'Domov',
  'nincs.tervezo': 'Plánovač trás',
  'nincs.tervezoLeiras': 'nakresli túru do mapy',
  'nincs.peldak': 'Hotové trasy',
  'nincs.peldakLeiras': 'príklady, ktoré môžeš otvoriť',

  'meta.fooldalCim': 'Túrabakancs — turistické trasy, značky, názory',
  'meta.fooldalLeiras': 'Mapa na plánovanie trás, vysvetlenie maďarských turistických značiek a názory bez mien.',
  'meta.tervezoCim': 'Plánovač — Túrabakancs',
  'meta.tervezoLeiras': 'Nakresli trasu do mapy, pridaj značky, zdieľaj ju odkazom.',
  'meta.peldakCim': 'Vzorové trasy — Túrabakancs',
  'meta.peldakLeiras': 'Hotové turistické trasy v mape, ktoré môžeš otvoriť a ďalej kresliť.',
  'meta.impresszumCim': 'O stránke a ochrana údajov — Túrabakancs',
  'meta.impresszumLeiras': 'Na čo stránka je a na čo nie. Žiadny účet, žiadne cookies, žiadne meranie; čo nakreslíš, zostáva v tvojom prehliadači.',
  'meta.nincsCim': 'Takáto stránka neexistuje — Túrabakancs',
  'meta.nincsLeiras': 'Táto adresa neexistuje.',
};
